/* Generated by uncursed-pp from collapse_traps.uncursed — do not edit. */
#pragma once

#include <boost/preprocessor/cat.hpp>
#include <boost/preprocessor/comparison/equal.hpp>
#include <boost/preprocessor/control/iif.hpp>
#include <boost/preprocessor/seq/for_each.hpp>
#include <boost/preprocessor/seq/size.hpp>
#include <boost/preprocessor/tuple/elem.hpp>
#include "uncursed_pp_runtime.h"

/* uncursed-pp source:
 * # Merge-machinery regression traps (ultracode review fixes). Three ways
 * # the collapse pass used to hijack lookalikes:
 * #   1. macro A's chain family (UNCURSED_PP_A_CH1_) merging with B's must
 * #      not rewrite the FRONT of a macro literally named A_CH1's own
 * #      machinery (UNCURSED_PP_A_CH1_EACH1, UNCURSED_PP_A_CH1_CH1_<n>);
 * #   2. @if branch helpers whose user params happen to spell "r, d, e"
 * #      own no spare data slot and must not be d-slot-parameterized;
 * #   3. loop bodies differing only in a lone paren must stay unmerged -
 * #      splicing '(' as FOR_EACH data unbalances the argument list.
 * @macro A($xs: seq<token>)
 * @for $x in $xs
 * f({{$x}});
 * @end
 * @endmacro
 */
#define UNCURSED_PP_COLLAPSE_TRAPS_H1(r, d, e) f(e);
#define UNCURSED_PP_COLLAPSE_TRAPS_HC3_1(e) f(e);
#define UNCURSED_PP_COLLAPSE_TRAPS_HC3_2(e) f(e); UNCURSED_PP_COLLAPSE_TRAPS_HC3_1
#define UNCURSED_PP_COLLAPSE_TRAPS_HC3_3(e) f(e); UNCURSED_PP_COLLAPSE_TRAPS_HC3_2
#define UNCURSED_PP_COLLAPSE_TRAPS_HC3_4(e) f(e); UNCURSED_PP_COLLAPSE_TRAPS_HC3_3
#define UNCURSED_PP_COLLAPSE_TRAPS_HC3_5(e) f(e); UNCURSED_PP_COLLAPSE_TRAPS_HC3_4
#define UNCURSED_PP_COLLAPSE_TRAPS_HC3_6(e) f(e); UNCURSED_PP_COLLAPSE_TRAPS_HC3_5
#define UNCURSED_PP_COLLAPSE_TRAPS_HC3_7(e) f(e); UNCURSED_PP_COLLAPSE_TRAPS_HC3_6
#define UNCURSED_PP_COLLAPSE_TRAPS_HC3_8(e) f(e); UNCURSED_PP_COLLAPSE_TRAPS_HC3_7
#define UNCURSED_PP_COLLAPSE_TRAPS_HC3_9(e) f(e); UNCURSED_PP_COLLAPSE_TRAPS_HC3_8
#define UNCURSED_PP_COLLAPSE_TRAPS_HC3_10(e) f(e); UNCURSED_PP_COLLAPSE_TRAPS_HC3_9
#define UNCURSED_PP_COLLAPSE_TRAPS_HC3_11(e) f(e); UNCURSED_PP_COLLAPSE_TRAPS_HC3_10
#define UNCURSED_PP_COLLAPSE_TRAPS_HC3_12(e) f(e); UNCURSED_PP_COLLAPSE_TRAPS_HC3_11
#define UNCURSED_PP_COLLAPSE_TRAPS_HC3_13(e) f(e); UNCURSED_PP_COLLAPSE_TRAPS_HC3_12
#define UNCURSED_PP_COLLAPSE_TRAPS_HC3_14(e) f(e); UNCURSED_PP_COLLAPSE_TRAPS_HC3_13
#define UNCURSED_PP_COLLAPSE_TRAPS_HC3_15(e) f(e); UNCURSED_PP_COLLAPSE_TRAPS_HC3_14
#define UNCURSED_PP_COLLAPSE_TRAPS_HC3_16(e) f(e); UNCURSED_PP_COLLAPSE_TRAPS_HC3_15
#define UNCURSED_PP_A_SMALL1(seq) BOOST_PP_CAT(UNCURSED_PP_COLLAPSE_TRAPS_HC3_, BOOST_PP_SEQ_SIZE(seq)) seq
#define UNCURSED_PP_A_PICK1(n) BOOST_PP_IIF(BOOST_PP_CAT(UNCURSED_PP_LE16_, n), UNCURSED_PP_A_SMALL1, UNCURSED_PP_A_BIG1)
#define UNCURSED_PP_A_BIG1(seq) BOOST_PP_SEQ_FOR_EACH(UNCURSED_PP_COLLAPSE_TRAPS_H1, ~, seq)
#define A(xs) UNCURSED_PP_A_PICK1(BOOST_PP_SEQ_SIZE(xs))(xs)

/* uncursed-pp source:
 * @macro B($ys: seq<token>)
 * @for $y in $ys
 * f({{$y}});
 * @end
 * @endmacro
 */
#define UNCURSED_PP_B_SMALL1(seq) BOOST_PP_CAT(UNCURSED_PP_COLLAPSE_TRAPS_HC3_, BOOST_PP_SEQ_SIZE(seq)) seq
#define UNCURSED_PP_B_PICK1(n) BOOST_PP_IIF(BOOST_PP_CAT(UNCURSED_PP_LE16_, n), UNCURSED_PP_B_SMALL1, UNCURSED_PP_B_BIG1)
#define UNCURSED_PP_B_BIG1(seq) BOOST_PP_SEQ_FOR_EACH(UNCURSED_PP_COLLAPSE_TRAPS_H1, ~, seq)
#define B(ys) UNCURSED_PP_B_PICK1(BOOST_PP_SEQ_SIZE(ys))(ys)

/* uncursed-pp source:
 * @macro A_CH1($zs: seq<token>)
 * @for $z in $zs
 * g({{$z}});
 * @end
 * @endmacro
 */
#define UNCURSED_PP_A_CH1_EACH1(r, d, e) g(e);
#define UNCURSED_PP_A_CH1_CH1_1(e) g(e);
#define UNCURSED_PP_A_CH1_CH1_2(e) g(e); UNCURSED_PP_A_CH1_CH1_1
#define UNCURSED_PP_A_CH1_CH1_3(e) g(e); UNCURSED_PP_A_CH1_CH1_2
#define UNCURSED_PP_A_CH1_CH1_4(e) g(e); UNCURSED_PP_A_CH1_CH1_3
#define UNCURSED_PP_A_CH1_CH1_5(e) g(e); UNCURSED_PP_A_CH1_CH1_4
#define UNCURSED_PP_A_CH1_CH1_6(e) g(e); UNCURSED_PP_A_CH1_CH1_5
#define UNCURSED_PP_A_CH1_CH1_7(e) g(e); UNCURSED_PP_A_CH1_CH1_6
#define UNCURSED_PP_A_CH1_CH1_8(e) g(e); UNCURSED_PP_A_CH1_CH1_7
#define UNCURSED_PP_A_CH1_CH1_9(e) g(e); UNCURSED_PP_A_CH1_CH1_8
#define UNCURSED_PP_A_CH1_CH1_10(e) g(e); UNCURSED_PP_A_CH1_CH1_9
#define UNCURSED_PP_A_CH1_CH1_11(e) g(e); UNCURSED_PP_A_CH1_CH1_10
#define UNCURSED_PP_A_CH1_CH1_12(e) g(e); UNCURSED_PP_A_CH1_CH1_11
#define UNCURSED_PP_A_CH1_CH1_13(e) g(e); UNCURSED_PP_A_CH1_CH1_12
#define UNCURSED_PP_A_CH1_CH1_14(e) g(e); UNCURSED_PP_A_CH1_CH1_13
#define UNCURSED_PP_A_CH1_CH1_15(e) g(e); UNCURSED_PP_A_CH1_CH1_14
#define UNCURSED_PP_A_CH1_CH1_16(e) g(e); UNCURSED_PP_A_CH1_CH1_15
#define UNCURSED_PP_A_CH1_SMALL1(seq) BOOST_PP_CAT(UNCURSED_PP_A_CH1_CH1_, BOOST_PP_SEQ_SIZE(seq)) seq
#define UNCURSED_PP_A_CH1_PICK1(n) BOOST_PP_IIF(BOOST_PP_CAT(UNCURSED_PP_LE16_, n), UNCURSED_PP_A_CH1_SMALL1, UNCURSED_PP_A_CH1_BIG1)
#define UNCURSED_PP_A_CH1_BIG1(seq) BOOST_PP_SEQ_FOR_EACH(UNCURSED_PP_A_CH1_EACH1, ~, seq)
#define A_CH1(zs) UNCURSED_PP_A_CH1_PICK1(BOOST_PP_SEQ_SIZE(zs))(zs)

/* uncursed-pp source:
 * @macro IA($r: token, $d: token, $e: token, $fs: seq<token>)
 * @for $f in $fs
 * @if $f == 1
 * use({{$r}});
 * @else
 * alt({{$d}}, {{$e}});
 * @end
 * @end
 * @endmacro
 */
#define UNCURSED_PP_IA_THEN1(r, d, e) use(r);
#define UNCURSED_PP_COLLAPSE_TRAPS_H2(r, d, e) alt(d, e);
#define UNCURSED_PP_IA_EACH1(r, d, e) BOOST_PP_IIF(BOOST_PP_EQUAL(e, 1), UNCURSED_PP_IA_THEN1, UNCURSED_PP_COLLAPSE_TRAPS_H2)(BOOST_PP_TUPLE_ELEM(0, d), BOOST_PP_TUPLE_ELEM(1, d), BOOST_PP_TUPLE_ELEM(2, d))
#define IA(r, d, e, fs) BOOST_PP_SEQ_FOR_EACH(UNCURSED_PP_IA_EACH1, (r, d, e), fs)

/* uncursed-pp source:
 * @macro IB($r: token, $d: token, $e: token, $fs: seq<token>)
 * @for $f in $fs
 * @if $f == 1
 * use2({{$r}});
 * @else
 * alt({{$d}}, {{$e}});
 * @end
 * @end
 * @endmacro
 */
#define UNCURSED_PP_IB_THEN1(r, d, e) use2(r);
#define UNCURSED_PP_IB_EACH1(r, d, e) BOOST_PP_IIF(BOOST_PP_EQUAL(e, 1), UNCURSED_PP_IB_THEN1, UNCURSED_PP_COLLAPSE_TRAPS_H2)(BOOST_PP_TUPLE_ELEM(0, d), BOOST_PP_TUPLE_ELEM(1, d), BOOST_PP_TUPLE_ELEM(2, d))
#define IB(r, d, e, fs) BOOST_PP_SEQ_FOR_EACH(UNCURSED_PP_IB_EACH1, (r, d, e), fs)

/* uncursed-pp source:
 * @macro OA($xs: seq<token>)
 * @for $x in $xs
 * call {{$x}} (
 * @end
 * @endmacro
 */
#define UNCURSED_PP_OA_EACH1(r, d, e) call e (
#define UNCURSED_PP_OA_CH1_1(e) call e (
#define UNCURSED_PP_OA_CH1_2(e) call e ( UNCURSED_PP_OA_CH1_1
#define UNCURSED_PP_OA_CH1_3(e) call e ( UNCURSED_PP_OA_CH1_2
#define UNCURSED_PP_OA_CH1_4(e) call e ( UNCURSED_PP_OA_CH1_3
#define UNCURSED_PP_OA_CH1_5(e) call e ( UNCURSED_PP_OA_CH1_4
#define UNCURSED_PP_OA_CH1_6(e) call e ( UNCURSED_PP_OA_CH1_5
#define UNCURSED_PP_OA_CH1_7(e) call e ( UNCURSED_PP_OA_CH1_6
#define UNCURSED_PP_OA_CH1_8(e) call e ( UNCURSED_PP_OA_CH1_7
#define UNCURSED_PP_OA_CH1_9(e) call e ( UNCURSED_PP_OA_CH1_8
#define UNCURSED_PP_OA_CH1_10(e) call e ( UNCURSED_PP_OA_CH1_9
#define UNCURSED_PP_OA_CH1_11(e) call e ( UNCURSED_PP_OA_CH1_10
#define UNCURSED_PP_OA_CH1_12(e) call e ( UNCURSED_PP_OA_CH1_11
#define UNCURSED_PP_OA_CH1_13(e) call e ( UNCURSED_PP_OA_CH1_12
#define UNCURSED_PP_OA_CH1_14(e) call e ( UNCURSED_PP_OA_CH1_13
#define UNCURSED_PP_OA_CH1_15(e) call e ( UNCURSED_PP_OA_CH1_14
#define UNCURSED_PP_OA_CH1_16(e) call e ( UNCURSED_PP_OA_CH1_15
#define UNCURSED_PP_OA_SMALL1(seq) BOOST_PP_CAT(UNCURSED_PP_OA_CH1_, BOOST_PP_SEQ_SIZE(seq)) seq
#define UNCURSED_PP_OA_PICK1(n) BOOST_PP_IIF(BOOST_PP_CAT(UNCURSED_PP_LE16_, n), UNCURSED_PP_OA_SMALL1, UNCURSED_PP_OA_BIG1)
#define UNCURSED_PP_OA_BIG1(seq) BOOST_PP_SEQ_FOR_EACH(UNCURSED_PP_OA_EACH1, ~, seq)
#define OA(xs) UNCURSED_PP_OA_PICK1(BOOST_PP_SEQ_SIZE(xs))(xs)

/* uncursed-pp source:
 * @macro OB($ys: seq<token>)
 * @for $y in $ys
 * call {{$y}} )
 * @end
 * @endmacro
 */
#define UNCURSED_PP_OB_EACH1(r, d, e) call e )
#define UNCURSED_PP_OB_CH1_1(e) call e )
#define UNCURSED_PP_OB_CH1_2(e) call e ) UNCURSED_PP_OB_CH1_1
#define UNCURSED_PP_OB_CH1_3(e) call e ) UNCURSED_PP_OB_CH1_2
#define UNCURSED_PP_OB_CH1_4(e) call e ) UNCURSED_PP_OB_CH1_3
#define UNCURSED_PP_OB_CH1_5(e) call e ) UNCURSED_PP_OB_CH1_4
#define UNCURSED_PP_OB_CH1_6(e) call e ) UNCURSED_PP_OB_CH1_5
#define UNCURSED_PP_OB_CH1_7(e) call e ) UNCURSED_PP_OB_CH1_6
#define UNCURSED_PP_OB_CH1_8(e) call e ) UNCURSED_PP_OB_CH1_7
#define UNCURSED_PP_OB_CH1_9(e) call e ) UNCURSED_PP_OB_CH1_8
#define UNCURSED_PP_OB_CH1_10(e) call e ) UNCURSED_PP_OB_CH1_9
#define UNCURSED_PP_OB_CH1_11(e) call e ) UNCURSED_PP_OB_CH1_10
#define UNCURSED_PP_OB_CH1_12(e) call e ) UNCURSED_PP_OB_CH1_11
#define UNCURSED_PP_OB_CH1_13(e) call e ) UNCURSED_PP_OB_CH1_12
#define UNCURSED_PP_OB_CH1_14(e) call e ) UNCURSED_PP_OB_CH1_13
#define UNCURSED_PP_OB_CH1_15(e) call e ) UNCURSED_PP_OB_CH1_14
#define UNCURSED_PP_OB_CH1_16(e) call e ) UNCURSED_PP_OB_CH1_15
#define UNCURSED_PP_OB_SMALL1(seq) BOOST_PP_CAT(UNCURSED_PP_OB_CH1_, BOOST_PP_SEQ_SIZE(seq)) seq
#define UNCURSED_PP_OB_PICK1(n) BOOST_PP_IIF(BOOST_PP_CAT(UNCURSED_PP_LE16_, n), UNCURSED_PP_OB_SMALL1, UNCURSED_PP_OB_BIG1)
#define UNCURSED_PP_OB_BIG1(seq) BOOST_PP_SEQ_FOR_EACH(UNCURSED_PP_OB_EACH1, ~, seq)
#define OB(ys) UNCURSED_PP_OB_PICK1(BOOST_PP_SEQ_SIZE(ys))(ys)

/* # ── invocation specs (verified through cc -E by test_e2e_specs) ──
 * #?  A((a)(b))
 * #=>     f(a); f(b);
 */

/* #?  B((u)(v))
 * #=>     f(u); f(v);
 */

/* # trap 1: the lookalike macro still expands after A+B's family merge
 * #?  A_CH1((z)(w))
 * #=>     g(z); g(w);
 */

/* # trap 2: branch helpers with user-named r/d/e params stay intact
 * #?  IA(R, D, E, (1)(2))
 * #=>     use(R); alt(D, E);
 */

/* #?  IB(R, D, E, (1))
 * #=>     use2(R);
 */

/* # trap 3: lone-paren bodies expand verbatim (never merged through d)
 * #?  OA((p))
 * #=>     call p (
 */

/* #?  OB((q))
 * #=>     call q )
 */
