/* Generated by uncursed-pp from dispatch.uncursed — do not edit. */
#pragma once

#include <boost/preprocessor/cat.hpp>
#include <boost/preprocessor/comparison/equal.hpp>
#include <boost/preprocessor/control/iif.hpp>
#include <boost/preprocessor/seq/elem.hpp>
#include <boost/preprocessor/seq/enum.hpp>
#include <boost/preprocessor/seq/size.hpp>

/* uncursed-pp source:
 * # Composition: @if len over a seq, inline @join inside a branch,
 * # indexing in the other branch, concat in both.
 * @macro DISPATCH(fn, args: seq<token>)
 * @if len(args) == 1
 * {{concat(fn, _1)}}({{args[0]}})
 * @else
 * {{concat(fn, _n)}}({{len(args)}}, @join args as a with ", ": {{a}}@end)
 * @end
 * @endmacro
 */
#define UNCURSED_PP_DISPATCH_THEN1(fn, args) BOOST_PP_CAT(fn, _1)(BOOST_PP_SEQ_ELEM(0, args))
#define UNCURSED_PP_DISPATCH_ELSE1(fn, args) BOOST_PP_CAT(fn, _n)(BOOST_PP_SEQ_SIZE(args), BOOST_PP_SEQ_ENUM(args))
#define DISPATCH(fn, args) BOOST_PP_IIF(BOOST_PP_EQUAL(BOOST_PP_SEQ_SIZE(args), 1), UNCURSED_PP_DISPATCH_THEN1, UNCURSED_PP_DISPATCH_ELSE1)(fn, args)

/* # ── invocation specs (verified through cc -E by the spec harness) ──
 * #?  DISPATCH(handler, (x))
 * #=>     handler_1(x)
 */

/* #?  DISPATCH(handler, (x)(y)(z))
 * #=>     handler_n(3, x, y, z)
 */
