/* Generated by cursedpp from dispatch.cursed — do not edit. */
#pragma once

#include <boost/preprocessor/cat.hpp>
#include <boost/preprocessor/comparison/equal.hpp>
#include <boost/preprocessor/control/iif.hpp>
#include <boost/preprocessor/seq/elem.hpp>
#include <boost/preprocessor/seq/enum.hpp>
#include <boost/preprocessor/seq/size.hpp>

/* cursedpp source:
 * # Composition: @if len over a seq, inline @join inside a branch,
 * # indexing in the other branch, concat in both.
 * macro DISPATCH(fn, args: seq<token>)
 * @if len(args) == 1
 * {{concat(fn, _1)}}({{args[0]}})
 * @else
 * {{concat(fn, _n)}}({{len(args)}}, @join args as a with ", ": {{a}}@end)
 * @end
 * end
 */
#define CURSEDPP_DISPATCH_THEN1(fn, args) BOOST_PP_CAT(fn, _1)(BOOST_PP_SEQ_ELEM(0, args))
#define CURSEDPP_DISPATCH_ELSE1(fn, args) BOOST_PP_CAT(fn, _n)(BOOST_PP_SEQ_SIZE(args), BOOST_PP_SEQ_ENUM(args))
#define DISPATCH(fn, args) BOOST_PP_IIF(BOOST_PP_EQUAL(BOOST_PP_SEQ_SIZE(args), 1), CURSEDPP_DISPATCH_THEN1, CURSEDPP_DISPATCH_ELSE1)(fn, args)
