/* Generated by cursedpp from enum_system.cursed — do not edit. */
#pragma once

#include <boost/preprocessor/cat.hpp>
#include <boost/preprocessor/seq/for_each.hpp>
#include <boost/preprocessor/seq/size.hpp>
#include <boost/preprocessor/stringize.hpp>
#include <boost/preprocessor/tuple/elem.hpp>
#include <boost/preprocessor/variadic/to_seq.hpp>

#define CURSEDPP_DEFINE_ENUM_EACH1(r, d, e) BOOST_PP_CAT(d, BOOST_PP_CAT(_, BOOST_PP_TUPLE_ELEM(0, e))) = BOOST_PP_TUPLE_ELEM(1, e),
#define CURSEDPP_DEFINE_ENUM_EACH2(r, d, e) case BOOST_PP_TUPLE_ELEM(1, e): return BOOST_PP_STRINGIZE(BOOST_PP_CAT(d, BOOST_PP_CAT(_, BOOST_PP_TUPLE_ELEM(0, e))));
#define DEFINE_ENUM(ename, ...) \
    typedef enum { \
    BOOST_PP_SEQ_FOR_EACH(CURSEDPP_DEFINE_ENUM_EACH1, ename, BOOST_PP_VARIADIC_TO_SEQ(__VA_ARGS__)) \
    } ename; \
    static const char *BOOST_PP_CAT(ename, _to_string)(int v) { \
    switch (v) { \
    BOOST_PP_SEQ_FOR_EACH(CURSEDPP_DEFINE_ENUM_EACH2, ename, BOOST_PP_VARIADIC_TO_SEQ(__VA_ARGS__)) \
    } \
    return "?"; \
    } \
    enum { BOOST_PP_CAT(ename, _count) = BOOST_PP_SEQ_SIZE(BOOST_PP_VARIADIC_TO_SEQ(__VA_ARGS__)) };
