/* Generated by uncursed-pp from lookup_table.uncursed — do not edit. */
#pragma once

#include <boost/preprocessor/cat.hpp>
#include <boost/preprocessor/punctuation/comma_if.hpp>
#include <boost/preprocessor/seq/for_each_i.hpp>
#include <boost/preprocessor/seq/size.hpp>
#include <boost/preprocessor/stringize.hpp>

/* uncursed-pp source:
 * # Composition: @let of len() and @let of an inline @join, each reused.
 * macro LOOKUP_TABLE(tname, keys: seq<token>)
 * @let n := len(keys)
 * @let strings := @join keys as k with ", ": {{stringize(k)}}@end
 * static const char *{{tname}}[{{n}}] = { {{strings}} };
 * enum { {{concat(tname, _len)}} = {{n}} };
 * end
 */
#define UNCURSED_PP_LOOKUP_TABLE_EACH1(r, d, i, e) BOOST_PP_COMMA_IF(i) BOOST_PP_STRINGIZE(e)
#define LOOKUP_TABLE(tname, keys) \
    static const char *tname[BOOST_PP_SEQ_SIZE(keys)] = { BOOST_PP_SEQ_FOR_EACH_I(UNCURSED_PP_LOOKUP_TABLE_EACH1, ~, keys) }; \
    enum { BOOST_PP_CAT(tname, _len) = BOOST_PP_SEQ_SIZE(keys) };
