/* Generated by uncursed-pp from lookup_table.uncursed — do not edit. */
#pragma once

#include <boost/preprocessor/cat.hpp>
#include <boost/preprocessor/control/iif.hpp>
#include <boost/preprocessor/punctuation/comma_if.hpp>
#include <boost/preprocessor/seq/for_each_i.hpp>
#include <boost/preprocessor/seq/size.hpp>
#include <boost/preprocessor/stringize.hpp>
#include "uncursed_pp_runtime.h"

/* uncursed-pp source:
 * # Composition: @let of len() and @let of an inline @join, each reused.
 * @macro LOOKUP_TABLE(tname, keys: seq<token>)
 * @let n := len(keys)
 * @let strings := @join keys as k with ", ": {{stringize(k)}}@end
 * static const char *{{tname}}[{{n}}] = { {{strings}} };
 * enum { {{concat(tname, _len)}} = {{n}} };
 * @endmacro
 */
#define UNCURSED_PP_LOOKUP_TABLE_EACH1(r, d, i, e) BOOST_PP_COMMA_IF(i) BOOST_PP_STRINGIZE(e)
#define UNCURSED_PP_LOOKUP_TABLE_CH1_1(e) BOOST_PP_STRINGIZE(e)
#define UNCURSED_PP_LOOKUP_TABLE_CH1_2(e) BOOST_PP_STRINGIZE(e), UNCURSED_PP_LOOKUP_TABLE_CH1_1
#define UNCURSED_PP_LOOKUP_TABLE_CH1_3(e) BOOST_PP_STRINGIZE(e), UNCURSED_PP_LOOKUP_TABLE_CH1_2
#define UNCURSED_PP_LOOKUP_TABLE_CH1_4(e) BOOST_PP_STRINGIZE(e), UNCURSED_PP_LOOKUP_TABLE_CH1_3
#define UNCURSED_PP_LOOKUP_TABLE_CH1_5(e) BOOST_PP_STRINGIZE(e), UNCURSED_PP_LOOKUP_TABLE_CH1_4
#define UNCURSED_PP_LOOKUP_TABLE_CH1_6(e) BOOST_PP_STRINGIZE(e), UNCURSED_PP_LOOKUP_TABLE_CH1_5
#define UNCURSED_PP_LOOKUP_TABLE_CH1_7(e) BOOST_PP_STRINGIZE(e), UNCURSED_PP_LOOKUP_TABLE_CH1_6
#define UNCURSED_PP_LOOKUP_TABLE_CH1_8(e) BOOST_PP_STRINGIZE(e), UNCURSED_PP_LOOKUP_TABLE_CH1_7
#define UNCURSED_PP_LOOKUP_TABLE_CH1_9(e) BOOST_PP_STRINGIZE(e), UNCURSED_PP_LOOKUP_TABLE_CH1_8
#define UNCURSED_PP_LOOKUP_TABLE_CH1_10(e) BOOST_PP_STRINGIZE(e), UNCURSED_PP_LOOKUP_TABLE_CH1_9
#define UNCURSED_PP_LOOKUP_TABLE_CH1_11(e) BOOST_PP_STRINGIZE(e), UNCURSED_PP_LOOKUP_TABLE_CH1_10
#define UNCURSED_PP_LOOKUP_TABLE_CH1_12(e) BOOST_PP_STRINGIZE(e), UNCURSED_PP_LOOKUP_TABLE_CH1_11
#define UNCURSED_PP_LOOKUP_TABLE_CH1_13(e) BOOST_PP_STRINGIZE(e), UNCURSED_PP_LOOKUP_TABLE_CH1_12
#define UNCURSED_PP_LOOKUP_TABLE_CH1_14(e) BOOST_PP_STRINGIZE(e), UNCURSED_PP_LOOKUP_TABLE_CH1_13
#define UNCURSED_PP_LOOKUP_TABLE_CH1_15(e) BOOST_PP_STRINGIZE(e), UNCURSED_PP_LOOKUP_TABLE_CH1_14
#define UNCURSED_PP_LOOKUP_TABLE_CH1_16(e) BOOST_PP_STRINGIZE(e), UNCURSED_PP_LOOKUP_TABLE_CH1_15
#define UNCURSED_PP_LOOKUP_TABLE_SMALL1(seq) BOOST_PP_CAT(UNCURSED_PP_LOOKUP_TABLE_CH1_, BOOST_PP_SEQ_SIZE(seq)) seq
#define UNCURSED_PP_LOOKUP_TABLE_PICK1(n) BOOST_PP_IIF(BOOST_PP_CAT(UNCURSED_PP_LE16_, n), UNCURSED_PP_LOOKUP_TABLE_SMALL1, UNCURSED_PP_LOOKUP_TABLE_BIG1)
#define UNCURSED_PP_LOOKUP_TABLE_BIG1(seq) BOOST_PP_SEQ_FOR_EACH_I(UNCURSED_PP_LOOKUP_TABLE_EACH1, ~, seq)
#define LOOKUP_TABLE(tname, keys) \
    static const char *tname[BOOST_PP_SEQ_SIZE(keys)] = { UNCURSED_PP_LOOKUP_TABLE_PICK1(BOOST_PP_SEQ_SIZE(keys))(keys) }; \
    enum { BOOST_PP_CAT(tname, _len) = BOOST_PP_SEQ_SIZE(keys) };
