/* Generated by cursedpp from pipeline.cursed — do not edit. */
#pragma once

#include <boost/preprocessor/cat.hpp>
#include <boost/preprocessor/control/iif.hpp>
#include <boost/preprocessor/facilities/overload.hpp>
#include <boost/preprocessor/punctuation/is_begin_parens.hpp>
#include <boost/preprocessor/punctuation/remove_parens.hpp>
#include <boost/preprocessor/seq/fold_left.hpp>
#include <boost/preprocessor/seq/for_each.hpp>
#include <boost/preprocessor/tuple/elem.hpp>
#include <boost/preprocessor/variadic/to_seq.hpp>
#include "cursedpp_runtime.h"

#define CURSEDPP_GET_A_BODY1(a, b) a
#define CURSEDPP_GET_A_BODY1_D(...) CURSEDPP_GET_A_BODY1(__VA_ARGS__)
#define GET_A(p) CURSEDPP_GET_A_BODY1_D(CURSEDPP_KW_SPREAD p)

#define USE(q) first = GET_A(q);

#define CURSEDPP_EACH_FIELD_AP1(t, n) t n;
#define CURSEDPP_EACH_FIELD_EACH1(r, d, e) CURSEDPP_EACH_FIELD_AP1 e
#define EACH_FIELD(fields) BOOST_PP_SEQ_FOR_EACH(CURSEDPP_EACH_FIELD_EACH1, ~, fields)

#define CURSEDPP_OBJ_THEN1(FIELDS) EACH_FIELD(FIELDS)
#define CURSEDPP_OBJ_ELSE1(FIELDS)
#define CURSEDPP_OBJ_SET_FIELDS(...) 0, (__VA_ARGS__)
#define CURSEDPP_OBJ_STEP(s, state, e) CURSEDPP_OBJ_STEP_D(state, BOOST_PP_CAT(CURSEDPP_OBJ_SET_, e))
#define CURSEDPP_OBJ_STEP_D(state, ...) CURSEDPP_OBJ_STEP_I(state, __VA_ARGS__)
#define CURSEDPP_OBJ_STEP_I(state, i, v) BOOST_PP_CAT(CURSEDPP_OBJ_PUT_, i)(v, state)
#define CURSEDPP_OBJ_PUT_0(v, state) CURSEDPP_OBJ_PUT_0_D(v, CURSEDPP_KW_SPREAD state)
#define CURSEDPP_OBJ_PUT_0_D(...) CURSEDPP_OBJ_PUT_0_I(__VA_ARGS__)
#define CURSEDPP_OBJ_PUT_0_I(v, p0) (v)
#define CURSEDPP_OBJ_BODY(name, FIELDS) struct name { BOOST_PP_IIF(BOOST_PP_IS_BEGIN_PARENS(BOOST_PP_REMOVE_PARENS(FIELDS)), CURSEDPP_OBJ_THEN1, CURSEDPP_OBJ_ELSE1)(BOOST_PP_REMOVE_PARENS(FIELDS)) };
#define CURSEDPP_OBJ_UNPACK(name, state) CURSEDPP_OBJ_BODY(name, BOOST_PP_TUPLE_ELEM(0, state))
#define CURSEDPP_OBJ_KW(name, ...) CURSEDPP_OBJ_UNPACK(name, BOOST_PP_SEQ_FOLD_LEFT(CURSEDPP_OBJ_STEP, (()), BOOST_PP_VARIADIC_TO_SEQ(__VA_ARGS__)))
#define CURSEDPP_OBJ_1(name) CURSEDPP_OBJ_BODY(name, ())
#define CURSEDPP_OBJ_2 CURSEDPP_OBJ_KW
#define OBJ(...) BOOST_PP_OVERLOAD(CURSEDPP_OBJ_, __VA_ARGS__)(__VA_ARGS__)
