/* Generated by uncursed-pp from pipeline.uncursed — do not edit. */
#pragma once

#include <boost/preprocessor/cat.hpp>
#include <boost/preprocessor/control/iif.hpp>
#include <boost/preprocessor/punctuation/is_begin_parens.hpp>
#include <boost/preprocessor/seq/for_each.hpp>
#include <boost/preprocessor/seq/size.hpp>
#include <boost/preprocessor/tuple/elem.hpp>
#include "uncursed_pp_runtime.h"

/* uncursed-pp source:
 * # Values travel between generated macros: a whole tuple forwarded as one
 * # argument, and a whole seq carried inside a 'named variadic' value and
 * # handed to a looping macro. is_paren() guards the empty default.
 * macro GET_A(p: tuple<a, b>)
 * {{p.a}}
 * end
 */
#define UNCURSED_PP_GET_A_BODY1(a, b) a
#define UNCURSED_PP_GET_A_BODY1_D(...) UNCURSED_PP_GET_A_BODY1(__VA_ARGS__)
#define GET_A(p) UNCURSED_PP_GET_A_BODY1_D(UNCURSED_PP_KW_SPREAD p)

/* uncursed-pp source:
 * macro USE(q: tuple<a, b>)
 * first = GET_A({{q}});
 * end
 */
#define USE(q) first = GET_A(q);

/* uncursed-pp source:
 * macro EACH_FIELD(fields: seq<tuple<t, n>>)
 * @for (t, n) in fields
 * {{t}} {{n}};
 * @end
 * end
 */
#define UNCURSED_PP_EACH_FIELD_AP1(t, n) t n;
#define UNCURSED_PP_EACH_FIELD_EACH1(r, d, e) UNCURSED_PP_EACH_FIELD_AP1 e
#define UNCURSED_PP_EACH_FIELD_CH1_1(e) UNCURSED_PP_EACH_FIELD_AP1 e
#define UNCURSED_PP_EACH_FIELD_CH1_2(e) UNCURSED_PP_EACH_FIELD_AP1 e UNCURSED_PP_EACH_FIELD_CH1_1
#define UNCURSED_PP_EACH_FIELD_CH1_3(e) UNCURSED_PP_EACH_FIELD_AP1 e UNCURSED_PP_EACH_FIELD_CH1_2
#define UNCURSED_PP_EACH_FIELD_CH1_4(e) UNCURSED_PP_EACH_FIELD_AP1 e UNCURSED_PP_EACH_FIELD_CH1_3
#define UNCURSED_PP_EACH_FIELD_CH1_5(e) UNCURSED_PP_EACH_FIELD_AP1 e UNCURSED_PP_EACH_FIELD_CH1_4
#define UNCURSED_PP_EACH_FIELD_CH1_6(e) UNCURSED_PP_EACH_FIELD_AP1 e UNCURSED_PP_EACH_FIELD_CH1_5
#define UNCURSED_PP_EACH_FIELD_CH1_7(e) UNCURSED_PP_EACH_FIELD_AP1 e UNCURSED_PP_EACH_FIELD_CH1_6
#define UNCURSED_PP_EACH_FIELD_CH1_8(e) UNCURSED_PP_EACH_FIELD_AP1 e UNCURSED_PP_EACH_FIELD_CH1_7
#define UNCURSED_PP_EACH_FIELD_CH1_9(e) UNCURSED_PP_EACH_FIELD_AP1 e UNCURSED_PP_EACH_FIELD_CH1_8
#define UNCURSED_PP_EACH_FIELD_CH1_10(e) UNCURSED_PP_EACH_FIELD_AP1 e UNCURSED_PP_EACH_FIELD_CH1_9
#define UNCURSED_PP_EACH_FIELD_CH1_11(e) UNCURSED_PP_EACH_FIELD_AP1 e UNCURSED_PP_EACH_FIELD_CH1_10
#define UNCURSED_PP_EACH_FIELD_CH1_12(e) UNCURSED_PP_EACH_FIELD_AP1 e UNCURSED_PP_EACH_FIELD_CH1_11
#define UNCURSED_PP_EACH_FIELD_CH1_13(e) UNCURSED_PP_EACH_FIELD_AP1 e UNCURSED_PP_EACH_FIELD_CH1_12
#define UNCURSED_PP_EACH_FIELD_CH1_14(e) UNCURSED_PP_EACH_FIELD_AP1 e UNCURSED_PP_EACH_FIELD_CH1_13
#define UNCURSED_PP_EACH_FIELD_CH1_15(e) UNCURSED_PP_EACH_FIELD_AP1 e UNCURSED_PP_EACH_FIELD_CH1_14
#define UNCURSED_PP_EACH_FIELD_CH1_16(e) UNCURSED_PP_EACH_FIELD_AP1 e UNCURSED_PP_EACH_FIELD_CH1_15
#define UNCURSED_PP_EACH_FIELD_SMALL1(seq) BOOST_PP_CAT(UNCURSED_PP_EACH_FIELD_CH1_, BOOST_PP_SEQ_SIZE(seq)) seq
#define UNCURSED_PP_EACH_FIELD_PICK1(n) BOOST_PP_IIF(BOOST_PP_CAT(UNCURSED_PP_LE16_, n), UNCURSED_PP_EACH_FIELD_SMALL1, UNCURSED_PP_EACH_FIELD_BIG1)
#define UNCURSED_PP_EACH_FIELD_BIG1(seq) BOOST_PP_SEQ_FOR_EACH(UNCURSED_PP_EACH_FIELD_EACH1, ~, seq)
#define EACH_FIELD(fields) UNCURSED_PP_EACH_FIELD_PICK1(BOOST_PP_SEQ_SIZE(fields))(fields)

/* uncursed-pp source:
 * macro OBJ(name, named variadic FIELDS = )
 * struct {{name}} { @if is_paren(FIELDS) EACH_FIELD({{FIELDS}}) @end };
 * end
 */
#define UNCURSED_PP_OBJ_THEN1(FIELDS) EACH_FIELD(FIELDS)
#define UNCURSED_PP_OBJ_ELSE1(FIELDS)
#define UNCURSED_PP_OBJ_SET_FIELDS(...) 0, (__VA_ARGS__)
#define UNCURSED_PP_OBJ_STEP1(e, ...) UNCURSED_PP_OBJ_STEP_D(BOOST_PP_CAT(UNCURSED_PP_OBJ_SET_, e), __VA_ARGS__)
#define UNCURSED_PP_OBJ_STEP_D(...) UNCURSED_PP_OBJ_STEP_I(__VA_ARGS__)
#define UNCURSED_PP_OBJ_STEP_I(i, v, ...) UNCURSED_PP_OBJ_PUT_ ## i(v, __VA_ARGS__)
#define UNCURSED_PP_OBJ_PUT_0(v, p0) v
#define UNCURSED_PP_OBJ_BODY(name, FIELDS) struct name { BOOST_PP_IIF(BOOST_PP_IS_BEGIN_PARENS(UNCURSED_PP_KW_SPREAD FIELDS), UNCURSED_PP_OBJ_THEN1, UNCURSED_PP_OBJ_ELSE1)(UNCURSED_PP_KW_SPREAD FIELDS) };
#define UNCURSED_PP_OBJ_BODY_D(...) UNCURSED_PP_OBJ_BODY(__VA_ARGS__)
#define UNCURSED_PP_OBJ_1(name) UNCURSED_PP_OBJ_BODY(name, ())
#define UNCURSED_PP_OBJ_2(name, e1) UNCURSED_PP_OBJ_BODY_D(name, UNCURSED_PP_OBJ_STEP1(e1, ()))
#define UNCURSED_PP_OBJ_SIZE(...) UNCURSED_PP_OBJ_SIZE_I(__VA_ARGS__, 2, 1,)
#define UNCURSED_PP_OBJ_SIZE_I(e0, e1, size, ...) size
#define UNCURSED_PP_OBJ_DISPATCH(n) UNCURSED_PP_OBJ_DISPATCH_I(n)
#define UNCURSED_PP_OBJ_DISPATCH_I(n) UNCURSED_PP_OBJ_ ## n
#define OBJ(...) UNCURSED_PP_OBJ_DISPATCH(UNCURSED_PP_OBJ_SIZE(__VA_ARGS__))(__VA_ARGS__)
