/* Generated by uncursed-pp from hybrid.uncursed — do not edit. */
#pragma once

#include <boost/preprocessor/cat.hpp>
#include <boost/preprocessor/control/iif.hpp>
#include <boost/preprocessor/facilities/is_empty_variadic.hpp>
#include <boost/preprocessor/punctuation/comma_if.hpp>
#include <boost/preprocessor/repetition/repeat.hpp>
#include <boost/preprocessor/seq/elem.hpp>
#include <boost/preprocessor/seq/enum.hpp>
#include <boost/preprocessor/seq/for_each.hpp>
#include <boost/preprocessor/seq/size.hpp>
#include <boost/preprocessor/tuple/elem.hpp>
#include <boost/preprocessor/tuple/size.hpp>
#include <boost/preprocessor/tuple/to_seq.hpp>
#include "uncursed_pp_runtime.h"

/* # Hybrid tuples: `tuple<n1, .., nk, T...>` — fixed NAMED head fields,
 * # then an unbounded typed tail. Named access reads the head; iteration,
 * # len(), is_empty() and [i] are all TAIL-scoped so they agree with each
 * # other. Call site (x, int, F1, F2); (x, int) is an empty tail.
 */

/* uncursed-pp source:
 * @macro DECL_FIELD($f: tuple<$fname, $ftype, token...>)
 * @if is_empty($f)
 *   {{$f.$ftype}} {{$f.$fname}};
 * @else
 *   {{$f.$ftype}} {{$f.$fname}} __attribute__((@join $f as $a with ", ": {{$a}}@end));
 * @end
 * @endmacro
 */
#define UNCURSED_PP_DECL_FIELD_THEN1(f) BOOST_PP_TUPLE_ELEM(1, f) BOOST_PP_TUPLE_ELEM(0, f);
#define UNCURSED_PP_DECL_FIELD_TL2(t) UNCURSED_PP_DECL_FIELD_TL2_I t
#define UNCURSED_PP_DECL_FIELD_TL2_I(f0, f1, ...) (__VA_ARGS__)
#define UNCURSED_PP_DECL_FIELD_LOOP1(f) BOOST_PP_SEQ_ENUM(BOOST_PP_TUPLE_TO_SEQ(UNCURSED_PP_DECL_FIELD_TL2(f)))
#define UNCURSED_PP_HYBRID_H1(f)
#define UNCURSED_PP_HYBRID_H2(x) BOOST_PP_IS_EMPTY x
#define UNCURSED_PP_DECL_FIELD_ELSE1(f) BOOST_PP_TUPLE_ELEM(1, f) BOOST_PP_TUPLE_ELEM(0, f) __attribute__((BOOST_PP_IIF(UNCURSED_PP_HYBRID_H2(UNCURSED_PP_DECL_FIELD_TL2(f)), UNCURSED_PP_HYBRID_H1, UNCURSED_PP_DECL_FIELD_LOOP1)(f)));
#define DECL_FIELD(f) BOOST_PP_IIF(UNCURSED_PP_HYBRID_H2(UNCURSED_PP_DECL_FIELD_TL2(f)), UNCURSED_PP_DECL_FIELD_THEN1, UNCURSED_PP_DECL_FIELD_ELSE1)(f)

/* #?  DECL_FIELD((x, int, packed, unused))
 * #=>     int x __attribute__((packed, unused));
 */

/* # empty tail: just the head fields
 * #?  DECL_FIELD((y, float))
 * #=>     float y;
 */

/* uncursed-pp source:
 * # len() and [i] are tail-scoped: the head does not count
 * @macro TAIL_INFO($f: tuple<$n, token...>)
 * {{$f.$n}}: {{len($f)}} flags, first {{$f[0]}}
 * @endmacro
 */
#define UNCURSED_PP_HYBRID_H4(t) UNCURSED_PP_HYBRID_H3 t
#define UNCURSED_PP_HYBRID_H3(f0, ...) (__VA_ARGS__)
#define TAIL_INFO(f) BOOST_PP_TUPLE_ELEM(0, f): BOOST_PP_IIF(UNCURSED_PP_HYBRID_H2(UNCURSED_PP_HYBRID_H4(f)), 0, BOOST_PP_TUPLE_SIZE(UNCURSED_PP_HYBRID_H4(f))) flags, first BOOST_PP_TUPLE_ELEM(0, UNCURSED_PP_HYBRID_H4(f))

/* #?  TAIL_INFO((cfg, RO, SYNC, DIRECT))
 * #=>     cfg: 3 flags, first RO
 */

/* #?  TAIL_INFO((bare))
 * #=>     bare: 0 flags, first
 */

/* uncursed-pp source:
 * # typed tails unpack; heads stay named
 * @macro ROUTE($r: tuple<$verb, tuple<$code, $action>...>)
 * {{concat(switch_, $r.$verb)}}:
 * @for ($code, $action) in $r
 *   case {{$code}}: {{$action}}();
 * @end
 * @endmacro
 */
#define UNCURSED_PP_ROUTE_AP1(code, action) case code: action();
#define UNCURSED_PP_ROUTE_EACH1(r, d, e) UNCURSED_PP_ROUTE_AP1 e
#define UNCURSED_PP_ROUTE_CH1_1(e) UNCURSED_PP_ROUTE_AP1 e
#define UNCURSED_PP_ROUTE_CH1_2(e) UNCURSED_PP_ROUTE_AP1 e UNCURSED_PP_ROUTE_CH1_1
#define UNCURSED_PP_ROUTE_CH1_3(e) UNCURSED_PP_ROUTE_AP1 e UNCURSED_PP_ROUTE_CH1_2
#define UNCURSED_PP_ROUTE_CH1_4(e) UNCURSED_PP_ROUTE_AP1 e UNCURSED_PP_ROUTE_CH1_3
#define UNCURSED_PP_ROUTE_CH1_5(e) UNCURSED_PP_ROUTE_AP1 e UNCURSED_PP_ROUTE_CH1_4
#define UNCURSED_PP_ROUTE_CH1_6(e) UNCURSED_PP_ROUTE_AP1 e UNCURSED_PP_ROUTE_CH1_5
#define UNCURSED_PP_ROUTE_CH1_7(e) UNCURSED_PP_ROUTE_AP1 e UNCURSED_PP_ROUTE_CH1_6
#define UNCURSED_PP_ROUTE_CH1_8(e) UNCURSED_PP_ROUTE_AP1 e UNCURSED_PP_ROUTE_CH1_7
#define UNCURSED_PP_ROUTE_CH1_9(e) UNCURSED_PP_ROUTE_AP1 e UNCURSED_PP_ROUTE_CH1_8
#define UNCURSED_PP_ROUTE_CH1_10(e) UNCURSED_PP_ROUTE_AP1 e UNCURSED_PP_ROUTE_CH1_9
#define UNCURSED_PP_ROUTE_CH1_11(e) UNCURSED_PP_ROUTE_AP1 e UNCURSED_PP_ROUTE_CH1_10
#define UNCURSED_PP_ROUTE_CH1_12(e) UNCURSED_PP_ROUTE_AP1 e UNCURSED_PP_ROUTE_CH1_11
#define UNCURSED_PP_ROUTE_CH1_13(e) UNCURSED_PP_ROUTE_AP1 e UNCURSED_PP_ROUTE_CH1_12
#define UNCURSED_PP_ROUTE_CH1_14(e) UNCURSED_PP_ROUTE_AP1 e UNCURSED_PP_ROUTE_CH1_13
#define UNCURSED_PP_ROUTE_CH1_15(e) UNCURSED_PP_ROUTE_AP1 e UNCURSED_PP_ROUTE_CH1_14
#define UNCURSED_PP_ROUTE_CH1_16(e) UNCURSED_PP_ROUTE_AP1 e UNCURSED_PP_ROUTE_CH1_15
#define UNCURSED_PP_ROUTE_LOOP1(r) UNCURSED_PP_ROUTE_PICK1(BOOST_PP_SEQ_SIZE(BOOST_PP_TUPLE_TO_SEQ(UNCURSED_PP_HYBRID_H4(r))))(BOOST_PP_TUPLE_TO_SEQ(UNCURSED_PP_HYBRID_H4(r)))
#define UNCURSED_PP_ROUTE_NIL1(r)
#define UNCURSED_PP_ROUTE_SMALL1(seq) BOOST_PP_CAT(UNCURSED_PP_ROUTE_CH1_, BOOST_PP_SEQ_SIZE(seq)) seq
#define UNCURSED_PP_ROUTE_PICK1(n) BOOST_PP_IIF(BOOST_PP_CAT(UNCURSED_PP_LE16_, n), UNCURSED_PP_ROUTE_SMALL1, UNCURSED_PP_ROUTE_BIG1)
#define UNCURSED_PP_ROUTE_BIG1(seq) BOOST_PP_SEQ_FOR_EACH(UNCURSED_PP_ROUTE_EACH1, ~, seq)
#define ROUTE(r) \
    BOOST_PP_CAT(switch_, BOOST_PP_TUPLE_ELEM(0, r)): \
    BOOST_PP_IIF(UNCURSED_PP_HYBRID_H2(UNCURSED_PP_HYBRID_H4(r)), UNCURSED_PP_ROUTE_NIL1, UNCURSED_PP_ROUTE_LOOP1)(r)

/* #?  ROUTE((GET, (200, ok), (404, missing)))
 * #=>     switch_GET:
 * #=>     case 200: ok();
 * #=>     case 404: missing();
 */

/* uncursed-pp source:
 * # collapse interaction: identical tail loops in two macros share one
 * # helper family through the TAIL extraction (chain families move as
 * # units - docs/optimization.md round 3); small and empty inputs pin
 * # the CAT-dispatched paths
 * @macro EMIT_A($f: tuple<$n, token...>)
 * @for $x in $f
 *   emit({{$x}});
 * @end
 * @endmacro
 */
#define UNCURSED_PP_HYBRID_H5(r, d, e) emit(e);
#define UNCURSED_PP_HYBRID_HC6_1(e) emit(e);
#define UNCURSED_PP_HYBRID_HC6_2(e) emit(e); UNCURSED_PP_HYBRID_HC6_1
#define UNCURSED_PP_HYBRID_HC6_3(e) emit(e); UNCURSED_PP_HYBRID_HC6_2
#define UNCURSED_PP_HYBRID_HC6_4(e) emit(e); UNCURSED_PP_HYBRID_HC6_3
#define UNCURSED_PP_HYBRID_HC6_5(e) emit(e); UNCURSED_PP_HYBRID_HC6_4
#define UNCURSED_PP_HYBRID_HC6_6(e) emit(e); UNCURSED_PP_HYBRID_HC6_5
#define UNCURSED_PP_HYBRID_HC6_7(e) emit(e); UNCURSED_PP_HYBRID_HC6_6
#define UNCURSED_PP_HYBRID_HC6_8(e) emit(e); UNCURSED_PP_HYBRID_HC6_7
#define UNCURSED_PP_HYBRID_HC6_9(e) emit(e); UNCURSED_PP_HYBRID_HC6_8
#define UNCURSED_PP_HYBRID_HC6_10(e) emit(e); UNCURSED_PP_HYBRID_HC6_9
#define UNCURSED_PP_HYBRID_HC6_11(e) emit(e); UNCURSED_PP_HYBRID_HC6_10
#define UNCURSED_PP_HYBRID_HC6_12(e) emit(e); UNCURSED_PP_HYBRID_HC6_11
#define UNCURSED_PP_HYBRID_HC6_13(e) emit(e); UNCURSED_PP_HYBRID_HC6_12
#define UNCURSED_PP_HYBRID_HC6_14(e) emit(e); UNCURSED_PP_HYBRID_HC6_13
#define UNCURSED_PP_HYBRID_HC6_15(e) emit(e); UNCURSED_PP_HYBRID_HC6_14
#define UNCURSED_PP_HYBRID_HC6_16(e) emit(e); UNCURSED_PP_HYBRID_HC6_15
#define UNCURSED_PP_EMIT_A_LOOP1(f) UNCURSED_PP_EMIT_A_PICK1(BOOST_PP_SEQ_SIZE(BOOST_PP_TUPLE_TO_SEQ(UNCURSED_PP_HYBRID_H4(f))))(BOOST_PP_TUPLE_TO_SEQ(UNCURSED_PP_HYBRID_H4(f)))
#define UNCURSED_PP_EMIT_A_SMALL1(seq) BOOST_PP_CAT(UNCURSED_PP_HYBRID_HC6_, BOOST_PP_SEQ_SIZE(seq)) seq
#define UNCURSED_PP_EMIT_A_PICK1(n) BOOST_PP_IIF(BOOST_PP_CAT(UNCURSED_PP_LE16_, n), UNCURSED_PP_EMIT_A_SMALL1, UNCURSED_PP_EMIT_A_BIG1)
#define UNCURSED_PP_EMIT_A_BIG1(seq) BOOST_PP_SEQ_FOR_EACH(UNCURSED_PP_HYBRID_H5, ~, seq)
#define EMIT_A(f) BOOST_PP_IIF(UNCURSED_PP_HYBRID_H2(UNCURSED_PP_HYBRID_H4(f)), UNCURSED_PP_HYBRID_H1, UNCURSED_PP_EMIT_A_LOOP1)(f)

/* uncursed-pp source:
 * @macro EMIT_B($f: tuple<$n, token...>)
 * @for $x in $f
 *   emit({{$x}});
 * @end
 * @endmacro
 */
#define UNCURSED_PP_EMIT_B_LOOP1(f) UNCURSED_PP_EMIT_B_PICK1(BOOST_PP_SEQ_SIZE(BOOST_PP_TUPLE_TO_SEQ(UNCURSED_PP_HYBRID_H4(f))))(BOOST_PP_TUPLE_TO_SEQ(UNCURSED_PP_HYBRID_H4(f)))
#define UNCURSED_PP_EMIT_B_SMALL1(seq) BOOST_PP_CAT(UNCURSED_PP_HYBRID_HC6_, BOOST_PP_SEQ_SIZE(seq)) seq
#define UNCURSED_PP_EMIT_B_PICK1(n) BOOST_PP_IIF(BOOST_PP_CAT(UNCURSED_PP_LE16_, n), UNCURSED_PP_EMIT_B_SMALL1, UNCURSED_PP_EMIT_B_BIG1)
#define UNCURSED_PP_EMIT_B_BIG1(seq) BOOST_PP_SEQ_FOR_EACH(UNCURSED_PP_HYBRID_H5, ~, seq)
#define EMIT_B(f) BOOST_PP_IIF(UNCURSED_PP_HYBRID_H2(UNCURSED_PP_HYBRID_H4(f)), UNCURSED_PP_HYBRID_H1, UNCURSED_PP_EMIT_B_LOOP1)(f)

/* #?  EMIT_A((h, one, two))
 * #=>     emit(one); emit(two);
 */

/* #?  EMIT_B((h, three))
 * #=>     emit(three);
 */

/* #?  begin EMIT_B((h)) end
 * #=>     begin end
 */

/* uncursed-pp source:
 * # hybrids as seq elements: per-row heads, variable-width tails
 * @macro ROWS($fs: seq<tuple<$n, token...>>)
 * @for $f in $fs
 *   {{$f.$n}}[ @join $f as $a with ", ": {{$a}}@end ]
 * @end
 * @endmacro
 */
#define UNCURSED_PP_ROWS_EACH1(z, n, d) BOOST_PP_COMMA_IF(n) BOOST_PP_SEQ_ELEM(n, d)
#define UNCURSED_PP_ROWS_LOOP1(f) BOOST_PP_REPEAT(BOOST_PP_SEQ_SIZE(BOOST_PP_TUPLE_TO_SEQ(UNCURSED_PP_HYBRID_H4(f))), UNCURSED_PP_ROWS_EACH1, BOOST_PP_TUPLE_TO_SEQ(UNCURSED_PP_HYBRID_H4(f)))
#define UNCURSED_PP_ROWS_EACH2(r, d, e) BOOST_PP_TUPLE_ELEM(0, e)[ BOOST_PP_IIF(UNCURSED_PP_HYBRID_H2(UNCURSED_PP_HYBRID_H4(e)), UNCURSED_PP_HYBRID_H1, UNCURSED_PP_ROWS_LOOP1)(e) ]
#define ROWS(fs) BOOST_PP_SEQ_FOR_EACH(UNCURSED_PP_ROWS_EACH2, ~, fs)

/* #?  ROWS(((r1, a, b))((r2))((r3, c)))
 * #=>     r1[ a, b ] r2[ ] r3[ c ]
 */

/* uncursed-pp source:
 * # named-head access works INSIDE a loop over the same hybrid's tail
 * # (named access reads the head, iteration stays tail-scoped)
 * @macro TAGGED($f: tuple<$name, token...>)
 * @for $v in $f
 * h({{$f.$name}}, {{$v}});
 * @end
 * @endmacro
 */
#define UNCURSED_PP_TAGGED_EACH1(r, d, e) h(BOOST_PP_TUPLE_ELEM(0, d), e);
#define UNCURSED_PP_TAGGED_LOOP1(f) BOOST_PP_SEQ_FOR_EACH(UNCURSED_PP_TAGGED_EACH1, f, BOOST_PP_TUPLE_TO_SEQ(UNCURSED_PP_HYBRID_H4(f)))
#define TAGGED(f) BOOST_PP_IIF(UNCURSED_PP_HYBRID_H2(UNCURSED_PP_HYBRID_H4(f)), UNCURSED_PP_HYBRID_H1, UNCURSED_PP_TAGGED_LOOP1)(f)

/* #?  TAGGED((pt, a, b))
 * #=>     h(pt, a); h(pt, b);
 */

/* #?  begin TAGGED((pt)) end
 * #=>     begin end
 */
