/* Generated by uncursed-pp from rows.uncursed — do not edit. */
#pragma once

#include <boost/preprocessor/cat.hpp>
#include <boost/preprocessor/control/if.hpp>
#include <boost/preprocessor/control/iif.hpp>
#include <boost/preprocessor/facilities/empty.hpp>
#include <boost/preprocessor/facilities/is_empty_variadic.hpp>
#include <boost/preprocessor/punctuation/comma_if.hpp>
#include <boost/preprocessor/repetition/repeat.hpp>
#include <boost/preprocessor/seq/elem.hpp>
#include <boost/preprocessor/seq/for_each.hpp>
#include <boost/preprocessor/seq/for_each_i.hpp>
#include <boost/preprocessor/seq/size.hpp>
#include <boost/preprocessor/stringize.hpp>
#include <boost/preprocessor/tuple/elem.hpp>
#include <boost/preprocessor/tuple/size.hpp>
#include <boost/preprocessor/tuple/to_seq.hpp>
#include "uncursed_pp_runtime.h"

/* # Unbounded tuples: `tuple<T...>` (bare `tuple` = `tuple<token...>`) hold
 * # a VARIABLE number of elements in one pair of parens - commas between
 * # elements, unlike a seq's (a)(b)(c). Loops and len() are emptiness-gated:
 * # () means zero elements. Elements cap at 64 (BOOST_PP_VARIADIC_SIZE).
 */

/* uncursed-pp source:
 * @macro CALL_ALL(fn, row: tuple)
 * @for x in row
 *   {{fn}}({{x}});
 * @end
 * @endmacro
 */
#define UNCURSED_PP_CALL_ALL_EACH1(r, d, e) d(e);
#define UNCURSED_PP_CALL_ALL_LOOP1(row, fn) BOOST_PP_SEQ_FOR_EACH(UNCURSED_PP_CALL_ALL_EACH1, fn, BOOST_PP_TUPLE_TO_SEQ(row))
#define UNCURSED_PP_CALL_ALL_NIL1(row, fn)
#define UNCURSED_PP_ROWS_H1(x) BOOST_PP_IS_EMPTY x
#define CALL_ALL(fn, row) BOOST_PP_IIF(UNCURSED_PP_ROWS_H1(row), UNCURSED_PP_CALL_ALL_NIL1, UNCURSED_PP_CALL_ALL_LOOP1)(row, fn)

/* #?  CALL_ALL(handle, (a, b, c))
 * #=>     handle(a); handle(b); handle(c);
 */

/* # () iterates ZERO times - the markers prove nothing stray is emitted
 * #?  begin CALL_ALL(handle, ()) end
 * #=>     begin end
 */

/* uncursed-pp source:
 * # is_empty() branches; len() reports 0 for ()
 * @macro DESCRIBE(row: tuple)
 * @if is_empty(row)
 *   nothing
 * @else
 *   {{len(row)}} items: @join row as x with " + ": {{x}}@end
 * @end
 * @endmacro
 */
#define UNCURSED_PP_DESCRIBE_THEN1(row) nothing
#define UNCURSED_PP_DESCRIBE_SEP1() +
#define UNCURSED_PP_DESCRIBE_EACH1(r, d, i, e) BOOST_PP_IF(i, UNCURSED_PP_DESCRIBE_SEP1, BOOST_PP_EMPTY)() e
#define UNCURSED_PP_DESCRIBE_CH1_1(e) e
#define UNCURSED_PP_DESCRIBE_CH1_2(e) e + UNCURSED_PP_DESCRIBE_CH1_1
#define UNCURSED_PP_DESCRIBE_CH1_3(e) e + UNCURSED_PP_DESCRIBE_CH1_2
#define UNCURSED_PP_DESCRIBE_CH1_4(e) e + UNCURSED_PP_DESCRIBE_CH1_3
#define UNCURSED_PP_DESCRIBE_CH1_5(e) e + UNCURSED_PP_DESCRIBE_CH1_4
#define UNCURSED_PP_DESCRIBE_CH1_6(e) e + UNCURSED_PP_DESCRIBE_CH1_5
#define UNCURSED_PP_DESCRIBE_CH1_7(e) e + UNCURSED_PP_DESCRIBE_CH1_6
#define UNCURSED_PP_DESCRIBE_CH1_8(e) e + UNCURSED_PP_DESCRIBE_CH1_7
#define UNCURSED_PP_DESCRIBE_CH1_9(e) e + UNCURSED_PP_DESCRIBE_CH1_8
#define UNCURSED_PP_DESCRIBE_CH1_10(e) e + UNCURSED_PP_DESCRIBE_CH1_9
#define UNCURSED_PP_DESCRIBE_CH1_11(e) e + UNCURSED_PP_DESCRIBE_CH1_10
#define UNCURSED_PP_DESCRIBE_CH1_12(e) e + UNCURSED_PP_DESCRIBE_CH1_11
#define UNCURSED_PP_DESCRIBE_CH1_13(e) e + UNCURSED_PP_DESCRIBE_CH1_12
#define UNCURSED_PP_DESCRIBE_CH1_14(e) e + UNCURSED_PP_DESCRIBE_CH1_13
#define UNCURSED_PP_DESCRIBE_CH1_15(e) e + UNCURSED_PP_DESCRIBE_CH1_14
#define UNCURSED_PP_DESCRIBE_CH1_16(e) e + UNCURSED_PP_DESCRIBE_CH1_15
#define UNCURSED_PP_DESCRIBE_LOOP1(row) UNCURSED_PP_DESCRIBE_PICK1(BOOST_PP_SEQ_SIZE(BOOST_PP_TUPLE_TO_SEQ(row)))(BOOST_PP_TUPLE_TO_SEQ(row))
#define UNCURSED_PP_ROWS_H2(row)
#define UNCURSED_PP_DESCRIBE_ELSE1(row) BOOST_PP_IIF(UNCURSED_PP_ROWS_H1(row), 0, BOOST_PP_TUPLE_SIZE(row)) items: BOOST_PP_IIF(UNCURSED_PP_ROWS_H1(row), UNCURSED_PP_ROWS_H2, UNCURSED_PP_DESCRIBE_LOOP1)(row)
#define UNCURSED_PP_DESCRIBE_SMALL1(seq) BOOST_PP_CAT(UNCURSED_PP_DESCRIBE_CH1_, BOOST_PP_SEQ_SIZE(seq)) seq
#define UNCURSED_PP_DESCRIBE_PICK1(n) BOOST_PP_IIF(BOOST_PP_CAT(UNCURSED_PP_LE16_, n), UNCURSED_PP_DESCRIBE_SMALL1, UNCURSED_PP_DESCRIBE_BIG1)
#define UNCURSED_PP_DESCRIBE_BIG1(seq) BOOST_PP_SEQ_FOR_EACH_I(UNCURSED_PP_DESCRIBE_EACH1, ~, seq)
#define DESCRIBE(row) BOOST_PP_IIF(UNCURSED_PP_ROWS_H1(row), UNCURSED_PP_DESCRIBE_THEN1, UNCURSED_PP_DESCRIBE_ELSE1)(row)

/* #?  DESCRIBE((p, q))
 * #=>     2 items: p + q
 */

/* #?  DESCRIBE(())
 * #=>     nothing
 */

/* uncursed-pp source:
 * # typed elements: named pairs give single-paren call sites
 * @macro SET_ALL(ps: tuple<tuple<key, value>...>)
 * @for (key, value) in ps
 *   cfg_set({{stringize(key)}}, {{value}});
 * @end
 * @endmacro
 */
#define UNCURSED_PP_SET_ALL_AP1(key, value) cfg_set(BOOST_PP_STRINGIZE(key), value);
#define UNCURSED_PP_SET_ALL_EACH1(r, d, e) UNCURSED_PP_SET_ALL_AP1 e
#define UNCURSED_PP_SET_ALL_CH1_1(e) UNCURSED_PP_SET_ALL_AP1 e
#define UNCURSED_PP_SET_ALL_CH1_2(e) UNCURSED_PP_SET_ALL_AP1 e UNCURSED_PP_SET_ALL_CH1_1
#define UNCURSED_PP_SET_ALL_CH1_3(e) UNCURSED_PP_SET_ALL_AP1 e UNCURSED_PP_SET_ALL_CH1_2
#define UNCURSED_PP_SET_ALL_CH1_4(e) UNCURSED_PP_SET_ALL_AP1 e UNCURSED_PP_SET_ALL_CH1_3
#define UNCURSED_PP_SET_ALL_CH1_5(e) UNCURSED_PP_SET_ALL_AP1 e UNCURSED_PP_SET_ALL_CH1_4
#define UNCURSED_PP_SET_ALL_CH1_6(e) UNCURSED_PP_SET_ALL_AP1 e UNCURSED_PP_SET_ALL_CH1_5
#define UNCURSED_PP_SET_ALL_CH1_7(e) UNCURSED_PP_SET_ALL_AP1 e UNCURSED_PP_SET_ALL_CH1_6
#define UNCURSED_PP_SET_ALL_CH1_8(e) UNCURSED_PP_SET_ALL_AP1 e UNCURSED_PP_SET_ALL_CH1_7
#define UNCURSED_PP_SET_ALL_CH1_9(e) UNCURSED_PP_SET_ALL_AP1 e UNCURSED_PP_SET_ALL_CH1_8
#define UNCURSED_PP_SET_ALL_CH1_10(e) UNCURSED_PP_SET_ALL_AP1 e UNCURSED_PP_SET_ALL_CH1_9
#define UNCURSED_PP_SET_ALL_CH1_11(e) UNCURSED_PP_SET_ALL_AP1 e UNCURSED_PP_SET_ALL_CH1_10
#define UNCURSED_PP_SET_ALL_CH1_12(e) UNCURSED_PP_SET_ALL_AP1 e UNCURSED_PP_SET_ALL_CH1_11
#define UNCURSED_PP_SET_ALL_CH1_13(e) UNCURSED_PP_SET_ALL_AP1 e UNCURSED_PP_SET_ALL_CH1_12
#define UNCURSED_PP_SET_ALL_CH1_14(e) UNCURSED_PP_SET_ALL_AP1 e UNCURSED_PP_SET_ALL_CH1_13
#define UNCURSED_PP_SET_ALL_CH1_15(e) UNCURSED_PP_SET_ALL_AP1 e UNCURSED_PP_SET_ALL_CH1_14
#define UNCURSED_PP_SET_ALL_CH1_16(e) UNCURSED_PP_SET_ALL_AP1 e UNCURSED_PP_SET_ALL_CH1_15
#define UNCURSED_PP_SET_ALL_LOOP1(ps) UNCURSED_PP_SET_ALL_PICK1(BOOST_PP_SEQ_SIZE(BOOST_PP_TUPLE_TO_SEQ(ps)))(BOOST_PP_TUPLE_TO_SEQ(ps))
#define UNCURSED_PP_SET_ALL_NIL1(ps)
#define UNCURSED_PP_SET_ALL_SMALL1(seq) BOOST_PP_CAT(UNCURSED_PP_SET_ALL_CH1_, BOOST_PP_SEQ_SIZE(seq)) seq
#define UNCURSED_PP_SET_ALL_PICK1(n) BOOST_PP_IIF(BOOST_PP_CAT(UNCURSED_PP_LE16_, n), UNCURSED_PP_SET_ALL_SMALL1, UNCURSED_PP_SET_ALL_BIG1)
#define UNCURSED_PP_SET_ALL_BIG1(seq) BOOST_PP_SEQ_FOR_EACH(UNCURSED_PP_SET_ALL_EACH1, ~, seq)
#define SET_ALL(ps) BOOST_PP_IIF(UNCURSED_PP_ROWS_H1(ps), UNCURSED_PP_SET_ALL_NIL1, UNCURSED_PP_SET_ALL_LOOP1)(ps)

/* #?  SET_ALL(((retries, 3), (timeout, 30)))
 * #=>     cfg_set("retries", 3);
 * #=>     cfg_set("timeout", 30);
 */

/* #?  begin SET_ALL(()) end
 * #=>     begin end
 */

/* uncursed-pp source:
 * # collapse interaction: two macros with identical no-free-var loop bodies
 * # share one helper family (chain members merge as a unit; small and empty
 * # inputs pin the CAT-dispatched paths - see docs/optimization.md round 3)
 * @macro TRACE_ROW(row: tuple)
 * @for x in row
 *   trace({{x}});
 * @end
 * @endmacro
 */
#define UNCURSED_PP_ROWS_H3(r, d, e) trace(e);
#define UNCURSED_PP_ROWS_HC4_1(e) trace(e);
#define UNCURSED_PP_ROWS_HC4_2(e) trace(e); UNCURSED_PP_ROWS_HC4_1
#define UNCURSED_PP_ROWS_HC4_3(e) trace(e); UNCURSED_PP_ROWS_HC4_2
#define UNCURSED_PP_ROWS_HC4_4(e) trace(e); UNCURSED_PP_ROWS_HC4_3
#define UNCURSED_PP_ROWS_HC4_5(e) trace(e); UNCURSED_PP_ROWS_HC4_4
#define UNCURSED_PP_ROWS_HC4_6(e) trace(e); UNCURSED_PP_ROWS_HC4_5
#define UNCURSED_PP_ROWS_HC4_7(e) trace(e); UNCURSED_PP_ROWS_HC4_6
#define UNCURSED_PP_ROWS_HC4_8(e) trace(e); UNCURSED_PP_ROWS_HC4_7
#define UNCURSED_PP_ROWS_HC4_9(e) trace(e); UNCURSED_PP_ROWS_HC4_8
#define UNCURSED_PP_ROWS_HC4_10(e) trace(e); UNCURSED_PP_ROWS_HC4_9
#define UNCURSED_PP_ROWS_HC4_11(e) trace(e); UNCURSED_PP_ROWS_HC4_10
#define UNCURSED_PP_ROWS_HC4_12(e) trace(e); UNCURSED_PP_ROWS_HC4_11
#define UNCURSED_PP_ROWS_HC4_13(e) trace(e); UNCURSED_PP_ROWS_HC4_12
#define UNCURSED_PP_ROWS_HC4_14(e) trace(e); UNCURSED_PP_ROWS_HC4_13
#define UNCURSED_PP_ROWS_HC4_15(e) trace(e); UNCURSED_PP_ROWS_HC4_14
#define UNCURSED_PP_ROWS_HC4_16(e) trace(e); UNCURSED_PP_ROWS_HC4_15
#define UNCURSED_PP_TRACE_ROW_LOOP1(row) UNCURSED_PP_TRACE_ROW_PICK1(BOOST_PP_SEQ_SIZE(BOOST_PP_TUPLE_TO_SEQ(row)))(BOOST_PP_TUPLE_TO_SEQ(row))
#define UNCURSED_PP_TRACE_ROW_SMALL1(seq) BOOST_PP_CAT(UNCURSED_PP_ROWS_HC4_, BOOST_PP_SEQ_SIZE(seq)) seq
#define UNCURSED_PP_TRACE_ROW_PICK1(n) BOOST_PP_IIF(BOOST_PP_CAT(UNCURSED_PP_LE16_, n), UNCURSED_PP_TRACE_ROW_SMALL1, UNCURSED_PP_TRACE_ROW_BIG1)
#define UNCURSED_PP_TRACE_ROW_BIG1(seq) BOOST_PP_SEQ_FOR_EACH(UNCURSED_PP_ROWS_H3, ~, seq)
#define TRACE_ROW(row) BOOST_PP_IIF(UNCURSED_PP_ROWS_H1(row), UNCURSED_PP_ROWS_H2, UNCURSED_PP_TRACE_ROW_LOOP1)(row)

/* uncursed-pp source:
 * @macro AUDIT_ROW(row: tuple)
 * @for x in row
 *   trace({{x}});
 * @end
 * @endmacro
 */
#define UNCURSED_PP_AUDIT_ROW_LOOP1(row) UNCURSED_PP_AUDIT_ROW_PICK1(BOOST_PP_SEQ_SIZE(BOOST_PP_TUPLE_TO_SEQ(row)))(BOOST_PP_TUPLE_TO_SEQ(row))
#define UNCURSED_PP_AUDIT_ROW_SMALL1(seq) BOOST_PP_CAT(UNCURSED_PP_ROWS_HC4_, BOOST_PP_SEQ_SIZE(seq)) seq
#define UNCURSED_PP_AUDIT_ROW_PICK1(n) BOOST_PP_IIF(BOOST_PP_CAT(UNCURSED_PP_LE16_, n), UNCURSED_PP_AUDIT_ROW_SMALL1, UNCURSED_PP_AUDIT_ROW_BIG1)
#define UNCURSED_PP_AUDIT_ROW_BIG1(seq) BOOST_PP_SEQ_FOR_EACH(UNCURSED_PP_ROWS_H3, ~, seq)
#define AUDIT_ROW(row) BOOST_PP_IIF(UNCURSED_PP_ROWS_H1(row), UNCURSED_PP_ROWS_H2, UNCURSED_PP_AUDIT_ROW_LOOP1)(row)

/* #?  TRACE_ROW((a, b))
 * #=>     trace(a); trace(b);
 */

/* #?  AUDIT_ROW((z))
 * #=>     trace(z);
 */

/* #?  begin AUDIT_ROW(()) end
 * #=>     begin end
 */

/* uncursed-pp source:
 * # nesting: a seq of variable-width rows; the inner tuple may be empty
 * @macro FLATTEN(rows: seq<tuple<token...>>)
 * @for row in rows
 *   { @join row as x with ", ": {{x}}@end }
 * @end
 * @endmacro
 */
#define UNCURSED_PP_FLATTEN_EACH1(z, n, d) BOOST_PP_COMMA_IF(n) BOOST_PP_SEQ_ELEM(n, d)
#define UNCURSED_PP_FLATTEN_LOOP1(row) BOOST_PP_REPEAT(BOOST_PP_SEQ_SIZE(BOOST_PP_TUPLE_TO_SEQ(row)), UNCURSED_PP_FLATTEN_EACH1, BOOST_PP_TUPLE_TO_SEQ(row))
#define UNCURSED_PP_FLATTEN_EACH2(r, d, e) { BOOST_PP_IIF(UNCURSED_PP_ROWS_H1(e), UNCURSED_PP_ROWS_H2, UNCURSED_PP_FLATTEN_LOOP1)(e) }
#define FLATTEN(rows) BOOST_PP_SEQ_FOR_EACH(UNCURSED_PP_FLATTEN_EACH2, ~, rows)

/* #?  FLATTEN(((a, b))((c))(()))
 * #=>     { a, b } { c } { }
 */
