"""Emit Boost.PP C header text from the cursedpp AST."""

from __future__ import annotations

import re
from dataclasses import dataclass, field

from .nodes import File, ForEach, Interp, MacroDef, SeqT, Text, TupleT, VarRef
from .parser import parse_file


@dataclass
class EmitConfig:
    pp_prefix: str = "BOOST_PP_"
    pp_include: str = "boost/preprocessor.hpp"


@dataclass
class _Helper:
    name: str
    params: str
    body: str


@dataclass
class _MacroOut:
    helpers: list[_Helper] = field(default_factory=list)
    define: str = ""


class _MacroEmitter:
    """Emits one macro: a main #define plus any generated helper macros."""

    def __init__(self, macro: MacroDef, config: EmitConfig):
        self.macro = macro
        self.config = config
        self.out = _MacroOut()
        self._helper_count = 0

    def pp(self, name: str) -> str:
        return f"{self.config.pp_prefix}{name}"

    def emit(self) -> _MacroOut:
        params = ", ".join(p.name for p in self.macro.params)
        top_env = {p.name: p.name for p in self.macro.params}
        body = self._render_block(self.macro.body, top_env)
        self.out.define = _format_define(f"{self.macro.name}({params})", body)
        return self.out

    # ── rendering ────────────────────────────────────────────────────

    def _render_block(self, nodes: list, env: dict[str, str]) -> str:
        parts: list[str] = []
        for node in nodes:
            if isinstance(node, Text):
                parts.append(node.value)
            elif isinstance(node, Interp):
                parts.append(self._render_expr(node.expr, env))
            elif isinstance(node, ForEach):
                parts.append(self._render_foreach(node, env))
                parts.append("\n")
            else:  # pragma: no cover - future node kinds
                raise NotImplementedError(f"cannot emit {node!r}")
        return "".join(parts)

    def _render_expr(self, expr, env: dict[str, str]) -> str:
        if isinstance(expr, VarRef):
            return env[expr.name]
        raise NotImplementedError(f"cannot emit expression {expr!r}")  # pragma: no cover

    def _render_foreach(self, loop: ForEach, env: dict[str, str]) -> str:
        loop_env = dict(env)
        if loop.unpack is not None:
            arity = len(loop.unpack)
            for idx, name in enumerate(loop.unpack):
                loop_env[name] = f"{self.pp('TUPLE_ELEM')}({arity}, {idx}, e)"
        else:
            loop_env[loop.var] = "e"

        body = _collapse_ws(self._render_block(loop.body, loop_env))
        helper = self._add_helper("EACH", "r, d, e", body)
        return f"{self.pp('SEQ_FOR_EACH')}({helper}, ~, {env[loop.iterable]})"

    def _add_helper(self, kind: str, params: str, body: str) -> str:
        self._helper_count += 1
        name = f"CURSEDPP_{self.macro.name}_{kind}{self._helper_count}"
        self.out.helpers.append(_Helper(name=name, params=params, body=body))
        return name


def _collapse_ws(text: str) -> str:
    return re.sub(r"\s+", " ", text).strip()


def _format_define(head: str, body: str) -> str:
    lines = [line.strip() for line in body.split("\n")]
    lines = [_collapse_ws(line) for line in lines if line.strip()]
    if not lines:
        return f"#define {head}\n"
    if len(lines) == 1:
        return f"#define {head} {lines[0]}\n"
    joined = " \\\n    ".join(lines)
    return f"#define {head} \\\n    {joined}\n"


def emit_file(file: File, *, source_name: str, guard: str, config: EmitConfig | None = None) -> str:
    config = config or EmitConfig()
    chunks: list[str] = [
        f"/* Generated by cursedpp from {source_name} — do not edit. */\n",
        f"#ifndef {guard}\n#define {guard}\n",
        "\n",
        f"#include <{config.pp_include}>\n",
    ]
    for macro in file.macros:
        out = _MacroEmitter(macro, config).emit()
        chunks.append("\n")
        for helper in out.helpers:
            chunks.append(f"#define {helper.name}({helper.params}) {helper.body}\n")
        chunks.append(out.define)
    chunks.append("\n#endif\n")
    return "".join(chunks)


def _default_guard(filename: str) -> str:
    stem = filename.rsplit("/", 1)[-1]
    stem = stem.removesuffix(".cursed")
    return re.sub(r"[^A-Za-z0-9]", "_", stem).upper() + "_CURSED_H"


def compile_source(source: str, filename: str, *, guard: str | None = None, config: EmitConfig | None = None) -> str:
    """Full pipeline: parse -> emit. Convenience for the CLI and tests."""
    file = parse_file(source, filename)
    return emit_file(
        file,
        source_name=filename.rsplit("/", 1)[-1],
        guard=guard or _default_guard(filename),
        config=config,
    )
