/* Generated by uncursed-pp from branches.uncursed — do not edit. */
#pragma once

#include <boost/preprocessor/comparison/equal.hpp>
#include <boost/preprocessor/control/iif.hpp>
#include <boost/preprocessor/seq/for_each.hpp>
#include <boost/preprocessor/seq/size.hpp>
#include <boost/preprocessor/tuple/elem.hpp>

/* uncursed-pp source:
 * # Branch helpers receive the union of both branches' free variables;
 * # branch bodies may contain commas safely (each lives in its own helper).
 * macro REPORT(a, b, xs: seq<token>)
 * @if len(xs) == 1
 * one({{a}})
 * @else
 * many({{b}}, {{len(xs)}})
 * @end
 * end
 */
#define UNCURSED_PP_REPORT_THEN1(a, b, xs) one(a)
#define UNCURSED_PP_REPORT_ELSE1(a, b, xs) many(b, BOOST_PP_SEQ_SIZE(xs))
#define REPORT(a, b, xs) BOOST_PP_IIF(BOOST_PP_EQUAL(BOOST_PP_SEQ_SIZE(xs), 1), UNCURSED_PP_REPORT_THEN1, UNCURSED_PP_REPORT_ELSE1)(a, b, xs)

/* uncursed-pp source:
 * # Line-form @if nested in a @for: branch per element.
 * macro EMIT(xs: seq<tuple<kind, val>>)
 * @for (kind, val) in xs
 * @if kind == 1
 * one({{val}});
 * @else
 * other({{kind}}, {{val}});
 * @end
 * @end
 * end
 */
#define UNCURSED_PP_EMIT_THEN1(val, kind) one(val);
#define UNCURSED_PP_EMIT_ELSE1(val, kind) other(kind, val);
#define UNCURSED_PP_EMIT_AP1(kind, val) BOOST_PP_IIF(BOOST_PP_EQUAL(kind, 1), UNCURSED_PP_EMIT_THEN1, UNCURSED_PP_EMIT_ELSE1)(val, kind)
#define UNCURSED_PP_EMIT_EACH1(r, d, e) UNCURSED_PP_EMIT_AP1 e
#define EMIT(xs) BOOST_PP_SEQ_FOR_EACH(UNCURSED_PP_EMIT_EACH1, ~, xs)

/* uncursed-pp source:
 * # Two sequential @ifs in one macro get independently numbered helpers.
 * macro SIZE_CLASS(xs: seq<token>)
 * @if len(xs) == 1
 * single
 * @end
 * @if len(xs) == 2
 * double
 * @end
 * end
 */
#define UNCURSED_PP_SIZE_CLASS_THEN1() single
#define UNCURSED_PP_BRANCHES_H1()
#define UNCURSED_PP_SIZE_CLASS_THEN2() double
#define SIZE_CLASS(xs) BOOST_PP_IIF(BOOST_PP_EQUAL(BOOST_PP_SEQ_SIZE(xs), 1), UNCURSED_PP_SIZE_CLASS_THEN1, UNCURSED_PP_BRANCHES_H1)()BOOST_PP_IIF(BOOST_PP_EQUAL(BOOST_PP_SEQ_SIZE(xs), 2), UNCURSED_PP_SIZE_CLASS_THEN2, UNCURSED_PP_BRANCHES_H1)()
