/* Generated by uncursed-pp from ctor.uncursed — do not edit. */
#pragma once

#include <boost/preprocessor/cat.hpp>
#include <boost/preprocessor/comparison/equal.hpp>
#include <boost/preprocessor/control/iif.hpp>
#include <boost/preprocessor/punctuation/comma_if.hpp>
#include <boost/preprocessor/seq/for_each_i.hpp>
#include <boost/preprocessor/seq/size.hpp>
#include <boost/preprocessor/tuple/elem.hpp>
#include "uncursed_pp_runtime.h"

/* uncursed-pp source:
 * # Branch on argument count: single-arg vs n-arg initializer.
 * macro CTOR(name, args: seq<tuple<type, argname>>)
 * @if len(args) == 1
 *   explicit_single_arg_init({{name}})
 * @else
 *   {{concat(name, _init)}}(@join args with ", ": {{argname}}@end)
 * @end
 * end
 */
#define UNCURSED_PP_CTOR_THEN1(name, args) explicit_single_arg_init(name)
#define UNCURSED_PP_CTOR_AP1(type, argname) argname
#define UNCURSED_PP_CTOR_EACH1(r, d, i, e) BOOST_PP_COMMA_IF(i) UNCURSED_PP_CTOR_AP1 e
#define UNCURSED_PP_CTOR_CH1_1(e) UNCURSED_PP_CTOR_AP1 e
#define UNCURSED_PP_CTOR_CH1_2(e) UNCURSED_PP_CTOR_AP1 e, UNCURSED_PP_CTOR_CH1_1
#define UNCURSED_PP_CTOR_CH1_3(e) UNCURSED_PP_CTOR_AP1 e, UNCURSED_PP_CTOR_CH1_2
#define UNCURSED_PP_CTOR_CH1_4(e) UNCURSED_PP_CTOR_AP1 e, UNCURSED_PP_CTOR_CH1_3
#define UNCURSED_PP_CTOR_CH1_5(e) UNCURSED_PP_CTOR_AP1 e, UNCURSED_PP_CTOR_CH1_4
#define UNCURSED_PP_CTOR_CH1_6(e) UNCURSED_PP_CTOR_AP1 e, UNCURSED_PP_CTOR_CH1_5
#define UNCURSED_PP_CTOR_CH1_7(e) UNCURSED_PP_CTOR_AP1 e, UNCURSED_PP_CTOR_CH1_6
#define UNCURSED_PP_CTOR_CH1_8(e) UNCURSED_PP_CTOR_AP1 e, UNCURSED_PP_CTOR_CH1_7
#define UNCURSED_PP_CTOR_CH1_9(e) UNCURSED_PP_CTOR_AP1 e, UNCURSED_PP_CTOR_CH1_8
#define UNCURSED_PP_CTOR_CH1_10(e) UNCURSED_PP_CTOR_AP1 e, UNCURSED_PP_CTOR_CH1_9
#define UNCURSED_PP_CTOR_CH1_11(e) UNCURSED_PP_CTOR_AP1 e, UNCURSED_PP_CTOR_CH1_10
#define UNCURSED_PP_CTOR_CH1_12(e) UNCURSED_PP_CTOR_AP1 e, UNCURSED_PP_CTOR_CH1_11
#define UNCURSED_PP_CTOR_CH1_13(e) UNCURSED_PP_CTOR_AP1 e, UNCURSED_PP_CTOR_CH1_12
#define UNCURSED_PP_CTOR_CH1_14(e) UNCURSED_PP_CTOR_AP1 e, UNCURSED_PP_CTOR_CH1_13
#define UNCURSED_PP_CTOR_CH1_15(e) UNCURSED_PP_CTOR_AP1 e, UNCURSED_PP_CTOR_CH1_14
#define UNCURSED_PP_CTOR_CH1_16(e) UNCURSED_PP_CTOR_AP1 e, UNCURSED_PP_CTOR_CH1_15
#define UNCURSED_PP_CTOR_ELSE1(name, args) BOOST_PP_CAT(name, _init)(UNCURSED_PP_CTOR_PICK1(BOOST_PP_SEQ_SIZE(args))(args))
#define UNCURSED_PP_CTOR_SMALL1(seq) BOOST_PP_CAT(UNCURSED_PP_CTOR_CH1_, BOOST_PP_SEQ_SIZE(seq)) seq
#define UNCURSED_PP_CTOR_PICK1(n) BOOST_PP_IIF(BOOST_PP_CAT(UNCURSED_PP_LE16_, n), UNCURSED_PP_CTOR_SMALL1, UNCURSED_PP_CTOR_BIG1)
#define UNCURSED_PP_CTOR_BIG1(seq) BOOST_PP_SEQ_FOR_EACH_I(UNCURSED_PP_CTOR_EACH1, ~, seq)
#define CTOR(name, args) BOOST_PP_IIF(BOOST_PP_EQUAL(BOOST_PP_SEQ_SIZE(args), 1), UNCURSED_PP_CTOR_THEN1, UNCURSED_PP_CTOR_ELSE1)(name, args)
