/* Generated by uncursed-pp from ctor.uncursed — do not edit. */
#pragma once

#include <boost/preprocessor/cat.hpp>
#include <boost/preprocessor/comparison/equal.hpp>
#include <boost/preprocessor/control/iif.hpp>
#include <boost/preprocessor/punctuation/comma_if.hpp>
#include <boost/preprocessor/seq/for_each_i.hpp>
#include <boost/preprocessor/seq/size.hpp>
#include <boost/preprocessor/tuple/elem.hpp>

/* uncursed-pp source:
 * # Branch on argument count: single-arg vs n-arg initializer.
 * macro CTOR(name, args: seq<tuple<type, argname>>)
 * @if len(args) == 1
 *   explicit_single_arg_init({{name}})
 * @else
 *   {{concat(name, _init)}}(@join args with ", ": {{argname}}@end)
 * @end
 * end
 */
#define UNCURSED_PP_CTOR_THEN1(name, args) explicit_single_arg_init(name)
#define UNCURSED_PP_CTOR_AP1(type, argname) argname
#define UNCURSED_PP_CTOR_EACH1(r, d, i, e) BOOST_PP_COMMA_IF(i) UNCURSED_PP_CTOR_AP1 e
#define UNCURSED_PP_CTOR_ELSE1(name, args) BOOST_PP_CAT(name, _init)(BOOST_PP_SEQ_FOR_EACH_I(UNCURSED_PP_CTOR_EACH1, ~, args))
#define CTOR(name, args) BOOST_PP_IIF(BOOST_PP_EQUAL(BOOST_PP_SEQ_SIZE(args), 1), UNCURSED_PP_CTOR_THEN1, UNCURSED_PP_CTOR_ELSE1)(name, args)
