/* Generated by uncursed-pp from nesting.uncursed — do not edit. */
#pragma once

#include <boost/preprocessor/arithmetic/dec.hpp>
#include <boost/preprocessor/cat.hpp>
#include <boost/preprocessor/comparison/equal.hpp>
#include <boost/preprocessor/control/iif.hpp>
#include <boost/preprocessor/logical/bool.hpp>
#include <boost/preprocessor/seq/elem.hpp>
#include <boost/preprocessor/seq/for_each.hpp>
#include <boost/preprocessor/seq/size.hpp>
#include <boost/preprocessor/tuple/elem.hpp>
#include "uncursed_pp_runtime.h"

/* # Deep nesting: loops inside @if branches, @ifs inside @ifs, and loops
 * # inside loops (up to 4 deep) are all fine; only loop depth 5+ is rejected.
 */

/* uncursed-pp source:
 * # @for inside an @else branch
 * @macro OPT($xs: seq<token>)
 * @if len($xs) == 1
 * solo({{$xs[0]}})
 * @else
 * @for $x in $xs
 * many({{$x}});
 * @end
 * @end
 * @endmacro
 */
#define UNCURSED_PP_OPT_THEN1(xs) solo(BOOST_PP_SEQ_ELEM(0, xs))
#define UNCURSED_PP_OPT_EACH1(r, d, e) many(e);
#define UNCURSED_PP_OPT_CH1_1(e) many(e);
#define UNCURSED_PP_OPT_CH1_2(e) many(e); UNCURSED_PP_OPT_CH1_1
#define UNCURSED_PP_OPT_CH1_3(e) many(e); UNCURSED_PP_OPT_CH1_2
#define UNCURSED_PP_OPT_CH1_4(e) many(e); UNCURSED_PP_OPT_CH1_3
#define UNCURSED_PP_OPT_CH1_5(e) many(e); UNCURSED_PP_OPT_CH1_4
#define UNCURSED_PP_OPT_CH1_6(e) many(e); UNCURSED_PP_OPT_CH1_5
#define UNCURSED_PP_OPT_CH1_7(e) many(e); UNCURSED_PP_OPT_CH1_6
#define UNCURSED_PP_OPT_CH1_8(e) many(e); UNCURSED_PP_OPT_CH1_7
#define UNCURSED_PP_OPT_CH1_9(e) many(e); UNCURSED_PP_OPT_CH1_8
#define UNCURSED_PP_OPT_CH1_10(e) many(e); UNCURSED_PP_OPT_CH1_9
#define UNCURSED_PP_OPT_CH1_11(e) many(e); UNCURSED_PP_OPT_CH1_10
#define UNCURSED_PP_OPT_CH1_12(e) many(e); UNCURSED_PP_OPT_CH1_11
#define UNCURSED_PP_OPT_CH1_13(e) many(e); UNCURSED_PP_OPT_CH1_12
#define UNCURSED_PP_OPT_CH1_14(e) many(e); UNCURSED_PP_OPT_CH1_13
#define UNCURSED_PP_OPT_CH1_15(e) many(e); UNCURSED_PP_OPT_CH1_14
#define UNCURSED_PP_OPT_CH1_16(e) many(e); UNCURSED_PP_OPT_CH1_15
#define UNCURSED_PP_OPT_ELSE1(xs) UNCURSED_PP_OPT_PICK1(BOOST_PP_SEQ_SIZE(xs))(xs)
#define UNCURSED_PP_OPT_SMALL1(seq) BOOST_PP_CAT(UNCURSED_PP_OPT_CH1_, BOOST_PP_SEQ_SIZE(seq)) seq
#define UNCURSED_PP_OPT_PICK1(n) BOOST_PP_IIF(BOOST_PP_CAT(UNCURSED_PP_LE16_, n), UNCURSED_PP_OPT_SMALL1, UNCURSED_PP_OPT_BIG1)
#define UNCURSED_PP_OPT_BIG1(seq) BOOST_PP_SEQ_FOR_EACH(UNCURSED_PP_OPT_EACH1, ~, seq)
#define OPT(xs) BOOST_PP_IIF(BOOST_PP_EQUAL(BOOST_PP_SEQ_SIZE(xs), 1), UNCURSED_PP_OPT_THEN1, UNCURSED_PP_OPT_ELSE1)(xs)

/* uncursed-pp source:
 * # @if inside an @if branch
 * @macro GRADE($xs: seq<token>)
 * @if len($xs) < 3
 * @if len($xs) == 1
 * tiny
 * @else
 * small
 * @end
 * @else
 * big
 * @end
 * @endmacro
 */
#define UNCURSED_PP_GRADE_THEN1() tiny
#define UNCURSED_PP_GRADE_ELSE1() small
#define UNCURSED_PP_GRADE_THEN2(xs) BOOST_PP_IIF(BOOST_PP_EQUAL(BOOST_PP_SEQ_SIZE(xs), 1), UNCURSED_PP_GRADE_THEN1, UNCURSED_PP_GRADE_ELSE1)()
#define UNCURSED_PP_GRADE_ELSE2(xs) big
#define GRADE(xs) BOOST_PP_IIF(BOOST_PP_BOOL(BOOST_PP_DEC(BOOST_PP_DEC(BOOST_PP_SEQ_SIZE(xs)))), UNCURSED_PP_GRADE_ELSE2, UNCURSED_PP_GRADE_THEN2)(xs)

/* uncursed-pp source:
 * # three levels: @if -> @for -> @if
 * @macro TRIAGE($xs: seq<tuple<$kind, $val>>)
 * @if len($xs) == 1
 * only({{$xs[0].$val}});
 * @else
 * @for ($kind, $val) in $xs
 * @if $kind == 1
 * urgent({{$val}});
 * @else
 * routine({{$kind}}, {{$val}});
 * @end
 * @end
 * @end
 * @endmacro
 */
#define UNCURSED_PP_TRIAGE_THEN1(xs) only(BOOST_PP_TUPLE_ELEM(1, BOOST_PP_SEQ_ELEM(0, xs)));
#define UNCURSED_PP_TRIAGE_THEN2(val, kind) urgent(val);
#define UNCURSED_PP_TRIAGE_ELSE1(val, kind) routine(kind, val);
#define UNCURSED_PP_TRIAGE_AP1(kind, val) BOOST_PP_IIF(BOOST_PP_EQUAL(kind, 1), UNCURSED_PP_TRIAGE_THEN2, UNCURSED_PP_TRIAGE_ELSE1)(val, kind)
#define UNCURSED_PP_TRIAGE_EACH1(r, d, e) UNCURSED_PP_TRIAGE_AP1 e
#define UNCURSED_PP_TRIAGE_CH1_1(e) UNCURSED_PP_TRIAGE_AP1 e
#define UNCURSED_PP_TRIAGE_CH1_2(e) UNCURSED_PP_TRIAGE_AP1 e UNCURSED_PP_TRIAGE_CH1_1
#define UNCURSED_PP_TRIAGE_CH1_3(e) UNCURSED_PP_TRIAGE_AP1 e UNCURSED_PP_TRIAGE_CH1_2
#define UNCURSED_PP_TRIAGE_CH1_4(e) UNCURSED_PP_TRIAGE_AP1 e UNCURSED_PP_TRIAGE_CH1_3
#define UNCURSED_PP_TRIAGE_CH1_5(e) UNCURSED_PP_TRIAGE_AP1 e UNCURSED_PP_TRIAGE_CH1_4
#define UNCURSED_PP_TRIAGE_CH1_6(e) UNCURSED_PP_TRIAGE_AP1 e UNCURSED_PP_TRIAGE_CH1_5
#define UNCURSED_PP_TRIAGE_CH1_7(e) UNCURSED_PP_TRIAGE_AP1 e UNCURSED_PP_TRIAGE_CH1_6
#define UNCURSED_PP_TRIAGE_CH1_8(e) UNCURSED_PP_TRIAGE_AP1 e UNCURSED_PP_TRIAGE_CH1_7
#define UNCURSED_PP_TRIAGE_CH1_9(e) UNCURSED_PP_TRIAGE_AP1 e UNCURSED_PP_TRIAGE_CH1_8
#define UNCURSED_PP_TRIAGE_CH1_10(e) UNCURSED_PP_TRIAGE_AP1 e UNCURSED_PP_TRIAGE_CH1_9
#define UNCURSED_PP_TRIAGE_CH1_11(e) UNCURSED_PP_TRIAGE_AP1 e UNCURSED_PP_TRIAGE_CH1_10
#define UNCURSED_PP_TRIAGE_CH1_12(e) UNCURSED_PP_TRIAGE_AP1 e UNCURSED_PP_TRIAGE_CH1_11
#define UNCURSED_PP_TRIAGE_CH1_13(e) UNCURSED_PP_TRIAGE_AP1 e UNCURSED_PP_TRIAGE_CH1_12
#define UNCURSED_PP_TRIAGE_CH1_14(e) UNCURSED_PP_TRIAGE_AP1 e UNCURSED_PP_TRIAGE_CH1_13
#define UNCURSED_PP_TRIAGE_CH1_15(e) UNCURSED_PP_TRIAGE_AP1 e UNCURSED_PP_TRIAGE_CH1_14
#define UNCURSED_PP_TRIAGE_CH1_16(e) UNCURSED_PP_TRIAGE_AP1 e UNCURSED_PP_TRIAGE_CH1_15
#define UNCURSED_PP_TRIAGE_ELSE2(xs) UNCURSED_PP_TRIAGE_PICK1(BOOST_PP_SEQ_SIZE(xs))(xs)
#define UNCURSED_PP_TRIAGE_SMALL1(seq) BOOST_PP_CAT(UNCURSED_PP_TRIAGE_CH1_, BOOST_PP_SEQ_SIZE(seq)) seq
#define UNCURSED_PP_TRIAGE_PICK1(n) BOOST_PP_IIF(BOOST_PP_CAT(UNCURSED_PP_LE16_, n), UNCURSED_PP_TRIAGE_SMALL1, UNCURSED_PP_TRIAGE_BIG1)
#define UNCURSED_PP_TRIAGE_BIG1(seq) BOOST_PP_SEQ_FOR_EACH(UNCURSED_PP_TRIAGE_EACH1, ~, seq)
#define TRIAGE(xs) BOOST_PP_IIF(BOOST_PP_EQUAL(BOOST_PP_SEQ_SIZE(xs), 1), UNCURSED_PP_TRIAGE_THEN1, UNCURSED_PP_TRIAGE_ELSE2)(xs)

/* # ── invocation specs (verified through cc -E by the spec harness) ──
 * #?  OPT((a))
 * #=>     solo(a)
 */

/* #?  OPT((a)(b))
 * #=>     many(a); many(b);
 */

/* #?  GRADE((a))
 * #=>     tiny
 */

/* #?  GRADE((a)(b))
 * #=>     small
 */

/* #?  GRADE((a)(b)(c))
 * #=>     big
 */

/* #?  TRIAGE(((1, a)))
 * #=>     only(a);
 */

/* #?  TRIAGE(((1, a))((2, b))((1, c)))
 * #=>     urgent(a); routine(2, b); urgent(c);
 */
