/* Generated by uncursed-pp from nesting.uncursed — do not edit. */
#pragma once

#include <boost/preprocessor/arithmetic/dec.hpp>
#include <boost/preprocessor/comparison/equal.hpp>
#include <boost/preprocessor/control/iif.hpp>
#include <boost/preprocessor/logical/bool.hpp>
#include <boost/preprocessor/seq/elem.hpp>
#include <boost/preprocessor/seq/for_each.hpp>
#include <boost/preprocessor/seq/size.hpp>
#include <boost/preprocessor/tuple/elem.hpp>

/* uncursed-pp source:
 * # @for inside an @else branch
 * macro OPT(xs: seq<token>)
 * @if len(xs) == 1
 * solo({{xs[0]}})
 * @else
 * @for x in xs
 * many({{x}});
 * @end
 * @end
 * end
 */
#define UNCURSED_PP_OPT_THEN1(xs) solo(BOOST_PP_SEQ_ELEM(0, xs))
#define UNCURSED_PP_OPT_EACH1(r, d, e) many(e);
#define UNCURSED_PP_OPT_ELSE1(xs) BOOST_PP_SEQ_FOR_EACH(UNCURSED_PP_OPT_EACH1, ~, xs)
#define OPT(xs) BOOST_PP_IIF(BOOST_PP_EQUAL(BOOST_PP_SEQ_SIZE(xs), 1), UNCURSED_PP_OPT_THEN1, UNCURSED_PP_OPT_ELSE1)(xs)

/* uncursed-pp source:
 * # @if inside an @if branch
 * macro GRADE(xs: seq<token>)
 * @if len(xs) < 3
 * @if len(xs) == 1
 * tiny
 * @else
 * small
 * @end
 * @else
 * big
 * @end
 * end
 */
#define UNCURSED_PP_GRADE_THEN1() tiny
#define UNCURSED_PP_GRADE_ELSE1() small
#define UNCURSED_PP_GRADE_THEN2(xs) BOOST_PP_IIF(BOOST_PP_EQUAL(BOOST_PP_SEQ_SIZE(xs), 1), UNCURSED_PP_GRADE_THEN1, UNCURSED_PP_GRADE_ELSE1)()
#define UNCURSED_PP_GRADE_ELSE2(xs) big
#define GRADE(xs) BOOST_PP_IIF(BOOST_PP_BOOL(BOOST_PP_DEC(BOOST_PP_DEC(BOOST_PP_SEQ_SIZE(xs)))), UNCURSED_PP_GRADE_ELSE2, UNCURSED_PP_GRADE_THEN2)(xs)

/* uncursed-pp source:
 * # three levels: @if -> @for -> @if
 * macro TRIAGE(xs: seq<tuple<kind, val>>)
 * @if len(xs) == 1
 * only({{xs[0].val}});
 * @else
 * @for (kind, val) in xs
 * @if kind == 1
 * urgent({{val}});
 * @else
 * routine({{kind}}, {{val}});
 * @end
 * @end
 * @end
 * end
 */
#define UNCURSED_PP_TRIAGE_THEN1(xs) only(BOOST_PP_TUPLE_ELEM(1, BOOST_PP_SEQ_ELEM(0, xs)));
#define UNCURSED_PP_TRIAGE_THEN2(val, kind) urgent(val);
#define UNCURSED_PP_TRIAGE_ELSE1(val, kind) routine(kind, val);
#define UNCURSED_PP_TRIAGE_AP1(kind, val) BOOST_PP_IIF(BOOST_PP_EQUAL(kind, 1), UNCURSED_PP_TRIAGE_THEN2, UNCURSED_PP_TRIAGE_ELSE1)(val, kind)
#define UNCURSED_PP_TRIAGE_EACH1(r, d, e) UNCURSED_PP_TRIAGE_AP1 e
#define UNCURSED_PP_TRIAGE_ELSE2(xs) BOOST_PP_SEQ_FOR_EACH(UNCURSED_PP_TRIAGE_EACH1, ~, xs)
#define TRIAGE(xs) BOOST_PP_IIF(BOOST_PP_EQUAL(BOOST_PP_SEQ_SIZE(xs), 1), UNCURSED_PP_TRIAGE_THEN1, UNCURSED_PP_TRIAGE_ELSE2)(xs)
