/* Generated by cursedpp from nesting.cursed — do not edit. */
#pragma once

#include <boost/preprocessor/comparison/equal.hpp>
#include <boost/preprocessor/comparison/less.hpp>
#include <boost/preprocessor/control/iif.hpp>
#include <boost/preprocessor/seq/elem.hpp>
#include <boost/preprocessor/seq/for_each.hpp>
#include <boost/preprocessor/seq/size.hpp>
#include <boost/preprocessor/tuple/elem.hpp>

#define CURSEDPP_OPT_THEN1(xs) solo(BOOST_PP_SEQ_ELEM(0, xs))
#define CURSEDPP_OPT_EACH1(r, d, e) many(e);
#define CURSEDPP_OPT_ELSE1(xs) BOOST_PP_SEQ_FOR_EACH(CURSEDPP_OPT_EACH1, ~, xs)
#define OPT(xs) BOOST_PP_IIF(BOOST_PP_EQUAL(BOOST_PP_SEQ_SIZE(xs), 1), CURSEDPP_OPT_THEN1, CURSEDPP_OPT_ELSE1)(xs)

#define CURSEDPP_GRADE_THEN1() tiny
#define CURSEDPP_GRADE_ELSE1() small
#define CURSEDPP_GRADE_THEN2(xs) BOOST_PP_IIF(BOOST_PP_EQUAL(BOOST_PP_SEQ_SIZE(xs), 1), CURSEDPP_GRADE_THEN1, CURSEDPP_GRADE_ELSE1)()
#define CURSEDPP_GRADE_ELSE2(xs) big
#define GRADE(xs) BOOST_PP_IIF(BOOST_PP_LESS(BOOST_PP_SEQ_SIZE(xs), 3), CURSEDPP_GRADE_THEN2, CURSEDPP_GRADE_ELSE2)(xs)

#define CURSEDPP_TRIAGE_THEN1(xs) only(BOOST_PP_TUPLE_ELEM(1, BOOST_PP_SEQ_ELEM(0, xs)));
#define CURSEDPP_TRIAGE_THEN2(val, kind) urgent(val);
#define CURSEDPP_TRIAGE_ELSE1(val, kind) routine(kind, val);
#define CURSEDPP_TRIAGE_AP1(kind, val) BOOST_PP_IIF(BOOST_PP_EQUAL(kind, 1), CURSEDPP_TRIAGE_THEN2, CURSEDPP_TRIAGE_ELSE1)(val, kind)
#define CURSEDPP_TRIAGE_EACH1(r, d, e) CURSEDPP_TRIAGE_AP1 e
#define CURSEDPP_TRIAGE_ELSE2(xs) BOOST_PP_SEQ_FOR_EACH(CURSEDPP_TRIAGE_EACH1, ~, xs)
#define TRIAGE(xs) BOOST_PP_IIF(BOOST_PP_EQUAL(BOOST_PP_SEQ_SIZE(xs), 1), CURSEDPP_TRIAGE_THEN1, CURSEDPP_TRIAGE_ELSE2)(xs)
