/* Generated by cursedpp from paren_dispatch.cursed — do not edit. */
#pragma once

#include <boost/preprocessor/cat.hpp>
#include <boost/preprocessor/control/iif.hpp>
#include <boost/preprocessor/facilities/overload.hpp>
#include <boost/preprocessor/punctuation/is_begin_parens.hpp>
#include <boost/preprocessor/punctuation/remove_parens.hpp>

/* cursedpp source:
 * # A named value's SHAPE picks the branch: parenthesized initializers
 * # become brace lists, bare tokens plain assignments, and the empty
 * # default falls through to a declaration.
 * macro DECL(name, named INIT = )
 * @if is_paren(INIT)
 * pair {{name}} = { {{remove_parens(INIT)}} };
 * @else
 * int {{name}} = {{INIT}};
 * @end
 * end
 */
#define CURSEDPP_DECL_THEN1(name, INIT) pair name = { BOOST_PP_REMOVE_PARENS(INIT) };
#define CURSEDPP_DECL_ELSE1(name, INIT) int name = INIT;
#define CURSEDPP_DECL_SET_INIT(v) 0, v
#define CURSEDPP_DECL_STEP1(e, ...) CURSEDPP_DECL_STEP_D(BOOST_PP_CAT(CURSEDPP_DECL_SET_, e), __VA_ARGS__)
#define CURSEDPP_DECL_STEP_D(...) CURSEDPP_DECL_STEP_I(__VA_ARGS__)
#define CURSEDPP_DECL_STEP_I(i, v, ...) CURSEDPP_DECL_PUT_ ## i(v, __VA_ARGS__)
#define CURSEDPP_DECL_PUT_0(v, p0) v
#define CURSEDPP_DECL_BODY(name, INIT) BOOST_PP_IIF(BOOST_PP_IS_BEGIN_PARENS(INIT), CURSEDPP_DECL_THEN1, CURSEDPP_DECL_ELSE1)(name, INIT)
#define CURSEDPP_DECL_BODY_D(...) CURSEDPP_DECL_BODY(__VA_ARGS__)
#define CURSEDPP_DECL_1(name) CURSEDPP_DECL_BODY(name, )
#define CURSEDPP_DECL_2(name, e1) CURSEDPP_DECL_BODY_D(name, CURSEDPP_DECL_STEP1(e1, ))
#define DECL(...) BOOST_PP_OVERLOAD(CURSEDPP_DECL_, __VA_ARGS__)(__VA_ARGS__)
