/* Generated by uncursed-pp from paren_dispatch.uncursed — do not edit. */
#pragma once

#include <boost/preprocessor/cat.hpp>
#include <boost/preprocessor/control/iif.hpp>
#include <boost/preprocessor/punctuation/is_begin_parens.hpp>
#include <boost/preprocessor/punctuation/remove_parens.hpp>

/* uncursed-pp source:
 * # A named value's SHAPE picks the branch: parenthesized initializers
 * # become brace lists, bare tokens plain assignments, and the empty
 * # default falls through to a declaration.
 * @macro DECL($name, named $INIT = )
 * @if is_paren($INIT)
 * pair {{$name}} = { {{remove_parens($INIT)}} };
 * @else
 * int {{$name}} = {{$INIT}};
 * @end
 * @endmacro
 */
#define UNCURSED_PP_DECL_THEN1(name, INIT) pair name = { BOOST_PP_REMOVE_PARENS(INIT) };
#define UNCURSED_PP_DECL_ELSE1(name, INIT) int name = INIT;
#define UNCURSED_PP_DECL_SET_INIT(v) 0, v
#define UNCURSED_PP_DECL_STEP1(e, ...) UNCURSED_PP_DECL_STEP_D(BOOST_PP_CAT(UNCURSED_PP_DECL_SET_, e), __VA_ARGS__)
#define UNCURSED_PP_DECL_STEP_D(...) UNCURSED_PP_DECL_STEP_I(__VA_ARGS__)
#define UNCURSED_PP_DECL_STEP_I(i, v, ...) UNCURSED_PP_DECL_PUT_ ## i(v, __VA_ARGS__)
#define UNCURSED_PP_DECL_PUT_0(v, p0) v
#define UNCURSED_PP_DECL_BODY(name, INIT) BOOST_PP_IIF(BOOST_PP_IS_BEGIN_PARENS(INIT), UNCURSED_PP_DECL_THEN1, UNCURSED_PP_DECL_ELSE1)(name, INIT)
#define UNCURSED_PP_DECL_BODY_D(...) UNCURSED_PP_DECL_BODY(__VA_ARGS__)
#define UNCURSED_PP_DECL_1(name) UNCURSED_PP_DECL_BODY(name, )
#define UNCURSED_PP_DECL_2(name, e1) UNCURSED_PP_DECL_BODY_D(name, UNCURSED_PP_DECL_STEP1(e1, ))
#define UNCURSED_PP_DECL_SIZE(...) UNCURSED_PP_DECL_SIZE_I(__VA_ARGS__, 2, 1,)
#define UNCURSED_PP_DECL_SIZE_I(e0, e1, size, ...) size
#define UNCURSED_PP_DECL_DISPATCH(n) UNCURSED_PP_DECL_DISPATCH_I(n)
#define UNCURSED_PP_DECL_DISPATCH_I(n) UNCURSED_PP_DECL_ ## n
#define DECL(...) UNCURSED_PP_DECL_DISPATCH(UNCURSED_PP_DECL_SIZE(__VA_ARGS__))(__VA_ARGS__)

/* # ── invocation specs (verified through cc -E by the spec harness) ──
 * #?  DECL(v, INIT((1, 2)))
 * #=>     pair v = { 1, 2 };
 */

/* #?  DECL(v, INIT(7))
 * #=>     int v = 7;
 */

/* # edge: empty default takes the else branch with an empty value
 * #?  DECL(v)
 * #=>     int v = ;
 */
