/* Generated by uncursed-pp from state-machine.uncursed — do not edit. */
#pragma once

#include <boost/preprocessor/cat.hpp>
#include <boost/preprocessor/control/iif.hpp>
#include <boost/preprocessor/seq/for_each.hpp>
#include <boost/preprocessor/seq/size.hpp>
#include <boost/preprocessor/tuple/elem.hpp>
#include "uncursed_pp_runtime.h"

/* # ── Combined example: a finite state machine from a transition list ──
 * #
 * # Features composing: two seq parameters, @for over tokens AND over
 * # tuples, concat() for derived names, trailing free use of a macro
 * # parameter inside loop bodies.
 * #
 * # The states seq defines the enum; the transitions seq defines step().
 * # An event that matches no transition leaves the state unchanged.
 */

/* uncursed-pp source:
 * @macro DEFINE_FSM(fsm, states: seq<token>, transitions: seq<tuple<src, evt, dst>>)
 * enum {{concat(fsm, _state)}} {
 * @for s in states
 *   {{s}},
 * @end
 * };
 * static int {{concat(fsm, _step)}}(int s, int ev) {
 * @for (src, evt, dst) in transitions
 *   if (s == {{src}} && ev == {{evt}}) return {{dst}};
 * @end
 *   return s;
 * }
 * @endmacro
 */
#define UNCURSED_PP_DEFINE_FSM_EACH1(r, d, e) e,
#define UNCURSED_PP_DEFINE_FSM_CH1_1(e) e,
#define UNCURSED_PP_DEFINE_FSM_CH1_2(e) e, UNCURSED_PP_DEFINE_FSM_CH1_1
#define UNCURSED_PP_DEFINE_FSM_CH1_3(e) e, UNCURSED_PP_DEFINE_FSM_CH1_2
#define UNCURSED_PP_DEFINE_FSM_CH1_4(e) e, UNCURSED_PP_DEFINE_FSM_CH1_3
#define UNCURSED_PP_DEFINE_FSM_CH1_5(e) e, UNCURSED_PP_DEFINE_FSM_CH1_4
#define UNCURSED_PP_DEFINE_FSM_CH1_6(e) e, UNCURSED_PP_DEFINE_FSM_CH1_5
#define UNCURSED_PP_DEFINE_FSM_CH1_7(e) e, UNCURSED_PP_DEFINE_FSM_CH1_6
#define UNCURSED_PP_DEFINE_FSM_CH1_8(e) e, UNCURSED_PP_DEFINE_FSM_CH1_7
#define UNCURSED_PP_DEFINE_FSM_CH1_9(e) e, UNCURSED_PP_DEFINE_FSM_CH1_8
#define UNCURSED_PP_DEFINE_FSM_CH1_10(e) e, UNCURSED_PP_DEFINE_FSM_CH1_9
#define UNCURSED_PP_DEFINE_FSM_CH1_11(e) e, UNCURSED_PP_DEFINE_FSM_CH1_10
#define UNCURSED_PP_DEFINE_FSM_CH1_12(e) e, UNCURSED_PP_DEFINE_FSM_CH1_11
#define UNCURSED_PP_DEFINE_FSM_CH1_13(e) e, UNCURSED_PP_DEFINE_FSM_CH1_12
#define UNCURSED_PP_DEFINE_FSM_CH1_14(e) e, UNCURSED_PP_DEFINE_FSM_CH1_13
#define UNCURSED_PP_DEFINE_FSM_CH1_15(e) e, UNCURSED_PP_DEFINE_FSM_CH1_14
#define UNCURSED_PP_DEFINE_FSM_CH1_16(e) e, UNCURSED_PP_DEFINE_FSM_CH1_15
#define UNCURSED_PP_DEFINE_FSM_AP1(src, evt, dst) if (s == src && ev == evt) return dst;
#define UNCURSED_PP_DEFINE_FSM_EACH2(r, d, e) UNCURSED_PP_DEFINE_FSM_AP1 e
#define UNCURSED_PP_DEFINE_FSM_CH2_1(e) UNCURSED_PP_DEFINE_FSM_AP1 e
#define UNCURSED_PP_DEFINE_FSM_CH2_2(e) UNCURSED_PP_DEFINE_FSM_AP1 e UNCURSED_PP_DEFINE_FSM_CH2_1
#define UNCURSED_PP_DEFINE_FSM_CH2_3(e) UNCURSED_PP_DEFINE_FSM_AP1 e UNCURSED_PP_DEFINE_FSM_CH2_2
#define UNCURSED_PP_DEFINE_FSM_CH2_4(e) UNCURSED_PP_DEFINE_FSM_AP1 e UNCURSED_PP_DEFINE_FSM_CH2_3
#define UNCURSED_PP_DEFINE_FSM_CH2_5(e) UNCURSED_PP_DEFINE_FSM_AP1 e UNCURSED_PP_DEFINE_FSM_CH2_4
#define UNCURSED_PP_DEFINE_FSM_CH2_6(e) UNCURSED_PP_DEFINE_FSM_AP1 e UNCURSED_PP_DEFINE_FSM_CH2_5
#define UNCURSED_PP_DEFINE_FSM_CH2_7(e) UNCURSED_PP_DEFINE_FSM_AP1 e UNCURSED_PP_DEFINE_FSM_CH2_6
#define UNCURSED_PP_DEFINE_FSM_CH2_8(e) UNCURSED_PP_DEFINE_FSM_AP1 e UNCURSED_PP_DEFINE_FSM_CH2_7
#define UNCURSED_PP_DEFINE_FSM_CH2_9(e) UNCURSED_PP_DEFINE_FSM_AP1 e UNCURSED_PP_DEFINE_FSM_CH2_8
#define UNCURSED_PP_DEFINE_FSM_CH2_10(e) UNCURSED_PP_DEFINE_FSM_AP1 e UNCURSED_PP_DEFINE_FSM_CH2_9
#define UNCURSED_PP_DEFINE_FSM_CH2_11(e) UNCURSED_PP_DEFINE_FSM_AP1 e UNCURSED_PP_DEFINE_FSM_CH2_10
#define UNCURSED_PP_DEFINE_FSM_CH2_12(e) UNCURSED_PP_DEFINE_FSM_AP1 e UNCURSED_PP_DEFINE_FSM_CH2_11
#define UNCURSED_PP_DEFINE_FSM_CH2_13(e) UNCURSED_PP_DEFINE_FSM_AP1 e UNCURSED_PP_DEFINE_FSM_CH2_12
#define UNCURSED_PP_DEFINE_FSM_CH2_14(e) UNCURSED_PP_DEFINE_FSM_AP1 e UNCURSED_PP_DEFINE_FSM_CH2_13
#define UNCURSED_PP_DEFINE_FSM_CH2_15(e) UNCURSED_PP_DEFINE_FSM_AP1 e UNCURSED_PP_DEFINE_FSM_CH2_14
#define UNCURSED_PP_DEFINE_FSM_CH2_16(e) UNCURSED_PP_DEFINE_FSM_AP1 e UNCURSED_PP_DEFINE_FSM_CH2_15
#define UNCURSED_PP_DEFINE_FSM_SMALL1(seq) BOOST_PP_CAT(UNCURSED_PP_DEFINE_FSM_CH1_, BOOST_PP_SEQ_SIZE(seq)) seq
#define UNCURSED_PP_DEFINE_FSM_PICK1(n) BOOST_PP_IIF(BOOST_PP_CAT(UNCURSED_PP_LE16_, n), UNCURSED_PP_DEFINE_FSM_SMALL1, UNCURSED_PP_DEFINE_FSM_BIG1)
#define UNCURSED_PP_DEFINE_FSM_BIG1(seq) BOOST_PP_SEQ_FOR_EACH(UNCURSED_PP_DEFINE_FSM_EACH1, ~, seq)
#define UNCURSED_PP_DEFINE_FSM_SMALL2(seq) BOOST_PP_CAT(UNCURSED_PP_DEFINE_FSM_CH2_, BOOST_PP_SEQ_SIZE(seq)) seq
#define UNCURSED_PP_DEFINE_FSM_PICK2(n) BOOST_PP_IIF(BOOST_PP_CAT(UNCURSED_PP_LE16_, n), UNCURSED_PP_DEFINE_FSM_SMALL2, UNCURSED_PP_DEFINE_FSM_BIG2)
#define UNCURSED_PP_DEFINE_FSM_BIG2(seq) BOOST_PP_SEQ_FOR_EACH(UNCURSED_PP_DEFINE_FSM_EACH2, ~, seq)
#define DEFINE_FSM(fsm, states, transitions) \
    enum BOOST_PP_CAT(fsm, _state) { \
    UNCURSED_PP_DEFINE_FSM_PICK1(BOOST_PP_SEQ_SIZE(states))(states) \
    }; \
    static int BOOST_PP_CAT(fsm, _step)(int s, int ev) { \
    UNCURSED_PP_DEFINE_FSM_PICK2(BOOST_PP_SEQ_SIZE(transitions))(transitions) \
    return s; \
    }

/* #?  DEFINE_FSM(door, (CLOSED)(OPEN), ((CLOSED, EV_OPEN, OPEN))((OPEN, EV_CLOSE, CLOSED)))
 * #=>     enum door_state {
 * #=>       CLOSED,
 * #=>       OPEN,
 * #=>     };
 * #=>     static int door_step(int s, int ev) {
 * #=>       if (s == CLOSED && ev == EV_OPEN) return OPEN;
 * #=>       if (s == OPEN && ev == EV_CLOSE) return CLOSED;
 * #=>       return s;
 * #=>     }
 */
