/* Generated by uncursed-pp from 00-readme-chains.uncursed — do not edit. */
#pragma once

#include <boost/preprocessor/cat.hpp>
#include <boost/preprocessor/control/iif.hpp>
#include <boost/preprocessor/seq/for_each.hpp>
#include <boost/preprocessor/seq/size.hpp>
#include <boost/preprocessor/tuple/elem.hpp>
#include <boost/preprocessor/variadic/to_seq.hpp>
#include "uncursed_pp_runtime.h"

/* # The SAME macro as 00-readme.uncursed, with no pragma: default codegen.
 * # Compare the two committed headers side by side — 00-readme.h is the
 * # compact three-define FOR_EACH form the README shows; this one carries
 * # the consumption-chain family (CH1_1..16 + SMALL/BIG/PICK dispatch),
 * # which preprocesses ~25x cheaper per call site at the cost of a longer
 * # header (see docs/loop-chains.md). Same call sites, same expansions:
 * # the specs below are identical to 00-readme's.
 */

/* uncursed-pp source:
 * @macro DECLARE_FIELDS($fields: variadic<tuple<$type, $name>>)
 * @for ($type, $name) in $fields
 *   {{$type}} {{$name}};
 * @end
 * @endmacro
 */
#define UNCURSED_PP_DECLARE_FIELDS_AP1(type, name) type name;
#define UNCURSED_PP_DECLARE_FIELDS_EACH1(r, d, e) UNCURSED_PP_DECLARE_FIELDS_AP1 e
#define UNCURSED_PP_DECLARE_FIELDS_CH1_1(e) UNCURSED_PP_DECLARE_FIELDS_AP1 e
#define UNCURSED_PP_DECLARE_FIELDS_CH1_2(e) UNCURSED_PP_DECLARE_FIELDS_AP1 e UNCURSED_PP_DECLARE_FIELDS_CH1_1
#define UNCURSED_PP_DECLARE_FIELDS_CH1_3(e) UNCURSED_PP_DECLARE_FIELDS_AP1 e UNCURSED_PP_DECLARE_FIELDS_CH1_2
#define UNCURSED_PP_DECLARE_FIELDS_CH1_4(e) UNCURSED_PP_DECLARE_FIELDS_AP1 e UNCURSED_PP_DECLARE_FIELDS_CH1_3
#define UNCURSED_PP_DECLARE_FIELDS_CH1_5(e) UNCURSED_PP_DECLARE_FIELDS_AP1 e UNCURSED_PP_DECLARE_FIELDS_CH1_4
#define UNCURSED_PP_DECLARE_FIELDS_CH1_6(e) UNCURSED_PP_DECLARE_FIELDS_AP1 e UNCURSED_PP_DECLARE_FIELDS_CH1_5
#define UNCURSED_PP_DECLARE_FIELDS_CH1_7(e) UNCURSED_PP_DECLARE_FIELDS_AP1 e UNCURSED_PP_DECLARE_FIELDS_CH1_6
#define UNCURSED_PP_DECLARE_FIELDS_CH1_8(e) UNCURSED_PP_DECLARE_FIELDS_AP1 e UNCURSED_PP_DECLARE_FIELDS_CH1_7
#define UNCURSED_PP_DECLARE_FIELDS_CH1_9(e) UNCURSED_PP_DECLARE_FIELDS_AP1 e UNCURSED_PP_DECLARE_FIELDS_CH1_8
#define UNCURSED_PP_DECLARE_FIELDS_CH1_10(e) UNCURSED_PP_DECLARE_FIELDS_AP1 e UNCURSED_PP_DECLARE_FIELDS_CH1_9
#define UNCURSED_PP_DECLARE_FIELDS_CH1_11(e) UNCURSED_PP_DECLARE_FIELDS_AP1 e UNCURSED_PP_DECLARE_FIELDS_CH1_10
#define UNCURSED_PP_DECLARE_FIELDS_CH1_12(e) UNCURSED_PP_DECLARE_FIELDS_AP1 e UNCURSED_PP_DECLARE_FIELDS_CH1_11
#define UNCURSED_PP_DECLARE_FIELDS_CH1_13(e) UNCURSED_PP_DECLARE_FIELDS_AP1 e UNCURSED_PP_DECLARE_FIELDS_CH1_12
#define UNCURSED_PP_DECLARE_FIELDS_CH1_14(e) UNCURSED_PP_DECLARE_FIELDS_AP1 e UNCURSED_PP_DECLARE_FIELDS_CH1_13
#define UNCURSED_PP_DECLARE_FIELDS_CH1_15(e) UNCURSED_PP_DECLARE_FIELDS_AP1 e UNCURSED_PP_DECLARE_FIELDS_CH1_14
#define UNCURSED_PP_DECLARE_FIELDS_CH1_16(e) UNCURSED_PP_DECLARE_FIELDS_AP1 e UNCURSED_PP_DECLARE_FIELDS_CH1_15
#define UNCURSED_PP_DECLARE_FIELDS_SMALL1(seq) BOOST_PP_CAT(UNCURSED_PP_DECLARE_FIELDS_CH1_, BOOST_PP_SEQ_SIZE(seq)) seq
#define UNCURSED_PP_DECLARE_FIELDS_PICK1(n) BOOST_PP_IIF(BOOST_PP_CAT(UNCURSED_PP_LE16_, n), UNCURSED_PP_DECLARE_FIELDS_SMALL1, UNCURSED_PP_DECLARE_FIELDS_BIG1)
#define UNCURSED_PP_DECLARE_FIELDS_BIG1(seq) BOOST_PP_SEQ_FOR_EACH(UNCURSED_PP_DECLARE_FIELDS_EACH1, ~, seq)
#define DECLARE_FIELDS(...) UNCURSED_PP_DECLARE_FIELDS_PICK1(BOOST_PP_SEQ_SIZE(BOOST_PP_VARIADIC_TO_SEQ(__VA_ARGS__)))(BOOST_PP_VARIADIC_TO_SEQ(__VA_ARGS__))

/* # ── invocation specs (verified through cc -E by the spec harness) ──
 * #?  DECLARE_FIELDS((int, x), (float, y))
 * #=>     int x; float y;
 */

/* #?  DECLARE_FIELDS((char *, name))
 * #=>     char * name;
 */
