/* Generated by uncursed-pp from 00-readme.uncursed — do not edit. */
#pragma once

#include <boost/preprocessor/seq/for_each.hpp>
#include <boost/preprocessor/tuple/elem.hpp>
#include <boost/preprocessor/variadic/to_seq.hpp>

/* # The front-page example from README.md, as a real, spec-checked source
 * # file — if the README ever drifts from what the compiler does, this file's
 * # specs fail the suite.
 * #
 * # `variadic<tuple<type, name>>` gives single-paren call sites; loop chains
 * # are off so the generated header stays three defines (drop the pragma for
 * # the ~25x-cheaper chain codegen; see docs/optimization.md).
 */

/* # demo only: skip the (faster, but longer) loop-chain codegen */

/* uncursed-pp source:
 * @macro DECLARE_FIELDS(fields: variadic<tuple<type, name>>)
 * @for (type, name) in fields
 *   {{type}} {{name}};
 * @end
 * @endmacro
 */
#define UNCURSED_PP_DECLARE_FIELDS_AP1(type, name) type name;
#define UNCURSED_PP_DECLARE_FIELDS_EACH1(r, d, e) UNCURSED_PP_DECLARE_FIELDS_AP1 e
#define DECLARE_FIELDS(...) BOOST_PP_SEQ_FOR_EACH(UNCURSED_PP_DECLARE_FIELDS_EACH1, ~, BOOST_PP_VARIADIC_TO_SEQ(__VA_ARGS__))

/* # ── invocation specs (verified through cc -E by the spec harness) ──
 * #?  DECLARE_FIELDS((int, x), (float, y))
 * #=>     int x; float y;
 */

/* #?  DECLARE_FIELDS((char *, name))
 * #=>     char * name;
 */
