/* Generated by uncursed-pp from attr.uncursed — do not edit. */
#pragma once

/* uncursed-pp source:
 * # Empty tail default: `$quals = ` (nothing after `=`) substitutes as
 * # zero tokens when the argument is omitted. Positional params have no
 * # bare shorthand - `$quals` alone means required.
 * @macro ATTR($name, $quals = )
 * {{$quals}} int {{$name}};
 * @endmacro
 */
#define UNCURSED_PP_ATTR_1(name) UNCURSED_PP_ATTR_2(name, )
#define UNCURSED_PP_ATTR_2(name, quals) quals int name;
#define UNCURSED_PP_ATTR_SIZE(...) UNCURSED_PP_ATTR_SIZE_I(__VA_ARGS__, 2, 1,)
#define UNCURSED_PP_ATTR_SIZE_I(e0, e1, size, ...) size
#define UNCURSED_PP_ATTR_DISPATCH(n) UNCURSED_PP_ATTR_DISPATCH_I(n)
#define UNCURSED_PP_ATTR_DISPATCH_I(n) UNCURSED_PP_ATTR_ ## n
#define ATTR(...) UNCURSED_PP_ATTR_DISPATCH(UNCURSED_PP_ATTR_SIZE(__VA_ARGS__))(__VA_ARGS__)

/* # ── invocation specs (verified through cc -E by test_e2e_specs) ──
 * #?  ATTR(x)
 * #=>     int x;
 */

/* #?  ATTR(y, static)
 * #=>     static int y;
 */

/* # edge: explicit empty trailing argument - selects the 2-arg overload
 * # with an empty value (same tokens as the default here, different route)
 * #?  ATTR(z,)
 * #=>     int z;
 */
