/* Generated by cursedpp from log.cursed — do not edit. */
#pragma once

/* cursedpp source:
 * # Tail defaults: arity dispatch at C compile time.
 * #   LOG(m) / LOG(m, WARN) / LOG(m, WARN, stdout)
 * macro LOG(msg, level = INFO, out = stderr)
 * fprintf({{out}}, "[" #{{level}} "] %s\n", {{msg}});
 * end
 */
#define CURSEDPP_LOG_1(msg) CURSEDPP_LOG_3(msg, INFO, stderr)
#define CURSEDPP_LOG_2(msg, level) CURSEDPP_LOG_3(msg, level, stderr)
#define CURSEDPP_LOG_3(msg, level, out) fprintf(out, "[" #level "] %s\n", msg);
#define CURSEDPP_LOG_SIZE(...) CURSEDPP_LOG_SIZE_I(__VA_ARGS__, 3, 2, 1,)
#define CURSEDPP_LOG_SIZE_I(e0, e1, e2, size, ...) size
#define CURSEDPP_LOG_DISPATCH(n) CURSEDPP_LOG_DISPATCH_I(n)
#define CURSEDPP_LOG_DISPATCH_I(n) CURSEDPP_LOG_ ## n
#define LOG(...) CURSEDPP_LOG_DISPATCH(CURSEDPP_LOG_SIZE(__VA_ARGS__))(__VA_ARGS__)
