/* Generated by uncursed-pp from log.uncursed — do not edit. */
#pragma once

/* uncursed-pp source:
 * # Tail defaults: arity dispatch at C compile time.
 * #   LOG(m) / LOG(m, WARN) / LOG(m, WARN, stdout)
 * @macro LOG($msg, $level = INFO, $out = stderr)
 * fprintf({{$out}}, "[" #{{$level}} "] %s\n", {{$msg}});
 * @endmacro
 */
#define UNCURSED_PP_LOG_1(msg) UNCURSED_PP_LOG_3(msg, INFO, stderr)
#define UNCURSED_PP_LOG_2(msg, level) UNCURSED_PP_LOG_3(msg, level, stderr)
#define UNCURSED_PP_LOG_3(msg, level, out) fprintf(out, "[" #level "] %s\n", msg);
#define UNCURSED_PP_LOG_SIZE(...) UNCURSED_PP_LOG_SIZE_I(__VA_ARGS__, 3, 2, 1,)
#define UNCURSED_PP_LOG_SIZE_I(e0, e1, e2, size, ...) size
#define UNCURSED_PP_LOG_DISPATCH(n) UNCURSED_PP_LOG_DISPATCH_I(n)
#define UNCURSED_PP_LOG_DISPATCH_I(n) UNCURSED_PP_LOG_ ## n
#define LOG(...) UNCURSED_PP_LOG_DISPATCH(UNCURSED_PP_LOG_SIZE(__VA_ARGS__))(__VA_ARGS__)

/* # ── invocation specs (verified through cc -E by test_e2e_specs) ──
 * #?  LOG(m)
 * #=>     fprintf(stderr, "[" "INFO" "] %s\n", m);
 */

/* #?  LOG(m, WARN)
 * #=>     fprintf(stderr, "[" "WARN" "] %s\n", m);
 */

/* #?  LOG(m, WARN, stdout)
 * #=>     fprintf(stdout, "[" "WARN" "] %s\n", m);
 */

/* # edge: parenthesized comma-containing message counts as ONE argument
 * #?  LOG((a, b))
 * #=>     fprintf(stderr, "[" "INFO" "] %s\n", (a, b));
 */

/* # edge: string-literal argument passes through
 * #?  LOG("hi there", ERROR)
 * #=>     fprintf(stderr, "[" "ERROR" "] %s\n", "hi there");
 */

/* # edge: an explicit empty trailing argument still counts in the arity
 * # scan - level gets an empty value (stringizing to ""), NOT its default
 * #?  LOG(m,)
 * #=>     fprintf(stderr, "[" "" "] %s\n", m);
 */
