/* Generated by uncursed-pp from optional_fields.uncursed — do not edit. */
#pragma once

#include <boost/preprocessor/cat.hpp>
#include <boost/preprocessor/control/iif.hpp>
#include <boost/preprocessor/seq/for_each.hpp>
#include <boost/preprocessor/seq/size.hpp>
#include <boost/preprocessor/tuple/elem.hpp>
#include <boost/preprocessor/tuple/size.hpp>
#include "uncursed_pp_runtime.h"

/* uncursed-pp source:
 * # Optional trailing tuple fields. `$f = def` fills a default when the
 * # call site omits the field; `$f?` is truly absent when omitted -
 * # has($t.$f) probes presence, and accessing an absent field yields
 * # zero tokens. Normalization is size-dispatched at C compile time.
 * @macro FIELD($f: tuple<$name, $type = int, $qual = >)
 * {{$f.$qual}} {{$f.$type}} {{$f.$name}};
 * @endmacro
 */
#define UNCURSED_PP_FIELD_NF1(t) UNCURSED_PP_FIELD_NF1_D(BOOST_PP_TUPLE_SIZE(t), t)
#define UNCURSED_PP_FIELD_NF1_D(...) UNCURSED_PP_FIELD_NF1_I(__VA_ARGS__)
#define UNCURSED_PP_FIELD_NF1_I(n, t) UNCURSED_PP_FIELD_NF1_ ## n t
#define UNCURSED_PP_FIELD_NF1_1(f0) (f0, int, )
#define UNCURSED_PP_FIELD_NF1_2(f0, f1) (f0, f1, )
#define UNCURSED_PP_FIELD_NF1_3(f0, f1, f2) (f0, f1, f2)
#define UNCURSED_PP_FIELD_BODY1(name, type, qual) qual type name;
#define UNCURSED_PP_FIELD_BODY1_D(...) UNCURSED_PP_FIELD_BODY1(__VA_ARGS__)
#define UNCURSED_PP_FIELD_BODY1_P(f) UNCURSED_PP_FIELD_BODY1_D(UNCURSED_PP_KW_SPREAD f)
#define FIELD(f) UNCURSED_PP_FIELD_BODY1_P(UNCURSED_PP_FIELD_NF1(f))

/* uncursed-pp source:
 * @macro DECL($t: tuple<$name, $init?>)
 * @if has($t.$init)
 * int {{$t.$name}} = {{$t.$init}};
 * @else
 * int {{$t.$name}};
 * @end
 * @endmacro
 */
#define UNCURSED_PP_DECL_THEN1(t) int BOOST_PP_TUPLE_ELEM(0, t) = BOOST_PP_TUPLE_ELEM(1, t);
#define UNCURSED_PP_DECL_ELSE1(t) int BOOST_PP_TUPLE_ELEM(0, t);
#define UNCURSED_PP_DECL_NF1(t) UNCURSED_PP_DECL_NF1_D(BOOST_PP_TUPLE_SIZE(t), t)
#define UNCURSED_PP_DECL_NF1_D(...) UNCURSED_PP_DECL_NF1_I(__VA_ARGS__)
#define UNCURSED_PP_DECL_NF1_I(n, t) UNCURSED_PP_DECL_NF1_ ## n t
#define UNCURSED_PP_DECL_NF1_1(f0) (f0, , 1)
#define UNCURSED_PP_DECL_NF1_2(f0, f1) (f0, f1, 2)
#define UNCURSED_PP_DECL_HP1_1 0
#define UNCURSED_PP_DECL_HP1_2 1
#define DECL(t) BOOST_PP_IIF(BOOST_PP_CAT(UNCURSED_PP_DECL_HP1_, BOOST_PP_TUPLE_ELEM(2, UNCURSED_PP_DECL_NF1(t))), UNCURSED_PP_DECL_THEN1, UNCURSED_PP_DECL_ELSE1)(UNCURSED_PP_DECL_NF1(t))

/* uncursed-pp source:
 * @macro EDGE($t: tuple<$a, $b, $c = 1>)
 * edge({{$t.$a}}, {{$t.$b}}, {{$t.$c}});
 * @endmacro
 */
#define UNCURSED_PP_EDGE_NF1(t) UNCURSED_PP_EDGE_NF1_D(BOOST_PP_TUPLE_SIZE(t), t)
#define UNCURSED_PP_EDGE_NF1_D(...) UNCURSED_PP_EDGE_NF1_I(__VA_ARGS__)
#define UNCURSED_PP_EDGE_NF1_I(n, t) UNCURSED_PP_EDGE_NF1_ ## n t
#define UNCURSED_PP_EDGE_ERROR_TOO_FEW_TUPLE_FIELDS(need, got)
#define UNCURSED_PP_EDGE_NF1_1(...) UNCURSED_PP_EDGE_ERROR_TOO_FEW_TUPLE_FIELDS(~)
#define UNCURSED_PP_EDGE_NF1_2(f0, f1) (f0, f1, 1)
#define UNCURSED_PP_EDGE_NF1_3(f0, f1, f2) (f0, f1, f2)
#define UNCURSED_PP_EDGE_BODY1(a, b, c) edge(a, b, c);
#define UNCURSED_PP_EDGE_BODY1_D(...) UNCURSED_PP_EDGE_BODY1(__VA_ARGS__)
#define UNCURSED_PP_EDGE_BODY1_P(t) UNCURSED_PP_EDGE_BODY1_D(UNCURSED_PP_KW_SPREAD t)
#define EDGE(t) UNCURSED_PP_EDGE_BODY1_P(UNCURSED_PP_EDGE_NF1(t))

/* uncursed-pp source:
 * # composition: optional-field tuples as seq elements, unpacked in loops
 * @macro ROWS($fs: seq<tuple<$name, $type = int>>)
 * @for ($name, $type) in $fs
 * {{$type}} {{$name}};
 * @end
 * @endmacro
 */
#define UNCURSED_PP_ROWS_AP1(name, type) type name;
#define UNCURSED_PP_ROWS_AP1_N(t) UNCURSED_PP_ROWS_AP1 t
#define UNCURSED_PP_ROWS_EACH1(r, d, e) UNCURSED_PP_ROWS_AP1_N(UNCURSED_PP_ROWS_NF1(e))
#define UNCURSED_PP_ROWS_CH1_1(e) UNCURSED_PP_ROWS_AP1_N(UNCURSED_PP_ROWS_NF1(e))
#define UNCURSED_PP_ROWS_CH1_2(e) UNCURSED_PP_ROWS_AP1_N(UNCURSED_PP_ROWS_NF1(e)) UNCURSED_PP_ROWS_CH1_1
#define UNCURSED_PP_ROWS_CH1_3(e) UNCURSED_PP_ROWS_AP1_N(UNCURSED_PP_ROWS_NF1(e)) UNCURSED_PP_ROWS_CH1_2
#define UNCURSED_PP_ROWS_CH1_4(e) UNCURSED_PP_ROWS_AP1_N(UNCURSED_PP_ROWS_NF1(e)) UNCURSED_PP_ROWS_CH1_3
#define UNCURSED_PP_ROWS_CH1_5(e) UNCURSED_PP_ROWS_AP1_N(UNCURSED_PP_ROWS_NF1(e)) UNCURSED_PP_ROWS_CH1_4
#define UNCURSED_PP_ROWS_CH1_6(e) UNCURSED_PP_ROWS_AP1_N(UNCURSED_PP_ROWS_NF1(e)) UNCURSED_PP_ROWS_CH1_5
#define UNCURSED_PP_ROWS_CH1_7(e) UNCURSED_PP_ROWS_AP1_N(UNCURSED_PP_ROWS_NF1(e)) UNCURSED_PP_ROWS_CH1_6
#define UNCURSED_PP_ROWS_CH1_8(e) UNCURSED_PP_ROWS_AP1_N(UNCURSED_PP_ROWS_NF1(e)) UNCURSED_PP_ROWS_CH1_7
#define UNCURSED_PP_ROWS_CH1_9(e) UNCURSED_PP_ROWS_AP1_N(UNCURSED_PP_ROWS_NF1(e)) UNCURSED_PP_ROWS_CH1_8
#define UNCURSED_PP_ROWS_CH1_10(e) UNCURSED_PP_ROWS_AP1_N(UNCURSED_PP_ROWS_NF1(e)) UNCURSED_PP_ROWS_CH1_9
#define UNCURSED_PP_ROWS_CH1_11(e) UNCURSED_PP_ROWS_AP1_N(UNCURSED_PP_ROWS_NF1(e)) UNCURSED_PP_ROWS_CH1_10
#define UNCURSED_PP_ROWS_CH1_12(e) UNCURSED_PP_ROWS_AP1_N(UNCURSED_PP_ROWS_NF1(e)) UNCURSED_PP_ROWS_CH1_11
#define UNCURSED_PP_ROWS_CH1_13(e) UNCURSED_PP_ROWS_AP1_N(UNCURSED_PP_ROWS_NF1(e)) UNCURSED_PP_ROWS_CH1_12
#define UNCURSED_PP_ROWS_CH1_14(e) UNCURSED_PP_ROWS_AP1_N(UNCURSED_PP_ROWS_NF1(e)) UNCURSED_PP_ROWS_CH1_13
#define UNCURSED_PP_ROWS_CH1_15(e) UNCURSED_PP_ROWS_AP1_N(UNCURSED_PP_ROWS_NF1(e)) UNCURSED_PP_ROWS_CH1_14
#define UNCURSED_PP_ROWS_CH1_16(e) UNCURSED_PP_ROWS_AP1_N(UNCURSED_PP_ROWS_NF1(e)) UNCURSED_PP_ROWS_CH1_15
#define UNCURSED_PP_ROWS_NF1(t) UNCURSED_PP_ROWS_NF1_D(BOOST_PP_TUPLE_SIZE(t), t)
#define UNCURSED_PP_ROWS_NF1_D(...) UNCURSED_PP_ROWS_NF1_I(__VA_ARGS__)
#define UNCURSED_PP_ROWS_NF1_I(n, t) UNCURSED_PP_ROWS_NF1_ ## n t
#define UNCURSED_PP_ROWS_NF1_1(f0) (f0, int)
#define UNCURSED_PP_ROWS_NF1_2(f0, f1) (f0, f1)
#define UNCURSED_PP_ROWS_SMALL1(seq) BOOST_PP_CAT(UNCURSED_PP_ROWS_CH1_, BOOST_PP_SEQ_SIZE(seq)) seq
#define UNCURSED_PP_ROWS_PICK1(n) BOOST_PP_IIF(BOOST_PP_CAT(UNCURSED_PP_LE16_, n), UNCURSED_PP_ROWS_SMALL1, UNCURSED_PP_ROWS_BIG1)
#define UNCURSED_PP_ROWS_BIG1(seq) BOOST_PP_SEQ_FOR_EACH(UNCURSED_PP_ROWS_EACH1, ~, seq)
#define ROWS(fs) UNCURSED_PP_ROWS_PICK1(BOOST_PP_SEQ_SIZE(fs))(fs)

/* # ── invocation specs (verified through cc -E by test_e2e_specs) ──
 * #?  FIELD((x))
 * #=>     int x;
 */

/* #?  FIELD((y, float))
 * #=>     float y;
 */

/* #?  FIELD((z, char, const))
 * #=>     const char z;
 */

/* #?  DECL((a, 42))
 * #=>     int a = 42;
 */

/* #?  DECL((b))
 * #=>     int b;
 */

/* #?  ROWS(((a))((b, float)))
 * #=>     int a; float b;
 */

/* #?  EDGE((p, q))
 * #=>     edge(p, q, 1);
 */

/* # fewer fields than required is a hard preprocessor error, never
 * # silent garbage
 * #?! EDGE((only))
 */
