/* Generated by uncursed-pp from required.uncursed — do not edit. */
#pragma once

#include <boost/preprocessor/cat.hpp>

/* uncursed-pp source:
 * # 'required named': the keyword must appear at the call site or the
 * # program does not compile. Omission fails one of two ways:
 * #   - too few arguments: hard preprocessor error via a deliberately
 * #     mismatched function-like macro (ERROR_MISSING_REQUIRED_KEYWORD);
 * #   - masked by a repeated keyword: the slot's poison identifier
 * #     lands in the output and fails C compilation, naming the keyword.
 * @macro CONNECT($tag, required named $HOST, named $PORT = 80)
 * connect({{$tag}}, {{$HOST}}, {{$PORT}});
 * @endmacro
 */
#define UNCURSED_PP_CONNECT_SET_HOST(v) 0, v
#define UNCURSED_PP_CONNECT_SET_PORT(v) 1, v
#define UNCURSED_PP_CONNECT_STEP1(e, ...) UNCURSED_PP_CONNECT_STEP_D(BOOST_PP_CAT(UNCURSED_PP_CONNECT_SET_, e), __VA_ARGS__)
#define UNCURSED_PP_CONNECT_STEP_D(...) UNCURSED_PP_CONNECT_STEP_I(__VA_ARGS__)
#define UNCURSED_PP_CONNECT_STEP_I(i, v, ...) UNCURSED_PP_CONNECT_PUT_ ## i(v, __VA_ARGS__)
#define UNCURSED_PP_CONNECT_PUT_0(v, p0, p1) v, p1
#define UNCURSED_PP_CONNECT_PUT_1(v, p0, p1) p0, v
#define UNCURSED_PP_CONNECT_BODY(tag, HOST, PORT) connect(tag, HOST, PORT);
#define UNCURSED_PP_CONNECT_BODY_D(...) UNCURSED_PP_CONNECT_BODY(__VA_ARGS__)
#define UNCURSED_PP_CONNECT_ERROR_MISSING_REQUIRED_KEYWORD(kw, missing)
#define UNCURSED_PP_CONNECT_1(...) UNCURSED_PP_CONNECT_ERROR_MISSING_REQUIRED_KEYWORD(~)
#define UNCURSED_PP_CONNECT_2(tag, e1) UNCURSED_PP_CONNECT_BODY_D(tag, UNCURSED_PP_CONNECT_STEP1(e1, UNCURSED_PP_CONNECT_MISSING_REQUIRED_KEYWORD_HOST, 80))
#define UNCURSED_PP_CONNECT_3(tag, e1, e2) UNCURSED_PP_CONNECT_BODY_D(tag, UNCURSED_PP_CONNECT_STEP1(e2, UNCURSED_PP_CONNECT_STEP1(e1, UNCURSED_PP_CONNECT_MISSING_REQUIRED_KEYWORD_HOST, 80)))
#define UNCURSED_PP_CONNECT_SIZE(...) UNCURSED_PP_CONNECT_SIZE_I(__VA_ARGS__, 3, 2, 1,)
#define UNCURSED_PP_CONNECT_SIZE_I(e0, e1, e2, size, ...) size
#define UNCURSED_PP_CONNECT_DISPATCH(n) UNCURSED_PP_CONNECT_DISPATCH_I(n)
#define UNCURSED_PP_CONNECT_DISPATCH_I(n) UNCURSED_PP_CONNECT_ ## n
#define CONNECT(...) UNCURSED_PP_CONNECT_DISPATCH(UNCURSED_PP_CONNECT_SIZE(__VA_ARGS__))(__VA_ARGS__)

/* # ── invocation specs (verified through cc -E by test_e2e_specs) ──
 * #?  CONNECT(t, HOST("example.org"))
 * #=>     connect(t, "example.org", 80);
 */

/* # keyword order stays free:
 * #?  CONNECT(t, PORT(443), HOST(h))
 * #=>     connect(t, h, 443);
 */

/* # 'required' means the KEYWORD must appear - an empty value satisfies it
 * #?  CONNECT(t, HOST())
 * #=>     connect(t, , 80);
 */

/* # edge: right count, wrong keyword - past the arity floor, but the
 * # un-set slot's poison identifier reaches the output (a C compile
 * # error naming HOST)
 * #?  CONNECT(t, PORT(443))
 * #=>     connect(t, UNCURSED_PP_CONNECT_MISSING_REQUIRED_KEYWORD_HOST, 443);
 */

/* # edge: a repeated keyword masks the count the same way
 * #?  CONNECT(t, PORT(1), PORT(2))
 * #=>     connect(t, UNCURSED_PP_CONNECT_MISSING_REQUIRED_KEYWORD_HOST, 2);
 */

/* # too few arguments to possibly contain HOST: hard preprocessor error
 * #?! CONNECT(t)
 */
