/* Generated by cursedpp from vec.cursed — do not edit. */
#pragma once

#include <boost/preprocessor/cat.hpp>
#include <boost/preprocessor/facilities/overload.hpp>
#include <boost/preprocessor/seq/for_each.hpp>
#include <boost/preprocessor/tuple/elem.hpp>

/* cursedpp source:
 * # Named args composed with a loop: BODY params referenced inside the
 * # loop ride the d slot as a tuple.
 * macro VEC(name, items: seq<token>, named PREFIX = v)
 * @for i in items
 * {{concat(PREFIX, i)}} {{name}};
 * @end
 * end
 */
#define CURSEDPP_VEC_EACH1(r, d, e) BOOST_PP_CAT(BOOST_PP_TUPLE_ELEM(0, d), e) BOOST_PP_TUPLE_ELEM(1, d);
#define CURSEDPP_VEC_SET_PREFIX(v) 0, v
#define CURSEDPP_VEC_STEP1(e, ...) CURSEDPP_VEC_STEP_D(BOOST_PP_CAT(CURSEDPP_VEC_SET_, e), __VA_ARGS__)
#define CURSEDPP_VEC_STEP_D(...) CURSEDPP_VEC_STEP_I(__VA_ARGS__)
#define CURSEDPP_VEC_STEP_I(i, v, ...) CURSEDPP_VEC_PUT_ ## i(v, __VA_ARGS__)
#define CURSEDPP_VEC_PUT_0(v, p0) v
#define CURSEDPP_VEC_BODY(name, items, PREFIX) BOOST_PP_SEQ_FOR_EACH(CURSEDPP_VEC_EACH1, (PREFIX, name), items)
#define CURSEDPP_VEC_BODY_D(...) CURSEDPP_VEC_BODY(__VA_ARGS__)
#define CURSEDPP_VEC_2(name, items) CURSEDPP_VEC_BODY(name, items, v)
#define CURSEDPP_VEC_3(name, items, e1) CURSEDPP_VEC_BODY_D(name, items, CURSEDPP_VEC_STEP1(e1, v))
#define VEC(...) BOOST_PP_OVERLOAD(CURSEDPP_VEC_, __VA_ARGS__)(__VA_ARGS__)
