/* Generated by uncursed-pp from widget.uncursed — do not edit. */
#pragma once

#include <boost/preprocessor/cat.hpp>
#include "uncursed_pp_runtime.h"

/* uncursed-pp source:
 * # Named arguments: KEYWORD(value) at the call site, any order, any subset.
 * #   MAKE_WIDGET(w1)                          → struct widget w1 = { 100, 50, };
 * #   MAKE_WIDGET(w2, HEIGHT(80))              → struct widget w2 = { 100, 80, };
 * #   MAKE_WIDGET(w3, FLAGS(BOLD), WIDTH(20))  → struct widget w3 = { 20, 50, BOLD };
 * @macro MAKE_WIDGET(name, named WIDTH = 100, named HEIGHT = 50, named FLAGS = )
 * struct widget {{name}} = { {{WIDTH}}, {{HEIGHT}}, {{FLAGS}} };
 * @endmacro
 */
#define UNCURSED_PP_MAKE_WIDGET_SET_WIDTH(v) 0, v
#define UNCURSED_PP_MAKE_WIDGET_SET_HEIGHT(v) 1, v
#define UNCURSED_PP_MAKE_WIDGET_SET_FLAGS(v) 2, v
#define UNCURSED_PP_MAKE_WIDGET_STEP1(e, ...) UNCURSED_PP_MAKE_WIDGET_STEP_D(BOOST_PP_CAT(UNCURSED_PP_MAKE_WIDGET_SET_, e), __VA_ARGS__)
#define UNCURSED_PP_MAKE_WIDGET_STEP_D(...) UNCURSED_PP_MAKE_WIDGET_STEP_I(__VA_ARGS__)
#define UNCURSED_PP_MAKE_WIDGET_STEP_I(i, v, ...) UNCURSED_PP_MAKE_WIDGET_PUT_ ## i(v, __VA_ARGS__)
#define UNCURSED_PP_MAKE_WIDGET_PUT_0(v, p0, p1, p2) v, p1, p2
#define UNCURSED_PP_MAKE_WIDGET_PUT_1(v, p0, p1, p2) p0, v, p2
#define UNCURSED_PP_MAKE_WIDGET_PUT_2(v, p0, p1, p2) p0, p1, v
#define UNCURSED_PP_MAKE_WIDGET_BODY(name, WIDTH, HEIGHT, FLAGS) struct widget name = { WIDTH, HEIGHT, FLAGS };
#define UNCURSED_PP_MAKE_WIDGET_BODY_D(...) UNCURSED_PP_MAKE_WIDGET_BODY(__VA_ARGS__)
#define UNCURSED_PP_MAKE_WIDGET_1(name) UNCURSED_PP_MAKE_WIDGET_BODY(name, 100, 50, )
#define UNCURSED_PP_MAKE_WIDGET_2(name, e1) UNCURSED_PP_MAKE_WIDGET_BODY_D(name, UNCURSED_PP_MAKE_WIDGET_STEP1(e1, 100, 50, ))
#define UNCURSED_PP_MAKE_WIDGET_3(name, e1, e2) UNCURSED_PP_MAKE_WIDGET_BODY_D(name, UNCURSED_PP_MAKE_WIDGET_STEP1(e2, UNCURSED_PP_MAKE_WIDGET_STEP1(e1, 100, 50, )))
#define UNCURSED_PP_MAKE_WIDGET_4(name, e1, e2, e3) UNCURSED_PP_MAKE_WIDGET_BODY_D(name, UNCURSED_PP_MAKE_WIDGET_STEP1(e3, UNCURSED_PP_MAKE_WIDGET_STEP1(e2, UNCURSED_PP_MAKE_WIDGET_STEP1(e1, 100, 50, ))))
#define UNCURSED_PP_MAKE_WIDGET_SIZE(...) UNCURSED_PP_MAKE_WIDGET_SIZE_I(__VA_ARGS__, 4, 3, 2, 1,)
#define UNCURSED_PP_MAKE_WIDGET_SIZE_I(e0, e1, e2, e3, size, ...) size
#define UNCURSED_PP_MAKE_WIDGET_DISPATCH(n) UNCURSED_PP_MAKE_WIDGET_DISPATCH_I(n)
#define UNCURSED_PP_MAKE_WIDGET_DISPATCH_I(n) UNCURSED_PP_MAKE_WIDGET_ ## n
#define MAKE_WIDGET(...) UNCURSED_PP_MAKE_WIDGET_DISPATCH(UNCURSED_PP_MAKE_WIDGET_SIZE(__VA_ARGS__))(__VA_ARGS__)

/* uncursed-pp source:
 * # 'named variadic' keyword values may contain bare commas: the generated
 * # setter captures __VA_ARGS__ and re-wraps, and {{COLORS}} auto-unwraps.
 * @macro STYLE(name, named variadic COLORS = none)
 * unsigned {{name}}[] = { {{COLORS}} };
 * @endmacro
 */
#define UNCURSED_PP_STYLE_SET_COLORS(...) 0, (__VA_ARGS__)
#define UNCURSED_PP_STYLE_STEP1(e, ...) UNCURSED_PP_STYLE_STEP_D(BOOST_PP_CAT(UNCURSED_PP_STYLE_SET_, e), __VA_ARGS__)
#define UNCURSED_PP_STYLE_STEP_D(...) UNCURSED_PP_STYLE_STEP_I(__VA_ARGS__)
#define UNCURSED_PP_STYLE_STEP_I(i, v, ...) UNCURSED_PP_STYLE_PUT_ ## i(v, __VA_ARGS__)
#define UNCURSED_PP_STYLE_PUT_0(v, p0) v
#define UNCURSED_PP_STYLE_BODY(name, COLORS) unsigned name[] = { UNCURSED_PP_KW_SPREAD COLORS };
#define UNCURSED_PP_STYLE_BODY_D(...) UNCURSED_PP_STYLE_BODY(__VA_ARGS__)
#define UNCURSED_PP_STYLE_1(name) UNCURSED_PP_STYLE_BODY(name, (none))
#define UNCURSED_PP_STYLE_2(name, e1) UNCURSED_PP_STYLE_BODY_D(name, UNCURSED_PP_STYLE_STEP1(e1, (none)))
#define UNCURSED_PP_STYLE_SIZE(...) UNCURSED_PP_STYLE_SIZE_I(__VA_ARGS__, 2, 1,)
#define UNCURSED_PP_STYLE_SIZE_I(e0, e1, size, ...) size
#define UNCURSED_PP_STYLE_DISPATCH(n) UNCURSED_PP_STYLE_DISPATCH_I(n)
#define UNCURSED_PP_STYLE_DISPATCH_I(n) UNCURSED_PP_STYLE_ ## n
#define STYLE(...) UNCURSED_PP_STYLE_DISPATCH(UNCURSED_PP_STYLE_SIZE(__VA_ARGS__))(__VA_ARGS__)
