/* Generated by uncursed-pp from chain_off.uncursed — do not edit. */
#pragma once

#include <boost/preprocessor/seq/for_each.hpp>
#include <boost/preprocessor/tuple/elem.hpp>

/* uncursed-pp source:
 * @macro FIELDS_OFF(fields: seq<tuple<t, n>>)
 * @for (t, n) in fields
 *   {{t}} {{n}};
 * @end
 * @endmacro
 */
#define UNCURSED_PP_FIELDS_OFF_AP1(t, n) t n;
#define UNCURSED_PP_FIELDS_OFF_EACH1(r, d, e) UNCURSED_PP_FIELDS_OFF_AP1 e
#define FIELDS_OFF(fields) BOOST_PP_SEQ_FOR_EACH(UNCURSED_PP_FIELDS_OFF_EACH1, ~, fields)
