/* Generated by cursedpp from free_vars.cursed — do not edit. */
#pragma once

#include <boost/preprocessor/seq/for_each.hpp>
#include <boost/preprocessor/seq/size.hpp>
#include <boost/preprocessor/tuple/elem.hpp>

#define CURSEDPP_TAG_EACH1(r, d, e) d(e);
#define TAG(prefix, xs) BOOST_PP_SEQ_FOR_EACH(CURSEDPP_TAG_EACH1, prefix, xs)

#define CURSEDPP_BOTH_EACH1(r, d, e) g(BOOST_PP_TUPLE_ELEM(0, d), BOOST_PP_TUPLE_ELEM(1, d), e);
#define BOTH(a, b, xs) BOOST_PP_SEQ_FOR_EACH(CURSEDPP_BOTH_EACH1, (a, b), xs)

#define CURSEDPP_COUNTED_EACH1(r, d, e) h(e, BOOST_PP_SEQ_SIZE(d));
#define COUNTED(xs) BOOST_PP_SEQ_FOR_EACH(CURSEDPP_COUNTED_EACH1, xs, xs)
