/* Generated by uncursed-pp from free_vars.uncursed — do not edit. */
#pragma once

#include <boost/preprocessor/seq/for_each.hpp>
#include <boost/preprocessor/seq/size.hpp>
#include <boost/preprocessor/tuple/elem.hpp>

/* uncursed-pp source:
 * # Outer params referenced inside a loop ride FOR_EACH's spare d slot:
 * # one free var travels as d itself, several as a tuple in d, and the
 * # iterable itself may be referenced too (e.g. via len()).
 * @macro TAG(prefix, xs: seq<token>)
 * @for x in xs
 * {{prefix}}({{x}});
 * @end
 * @endmacro
 */
#define UNCURSED_PP_TAG_EACH1(r, d, e) d(e);
#define TAG(prefix, xs) BOOST_PP_SEQ_FOR_EACH(UNCURSED_PP_TAG_EACH1, prefix, xs)

/* uncursed-pp source:
 * @macro BOTH(a, b, xs: seq<token>)
 * @for x in xs
 * g({{a}}, {{b}}, {{x}});
 * @end
 * @endmacro
 */
#define UNCURSED_PP_BOTH_EACH1(r, d, e) g(BOOST_PP_TUPLE_ELEM(0, d), BOOST_PP_TUPLE_ELEM(1, d), e);
#define BOTH(a, b, xs) BOOST_PP_SEQ_FOR_EACH(UNCURSED_PP_BOTH_EACH1, (a, b), xs)

/* uncursed-pp source:
 * @macro COUNTED(xs: seq<token>)
 * @for x in xs
 * h({{x}}, {{len(xs)}});
 * @end
 * @endmacro
 */
#define UNCURSED_PP_COUNTED_EACH1(r, d, e) h(e, BOOST_PP_SEQ_SIZE(d));
#define COUNTED(xs) BOOST_PP_SEQ_FOR_EACH(UNCURSED_PP_COUNTED_EACH1, xs, xs)
