/* Generated by uncursed-pp from nested_seq.uncursed — do not edit. */
#pragma once

#include <boost/preprocessor/cat.hpp>
#include <boost/preprocessor/control/iif.hpp>
#include <boost/preprocessor/seq/elem.hpp>
#include <boost/preprocessor/seq/for_each.hpp>
#include <boost/preprocessor/seq/size.hpp>
#include "uncursed_pp_runtime.h"

/* uncursed-pp source:
 * # seq<seq<token>>: index the outer seq, bind the inner one with @let,
 * # then loop over it (one loop level - the outer access is an index).
 * macro FIRST_ROW(grid: seq<seq<token>>)
 * @let row := grid[0]
 * @for x in row
 * cell({{x}});
 * @end
 * end
 */
#define UNCURSED_PP_FIRST_ROW_EACH1(r, d, e) cell(e);
#define UNCURSED_PP_FIRST_ROW_CH1_1(e) cell(e);
#define UNCURSED_PP_FIRST_ROW_CH1_2(e) cell(e); UNCURSED_PP_FIRST_ROW_CH1_1
#define UNCURSED_PP_FIRST_ROW_CH1_3(e) cell(e); UNCURSED_PP_FIRST_ROW_CH1_2
#define UNCURSED_PP_FIRST_ROW_CH1_4(e) cell(e); UNCURSED_PP_FIRST_ROW_CH1_3
#define UNCURSED_PP_FIRST_ROW_CH1_5(e) cell(e); UNCURSED_PP_FIRST_ROW_CH1_4
#define UNCURSED_PP_FIRST_ROW_CH1_6(e) cell(e); UNCURSED_PP_FIRST_ROW_CH1_5
#define UNCURSED_PP_FIRST_ROW_CH1_7(e) cell(e); UNCURSED_PP_FIRST_ROW_CH1_6
#define UNCURSED_PP_FIRST_ROW_CH1_8(e) cell(e); UNCURSED_PP_FIRST_ROW_CH1_7
#define UNCURSED_PP_FIRST_ROW_CH1_9(e) cell(e); UNCURSED_PP_FIRST_ROW_CH1_8
#define UNCURSED_PP_FIRST_ROW_CH1_10(e) cell(e); UNCURSED_PP_FIRST_ROW_CH1_9
#define UNCURSED_PP_FIRST_ROW_CH1_11(e) cell(e); UNCURSED_PP_FIRST_ROW_CH1_10
#define UNCURSED_PP_FIRST_ROW_CH1_12(e) cell(e); UNCURSED_PP_FIRST_ROW_CH1_11
#define UNCURSED_PP_FIRST_ROW_CH1_13(e) cell(e); UNCURSED_PP_FIRST_ROW_CH1_12
#define UNCURSED_PP_FIRST_ROW_CH1_14(e) cell(e); UNCURSED_PP_FIRST_ROW_CH1_13
#define UNCURSED_PP_FIRST_ROW_CH1_15(e) cell(e); UNCURSED_PP_FIRST_ROW_CH1_14
#define UNCURSED_PP_FIRST_ROW_CH1_16(e) cell(e); UNCURSED_PP_FIRST_ROW_CH1_15
#define UNCURSED_PP_FIRST_ROW_SMALL1(seq) BOOST_PP_CAT(UNCURSED_PP_FIRST_ROW_CH1_, BOOST_PP_SEQ_SIZE(seq)) seq
#define UNCURSED_PP_FIRST_ROW_PICK1(n) BOOST_PP_IIF(BOOST_PP_CAT(UNCURSED_PP_LE16_, n), UNCURSED_PP_FIRST_ROW_SMALL1, UNCURSED_PP_FIRST_ROW_BIG1)
#define UNCURSED_PP_FIRST_ROW_BIG1(seq) BOOST_PP_SEQ_FOR_EACH(UNCURSED_PP_FIRST_ROW_EACH1, ~, seq)
#define FIRST_ROW(grid) UNCURSED_PP_FIRST_ROW_PICK1(BOOST_PP_SEQ_SIZE(BOOST_PP_SEQ_ELEM(0, grid)))(BOOST_PP_SEQ_ELEM(0, grid))
