/* Generated by cursedpp from nested_seq.cursed — do not edit. */
#pragma once

#include <boost/preprocessor/seq/elem.hpp>
#include <boost/preprocessor/seq/for_each.hpp>

#define CURSEDPP_FIRST_ROW_EACH1(r, d, e) cell(e);
#define FIRST_ROW(grid) BOOST_PP_SEQ_FOR_EACH(CURSEDPP_FIRST_ROW_EACH1, ~, BOOST_PP_SEQ_ELEM(0, grid))
