/* Generated by uncursed-pp from nested.uncursed — do not edit. */
#pragma once

#include <boost/preprocessor/punctuation/comma_if.hpp>
#include <boost/preprocessor/repetition/repeat.hpp>
#include <boost/preprocessor/seq/elem.hpp>
#include <boost/preprocessor/seq/for_each.hpp>
#include <boost/preprocessor/seq/size.hpp>
#include <boost/preprocessor/tuple/elem.hpp>

/* # Nested loops (up to 4 deep): the outer level uses SEQ_FOR_EACH; inner
 * # levels ride BOOST_PP_REPEAT's three auto-detected dimensions, indexing
 * # their seq with SEQ_ELEM. The seq plus free outer variables travel in
 * # the inner data tuple.
 */

/* uncursed-pp source:
 * # cartesian product of two seq params
 * @macro CROSS($xs: seq<token>, $ys: seq<token>)
 * @for $x in $xs
 * @for $y in $ys
 * pair({{$x}}, {{$y}});
 * @end
 * @end
 * @endmacro
 */
#define UNCURSED_PP_CROSS_EACH1(z, n, d) pair(BOOST_PP_TUPLE_ELEM(1, d), BOOST_PP_SEQ_ELEM(n, BOOST_PP_TUPLE_ELEM(0, d)));
#define UNCURSED_PP_CROSS_EACH2(r, d, e) BOOST_PP_REPEAT(BOOST_PP_SEQ_SIZE(d), UNCURSED_PP_CROSS_EACH1, (d, e))
#define CROSS(xs, ys) BOOST_PP_SEQ_FOR_EACH(UNCURSED_PP_CROSS_EACH2, ys, xs)

/* uncursed-pp source:
 * # iterate a seq<seq<...>>: the inner iterable is the OUTER loop variable
 * @macro MATRIX($grid: seq<seq<token>>)
 * @for $row in $grid
 * @for $cell in $row
 * cell({{$cell}});
 * @end
 * @end
 * @endmacro
 */
#define UNCURSED_PP_MATRIX_EACH1(z, n, d) cell(BOOST_PP_SEQ_ELEM(n, d));
#define UNCURSED_PP_MATRIX_EACH2(r, d, e) BOOST_PP_REPEAT(BOOST_PP_SEQ_SIZE(e), UNCURSED_PP_MATRIX_EACH1, e)
#define MATRIX(grid) BOOST_PP_SEQ_FOR_EACH(UNCURSED_PP_MATRIX_EACH2, ~, grid)

/* uncursed-pp source:
 * # inline @join per outer element
 * @macro CALL_ROWS($xs: seq<token>, $ys: seq<token>)
 * @for $x in $xs
 * call({{$x}}, @join $ys as $y with ", ": {{$y}}@end);
 * @end
 * @endmacro
 */
#define UNCURSED_PP_CALL_ROWS_EACH1(z, n, d) BOOST_PP_COMMA_IF(n) BOOST_PP_SEQ_ELEM(n, d)
#define UNCURSED_PP_CALL_ROWS_EACH2(r, d, e) call(e, BOOST_PP_REPEAT(BOOST_PP_SEQ_SIZE(d), UNCURSED_PP_CALL_ROWS_EACH1, d));
#define CALL_ROWS(xs, ys) BOOST_PP_SEQ_FOR_EACH(UNCURSED_PP_CALL_ROWS_EACH2, ys, xs)

/* uncursed-pp source:
 * # full depth: 4 nested loops
 * @macro QUAD($s1: seq<token>, $s2: seq<token>, $s3: seq<token>, $s4: seq<token>)
 * @for $a in $s1
 * @for $b in $s2
 * @for $c in $s3
 * @for $dd in $s4
 * quad({{$a}}, {{$b}}, {{$c}}, {{$dd}});
 * @end
 * @end
 * @end
 * @end
 * @endmacro
 */
#define UNCURSED_PP_QUAD_EACH1(z, n, d) quad(BOOST_PP_TUPLE_ELEM(1, d), BOOST_PP_TUPLE_ELEM(2, d), BOOST_PP_TUPLE_ELEM(3, d), BOOST_PP_SEQ_ELEM(n, BOOST_PP_TUPLE_ELEM(0, d)));
#define UNCURSED_PP_QUAD_EACH2(z, n, d) BOOST_PP_REPEAT(BOOST_PP_SEQ_SIZE(BOOST_PP_TUPLE_ELEM(1, d)), UNCURSED_PP_QUAD_EACH1, (BOOST_PP_TUPLE_ELEM(1, d), BOOST_PP_TUPLE_ELEM(2, d), BOOST_PP_TUPLE_ELEM(3, d), BOOST_PP_SEQ_ELEM(n, BOOST_PP_TUPLE_ELEM(0, d))))
#define UNCURSED_PP_QUAD_EACH3(z, n, d) BOOST_PP_REPEAT(BOOST_PP_SEQ_SIZE(BOOST_PP_TUPLE_ELEM(1, d)), UNCURSED_PP_QUAD_EACH2, (BOOST_PP_TUPLE_ELEM(1, d), BOOST_PP_TUPLE_ELEM(2, d), BOOST_PP_TUPLE_ELEM(3, d), BOOST_PP_SEQ_ELEM(n, BOOST_PP_TUPLE_ELEM(0, d))))
#define UNCURSED_PP_QUAD_EACH4(r, d, e) BOOST_PP_REPEAT(BOOST_PP_SEQ_SIZE(BOOST_PP_TUPLE_ELEM(0, d)), UNCURSED_PP_QUAD_EACH3, (BOOST_PP_TUPLE_ELEM(0, d), BOOST_PP_TUPLE_ELEM(1, d), BOOST_PP_TUPLE_ELEM(2, d), e))
#define QUAD(s1, s2, s3, s4) BOOST_PP_SEQ_FOR_EACH(UNCURSED_PP_QUAD_EACH4, (s2, s3, s4), s1)

/* # ── invocation specs (verified through cc -E by the spec harness) ──
 * #?  CROSS((a)(b), (u)(v))
 * #=>     pair(a, u); pair(a, v); pair(b, u); pair(b, v);
 */

/* #?  MATRIX(((a)(b))((c)))
 * #=>     cell(a); cell(b); cell(c);
 */

/* #?  CALL_ROWS((p)(q), (u)(v))
 * #=>     call(p, u, v); call(q, u, v);
 */

/* #?  QUAD((1), (2)(20), (3), (4))
 * #=>     quad(1, 2, 3, 4); quad(1, 20, 3, 4);
 */

/* # edge: single-element everything
 * #?  QUAD((1), (2), (3), (4))
 * #=>     quad(1, 2, 3, 4);
 */
