/* Generated by uncursed-pp from or_token_fallback.uncursed — do not edit. */
#pragma once

#include <boost/preprocessor/cat.hpp>
#include <boost/preprocessor/control/iif.hpp>
#include <boost/preprocessor/seq/for_each.hpp>
#include <boost/preprocessor/seq/size.hpp>
#include <boost/preprocessor/tuple/elem.hpp>
#include <boost/preprocessor/tuple/size.hpp>
#include <boost/preprocessor/variadic/to_seq.hpp>
#include "uncursed_pp_runtime.h"

/* # _or_token normalization must ride BOTH loop strategies: sizes up to
 * # loop_chain_limit take the consumption chain, larger ones the
 * # SEQ_FOR_EACH fallback. K=4 here so the specs can cross the boundary
 * # cheaply (same trick as chain_limit.uncursed).
 */

/* uncursed-pp source:
 * @macro TL($ms: variadic<tuple_or_token<$m, $v = 0>>)
 * @for ($m, $v) in $ms
 * t({{$m}}, {{$v}});
 * @end
 * @endmacro
 */
#define UNCURSED_PP_TL_AP1(m, v) t(m, v);
#define UNCURSED_PP_TL_AP1_N(t) UNCURSED_PP_TL_AP1 t
#define UNCURSED_PP_TL_EACH1(r, d, e) UNCURSED_PP_TL_AP1_N(UNCURSED_PP_TL_NF1(e))
#define UNCURSED_PP_TL_CH1_1(e) UNCURSED_PP_TL_AP1_N(UNCURSED_PP_TL_NF1(e))
#define UNCURSED_PP_TL_CH1_2(e) UNCURSED_PP_TL_AP1_N(UNCURSED_PP_TL_NF1(e)) UNCURSED_PP_TL_CH1_1
#define UNCURSED_PP_TL_CH1_3(e) UNCURSED_PP_TL_AP1_N(UNCURSED_PP_TL_NF1(e)) UNCURSED_PP_TL_CH1_2
#define UNCURSED_PP_TL_CH1_4(e) UNCURSED_PP_TL_AP1_N(UNCURSED_PP_TL_NF1(e)) UNCURSED_PP_TL_CH1_3
#define UNCURSED_PP_TL_NF1(t) UNCURSED_PP_TL_NF1_S(t, UNCURSED_PP_TL_NF1_CT(UNCURSED_PP_TL_NF1_R_, UNCURSED_PP_TL_NF1_C t))
#define UNCURSED_PP_TL_NF1_C(...) 1
#define UNCURSED_PP_TL_NF1_CT(a, b) UNCURSED_PP_TL_NF1_CTI(a, b)
#define UNCURSED_PP_TL_NF1_CTI(a, b) a ## b
#define UNCURSED_PP_TL_NF1_R_1 UNCURSED_PP_TL_NF1_T,
#define UNCURSED_PP_TL_NF1_R_UNCURSED_PP_TL_NF1_C UNCURSED_PP_TL_NF1_B,
#define UNCURSED_PP_TL_NF1_S(...) UNCURSED_PP_TL_NF1_SI(__VA_ARGS__)
#define UNCURSED_PP_TL_NF1_SI(t, f, ...) f(t)
#define UNCURSED_PP_TL_NF1_B(t) (t, 0)
#define UNCURSED_PP_TL_NF1_T(t) UNCURSED_PP_TL_NF1_D(BOOST_PP_TUPLE_SIZE(t), t)
#define UNCURSED_PP_TL_NF1_D(...) UNCURSED_PP_TL_NF1_I(__VA_ARGS__)
#define UNCURSED_PP_TL_NF1_I(n, t) UNCURSED_PP_TL_NF1_ ## n t
#define UNCURSED_PP_TL_NF1_1(f0) (f0, 0)
#define UNCURSED_PP_TL_NF1_2(f0, f1) (f0, f1)
#define UNCURSED_PP_TL_SMALL1(seq) BOOST_PP_CAT(UNCURSED_PP_TL_CH1_, BOOST_PP_SEQ_SIZE(seq)) seq
#define UNCURSED_PP_TL_PICK1(n) BOOST_PP_IIF(BOOST_PP_CAT(UNCURSED_PP_LE4_, n), UNCURSED_PP_TL_SMALL1, UNCURSED_PP_TL_BIG1)
#define UNCURSED_PP_TL_BIG1(seq) BOOST_PP_SEQ_FOR_EACH(UNCURSED_PP_TL_EACH1, ~, seq)
#define TL(...) UNCURSED_PP_TL_PICK1(BOOST_PP_SEQ_SIZE(BOOST_PP_VARIADIC_TO_SEQ(__VA_ARGS__)))(BOOST_PP_VARIADIC_TO_SEQ(__VA_ARGS__))

/* uncursed-pp source:
 * @macro SL($xs: seq_or_token<token>)
 * @for $x in $xs
 * s({{$x}});
 * @end
 * n={{len($xs)}}
 * @endmacro
 */
#define UNCURSED_PP_SL_EACH1(r, d, e) s(e);
#define UNCURSED_PP_SL_CH1_1(e) s(e);
#define UNCURSED_PP_SL_CH1_2(e) s(e); UNCURSED_PP_SL_CH1_1
#define UNCURSED_PP_SL_CH1_3(e) s(e); UNCURSED_PP_SL_CH1_2
#define UNCURSED_PP_SL_CH1_4(e) s(e); UNCURSED_PP_SL_CH1_3
#define UNCURSED_PP_SL_NS1(t) UNCURSED_PP_SL_NS1_S(t, UNCURSED_PP_SL_NS1_CT(UNCURSED_PP_SL_NS1_R_, UNCURSED_PP_SL_NS1_C t))
#define UNCURSED_PP_SL_NS1_C(...) 1
#define UNCURSED_PP_SL_NS1_CT(a, b) UNCURSED_PP_SL_NS1_CTI(a, b)
#define UNCURSED_PP_SL_NS1_CTI(a, b) a ## b
#define UNCURSED_PP_SL_NS1_R_1 UNCURSED_PP_SL_NS1_T,
#define UNCURSED_PP_SL_NS1_R_UNCURSED_PP_SL_NS1_C UNCURSED_PP_SL_NS1_B,
#define UNCURSED_PP_SL_NS1_S(...) UNCURSED_PP_SL_NS1_SI(__VA_ARGS__)
#define UNCURSED_PP_SL_NS1_SI(t, f, ...) f(t)
#define UNCURSED_PP_SL_NS1_T(t) t
#define UNCURSED_PP_SL_NS1_B(t) (t)
#define UNCURSED_PP_SL_SMALL1(seq) BOOST_PP_CAT(UNCURSED_PP_SL_CH1_, BOOST_PP_SEQ_SIZE(seq)) seq
#define UNCURSED_PP_SL_PICK1(n) BOOST_PP_IIF(BOOST_PP_CAT(UNCURSED_PP_LE4_, n), UNCURSED_PP_SL_SMALL1, UNCURSED_PP_SL_BIG1)
#define UNCURSED_PP_SL_BIG1(seq) BOOST_PP_SEQ_FOR_EACH(UNCURSED_PP_SL_EACH1, ~, seq)
#define SL(xs) \
    UNCURSED_PP_SL_PICK1(BOOST_PP_SEQ_SIZE(UNCURSED_PP_SL_NS1(xs)))(UNCURSED_PP_SL_NS1(xs)) \
    n=BOOST_PP_SEQ_SIZE(UNCURSED_PP_SL_NS1(xs))

/* # ── invocation specs (verified through cc -E by test_e2e_specs) ──
 * # within the chain (3 <= 4):
 * #?  TL(a, (b, 2), c)
 * #=>     t(a, 0); t(b, 2); t(c, 0);
 */

/* # past the limit (6 > 4): the SEQ_FOR_EACH fallback normalizes too
 * #?  TL(a, (b, 2), c, d, (e, 5), f)
 * #=>     t(a, 0); t(b, 2); t(c, 0); t(d, 0); t(e, 5); t(f, 0);
 */

/* #?  SL(solo)
 * #=>     s(solo); n=1
 */

/* #?  SL((a)(b)(c))
 * #=>     s(a); s(b); s(c); n=3
 */

/* #?  SL((a)(b)(c)(d)(e)(f))
 * #=>     s(a); s(b); s(c); s(d); s(e); s(f); n=6
 */
