/* Generated by uncursed-pp from ors.uncursed — do not edit. */
#pragma once

#include <boost/preprocessor/cat.hpp>
#include <boost/preprocessor/control/if.hpp>
#include <boost/preprocessor/control/iif.hpp>
#include <boost/preprocessor/facilities/empty.hpp>
#include <boost/preprocessor/seq/for_each_i.hpp>
#include <boost/preprocessor/seq/size.hpp>
#include "uncursed_pp_runtime.h"

/* uncursed-pp source:
 * # Non-comma separator: the separator text lives in its own SEP helper.
 * macro ORS(xs: seq<token>)
 * @join xs as x with " || "
 * ({{x}})
 * @end
 * end
 */
#define UNCURSED_PP_ORS_SEP1() ||
#define UNCURSED_PP_ORS_EACH1(r, d, i, e) BOOST_PP_IF(i, UNCURSED_PP_ORS_SEP1, BOOST_PP_EMPTY)() (e)
#define UNCURSED_PP_ORS_CH1_1(e) (e)
#define UNCURSED_PP_ORS_CH1_2(e) (e) || UNCURSED_PP_ORS_CH1_1
#define UNCURSED_PP_ORS_CH1_3(e) (e) || UNCURSED_PP_ORS_CH1_2
#define UNCURSED_PP_ORS_CH1_4(e) (e) || UNCURSED_PP_ORS_CH1_3
#define UNCURSED_PP_ORS_CH1_5(e) (e) || UNCURSED_PP_ORS_CH1_4
#define UNCURSED_PP_ORS_CH1_6(e) (e) || UNCURSED_PP_ORS_CH1_5
#define UNCURSED_PP_ORS_CH1_7(e) (e) || UNCURSED_PP_ORS_CH1_6
#define UNCURSED_PP_ORS_CH1_8(e) (e) || UNCURSED_PP_ORS_CH1_7
#define UNCURSED_PP_ORS_CH1_9(e) (e) || UNCURSED_PP_ORS_CH1_8
#define UNCURSED_PP_ORS_CH1_10(e) (e) || UNCURSED_PP_ORS_CH1_9
#define UNCURSED_PP_ORS_CH1_11(e) (e) || UNCURSED_PP_ORS_CH1_10
#define UNCURSED_PP_ORS_CH1_12(e) (e) || UNCURSED_PP_ORS_CH1_11
#define UNCURSED_PP_ORS_CH1_13(e) (e) || UNCURSED_PP_ORS_CH1_12
#define UNCURSED_PP_ORS_CH1_14(e) (e) || UNCURSED_PP_ORS_CH1_13
#define UNCURSED_PP_ORS_CH1_15(e) (e) || UNCURSED_PP_ORS_CH1_14
#define UNCURSED_PP_ORS_CH1_16(e) (e) || UNCURSED_PP_ORS_CH1_15
#define UNCURSED_PP_ORS_SMALL1(seq) BOOST_PP_CAT(UNCURSED_PP_ORS_CH1_, BOOST_PP_SEQ_SIZE(seq)) seq
#define UNCURSED_PP_ORS_PICK1(n) BOOST_PP_IIF(BOOST_PP_CAT(UNCURSED_PP_LE16_, n), UNCURSED_PP_ORS_SMALL1, UNCURSED_PP_ORS_BIG1)
#define UNCURSED_PP_ORS_BIG1(seq) BOOST_PP_SEQ_FOR_EACH_I(UNCURSED_PP_ORS_EACH1, ~, seq)
#define ORS(xs) UNCURSED_PP_ORS_PICK1(BOOST_PP_SEQ_SIZE(xs))(xs)
