/* Generated by uncursed-pp from ors.uncursed — do not edit. */
#pragma once

#include <boost/preprocessor/control/if.hpp>
#include <boost/preprocessor/facilities/empty.hpp>
#include <boost/preprocessor/seq/for_each_i.hpp>

/* uncursed-pp source:
 * # Non-comma separator: the separator text lives in its own SEP helper.
 * macro ORS(xs: seq<token>)
 * @join xs as x with " || "
 * ({{x}})
 * @end
 * end
 */
#define UNCURSED_PP_ORS_SEP1() ||
#define UNCURSED_PP_ORS_EACH1(r, d, i, e) BOOST_PP_IF(i, UNCURSED_PP_ORS_SEP1, BOOST_PP_EMPTY)() (e)
#define ORS(xs) BOOST_PP_SEQ_FOR_EACH_I(UNCURSED_PP_ORS_EACH1, ~, xs)
