/* Generated by uncursed-pp from proto.uncursed — do not edit. */
#pragma once

#include <boost/preprocessor/punctuation/comma_if.hpp>
#include <boost/preprocessor/seq/for_each_i.hpp>
#include <boost/preprocessor/tuple/elem.hpp>

/* uncursed-pp source:
 * # Function prototype from a seq of (type, argname) tuples.
 * macro PROTO(name, args: seq<tuple<type, argname>>)
 * void {{name}}(@join args with ", ": {{type}} {{argname}}@end);
 * end
 */
#define UNCURSED_PP_PROTO_AP1(type, argname) type argname
#define UNCURSED_PP_PROTO_EACH1(r, d, i, e) BOOST_PP_COMMA_IF(i) UNCURSED_PP_PROTO_AP1 e
#define PROTO(name, args) void name(BOOST_PP_SEQ_FOR_EACH_I(UNCURSED_PP_PROTO_EACH1, ~, args));
