/* Generated by uncursed-pp from two_joins.uncursed — do not edit. */
#pragma once

#include <boost/preprocessor/seq/enum.hpp>
#include <boost/preprocessor/seq/size.hpp>

/* uncursed-pp source:
 * # Two inline @joins on one line get independent EACH helpers.
 * macro ZIP(ks: seq<token>, vs: seq<token>)
 * k({{len(ks)}}): @join ks as k with ", ": {{k}}@end / v: @join vs as v with ", ": {{v}}@end
 * end
 */
#define ZIP(ks, vs) k(BOOST_PP_SEQ_SIZE(ks)): BOOST_PP_SEQ_ENUM(ks) / v: BOOST_PP_SEQ_ENUM(vs)
