/* Generated by cursedpp from two_joins.cursed — do not edit. */
#pragma once

#include <boost/preprocessor/punctuation/comma_if.hpp>
#include <boost/preprocessor/seq/for_each_i.hpp>
#include <boost/preprocessor/seq/size.hpp>

#define CURSEDPP_H1(r, d, i, e) BOOST_PP_COMMA_IF(i) e
#define ZIP(ks, vs) k(BOOST_PP_SEQ_SIZE(ks)): BOOST_PP_SEQ_FOR_EACH_I(CURSEDPP_H1, ~, ks) / v: BOOST_PP_SEQ_FOR_EACH_I(CURSEDPP_H1, ~, vs)
