/* Generated by uncursed-pp from 03-nested-loops.uncursed — do not edit. */
#pragma once

#include <boost/preprocessor/repetition/repeat.hpp>
#include <boost/preprocessor/seq/elem.hpp>
#include <boost/preprocessor/seq/for_each.hpp>
#include <boost/preprocessor/seq/size.hpp>
#include <boost/preprocessor/tuple/elem.hpp>

/* uncursed-pp source:
 * @macro FILL_DISPATCH(modes: seq<token>, widths: seq<token>)
 * @for m in modes
 * @for w in widths
 *   table[{{m}}][{{w}}] = op_generic;
 * @end
 * @end
 * @endmacro
 */
#define UNCURSED_PP_FILL_DISPATCH_EACH1(z, n, d) table[BOOST_PP_TUPLE_ELEM(1, d)][BOOST_PP_SEQ_ELEM(n, BOOST_PP_TUPLE_ELEM(0, d))] = op_generic;
#define UNCURSED_PP_FILL_DISPATCH_EACH2(r, d, e) BOOST_PP_REPEAT(BOOST_PP_SEQ_SIZE(d), UNCURSED_PP_FILL_DISPATCH_EACH1, (d, e))
#define FILL_DISPATCH(modes, widths) BOOST_PP_SEQ_FOR_EACH(UNCURSED_PP_FILL_DISPATCH_EACH2, widths, modes)
