/* Generated by uncursed-pp from 04-join.uncursed — do not edit. */
#pragma once

#include <boost/preprocessor/cat.hpp>
#include <boost/preprocessor/control/if.hpp>
#include <boost/preprocessor/control/iif.hpp>
#include <boost/preprocessor/facilities/empty.hpp>
#include <boost/preprocessor/punctuation/comma_if.hpp>
#include <boost/preprocessor/seq/for_each_i.hpp>
#include <boost/preprocessor/seq/size.hpp>
#include <boost/preprocessor/tuple/elem.hpp>
#include "uncursed_pp_runtime.h"

/* # ── @join: loop with a separator ─────────────────────────────────────
 * #
 * # `@join xs with "sep": body @end` emits the body once per element with
 * # `sep` BETWEEN elements (never trailing). The inline form shown here
 * # fits on one line; a block form exists too. `as name` binds the
 * # element; for a seq<tuple<...>> the tuple's element names are bound
 * # automatically, no `as` needed.
 * #
 * # Scenario: a function prototype — the classic comma-separated list.
 */

/* uncursed-pp source:
 * @macro DECLARE_FN($ret, $fname, $params: seq<tuple<$ptype, $pname>>)
 * {{$ret}} {{$fname}}(@join $params with ", ": {{$ptype}} {{$pname}}@end);
 * @endmacro
 */
#define UNCURSED_PP_DECLARE_FN_AP1(ptype, pname) ptype pname
#define UNCURSED_PP_DECLARE_FN_EACH1(r, d, i, e) BOOST_PP_COMMA_IF(i) UNCURSED_PP_DECLARE_FN_AP1 e
#define UNCURSED_PP_DECLARE_FN_CH1_1(e) UNCURSED_PP_DECLARE_FN_AP1 e
#define UNCURSED_PP_DECLARE_FN_CH1_2(e) UNCURSED_PP_DECLARE_FN_AP1 e, UNCURSED_PP_DECLARE_FN_CH1_1
#define UNCURSED_PP_DECLARE_FN_CH1_3(e) UNCURSED_PP_DECLARE_FN_AP1 e, UNCURSED_PP_DECLARE_FN_CH1_2
#define UNCURSED_PP_DECLARE_FN_CH1_4(e) UNCURSED_PP_DECLARE_FN_AP1 e, UNCURSED_PP_DECLARE_FN_CH1_3
#define UNCURSED_PP_DECLARE_FN_CH1_5(e) UNCURSED_PP_DECLARE_FN_AP1 e, UNCURSED_PP_DECLARE_FN_CH1_4
#define UNCURSED_PP_DECLARE_FN_CH1_6(e) UNCURSED_PP_DECLARE_FN_AP1 e, UNCURSED_PP_DECLARE_FN_CH1_5
#define UNCURSED_PP_DECLARE_FN_CH1_7(e) UNCURSED_PP_DECLARE_FN_AP1 e, UNCURSED_PP_DECLARE_FN_CH1_6
#define UNCURSED_PP_DECLARE_FN_CH1_8(e) UNCURSED_PP_DECLARE_FN_AP1 e, UNCURSED_PP_DECLARE_FN_CH1_7
#define UNCURSED_PP_DECLARE_FN_CH1_9(e) UNCURSED_PP_DECLARE_FN_AP1 e, UNCURSED_PP_DECLARE_FN_CH1_8
#define UNCURSED_PP_DECLARE_FN_CH1_10(e) UNCURSED_PP_DECLARE_FN_AP1 e, UNCURSED_PP_DECLARE_FN_CH1_9
#define UNCURSED_PP_DECLARE_FN_CH1_11(e) UNCURSED_PP_DECLARE_FN_AP1 e, UNCURSED_PP_DECLARE_FN_CH1_10
#define UNCURSED_PP_DECLARE_FN_CH1_12(e) UNCURSED_PP_DECLARE_FN_AP1 e, UNCURSED_PP_DECLARE_FN_CH1_11
#define UNCURSED_PP_DECLARE_FN_CH1_13(e) UNCURSED_PP_DECLARE_FN_AP1 e, UNCURSED_PP_DECLARE_FN_CH1_12
#define UNCURSED_PP_DECLARE_FN_CH1_14(e) UNCURSED_PP_DECLARE_FN_AP1 e, UNCURSED_PP_DECLARE_FN_CH1_13
#define UNCURSED_PP_DECLARE_FN_CH1_15(e) UNCURSED_PP_DECLARE_FN_AP1 e, UNCURSED_PP_DECLARE_FN_CH1_14
#define UNCURSED_PP_DECLARE_FN_CH1_16(e) UNCURSED_PP_DECLARE_FN_AP1 e, UNCURSED_PP_DECLARE_FN_CH1_15
#define UNCURSED_PP_DECLARE_FN_SMALL1(seq) BOOST_PP_CAT(UNCURSED_PP_DECLARE_FN_CH1_, BOOST_PP_SEQ_SIZE(seq)) seq
#define UNCURSED_PP_DECLARE_FN_PICK1(n) BOOST_PP_IIF(BOOST_PP_CAT(UNCURSED_PP_LE16_, n), UNCURSED_PP_DECLARE_FN_SMALL1, UNCURSED_PP_DECLARE_FN_BIG1)
#define UNCURSED_PP_DECLARE_FN_BIG1(seq) BOOST_PP_SEQ_FOR_EACH_I(UNCURSED_PP_DECLARE_FN_EACH1, ~, seq)
#define DECLARE_FN(ret, fname, params) ret fname(UNCURSED_PP_DECLARE_FN_PICK1(BOOST_PP_SEQ_SIZE(params))(params));

/* #?  DECLARE_FN(int, clamp, ((int, v))((int, lo))((int, hi)))
 * #=>     int clamp(int v, int lo, int hi);
 */

/* # One parameter: no separator emitted.
 * #?  DECLARE_FN(void, reset, ((struct ctx *, c)))
 * #=>     void reset(struct ctx * c);
 */

/* # Separators are arbitrary text, not just commas. `as f` names the
 * # element explicitly.
 */

/* uncursed-pp source:
 * @macro ANY_FLAG_SET($mask, $flags: seq<token>)
 * (@join $flags as $f with " || ": ({{$mask}} & {{$f}})@end)
 * @endmacro
 */
#define UNCURSED_PP_ANY_FLAG_SET_SEP1() ||
#define UNCURSED_PP_ANY_FLAG_SET_EACH1(r, d, i, e) BOOST_PP_IF(i, UNCURSED_PP_ANY_FLAG_SET_SEP1, BOOST_PP_EMPTY)() (d & e)
#define ANY_FLAG_SET(mask, flags) (BOOST_PP_SEQ_FOR_EACH_I(UNCURSED_PP_ANY_FLAG_SET_EACH1, mask, flags))

/* #?  ANY_FLAG_SET(m, (F_DIRTY)(F_LOCKED))
 * #=>     ((m & F_DIRTY) || (m & F_LOCKED))
 */
