/* Generated by uncursed-pp from 05-if-else.uncursed — do not edit. */
#pragma once

#include <boost/preprocessor/arithmetic/dec.hpp>
#include <boost/preprocessor/cat.hpp>
#include <boost/preprocessor/comparison/equal.hpp>
#include <boost/preprocessor/control/if.hpp>
#include <boost/preprocessor/control/iif.hpp>
#include <boost/preprocessor/facilities/empty.hpp>
#include <boost/preprocessor/logical/bool.hpp>
#include <boost/preprocessor/seq/elem.hpp>
#include <boost/preprocessor/seq/for_each_i.hpp>
#include <boost/preprocessor/seq/size.hpp>
#include "uncursed_pp_runtime.h"

/* uncursed-pp source:
 * @macro DECLARE_BUFFER(name, dims: seq<token>)
 * @if len(dims) == 1
 *   static char {{name}}[{{dims[0]}}];
 * @else
 *   static char {{name}}[@join dims as d with " * ": {{d}}@end];
 * @end
 * @endmacro
 */
#define UNCURSED_PP_DECLARE_BUFFER_THEN1(name, dims) static char name[BOOST_PP_SEQ_ELEM(0, dims)];
#define UNCURSED_PP_DECLARE_BUFFER_SEP1() *
#define UNCURSED_PP_DECLARE_BUFFER_EACH1(r, d, i, e) BOOST_PP_IF(i, UNCURSED_PP_DECLARE_BUFFER_SEP1, BOOST_PP_EMPTY)() e
#define UNCURSED_PP_DECLARE_BUFFER_CH1_1(e) e
#define UNCURSED_PP_DECLARE_BUFFER_CH1_2(e) e * UNCURSED_PP_DECLARE_BUFFER_CH1_1
#define UNCURSED_PP_DECLARE_BUFFER_CH1_3(e) e * UNCURSED_PP_DECLARE_BUFFER_CH1_2
#define UNCURSED_PP_DECLARE_BUFFER_CH1_4(e) e * UNCURSED_PP_DECLARE_BUFFER_CH1_3
#define UNCURSED_PP_DECLARE_BUFFER_CH1_5(e) e * UNCURSED_PP_DECLARE_BUFFER_CH1_4
#define UNCURSED_PP_DECLARE_BUFFER_CH1_6(e) e * UNCURSED_PP_DECLARE_BUFFER_CH1_5
#define UNCURSED_PP_DECLARE_BUFFER_CH1_7(e) e * UNCURSED_PP_DECLARE_BUFFER_CH1_6
#define UNCURSED_PP_DECLARE_BUFFER_CH1_8(e) e * UNCURSED_PP_DECLARE_BUFFER_CH1_7
#define UNCURSED_PP_DECLARE_BUFFER_CH1_9(e) e * UNCURSED_PP_DECLARE_BUFFER_CH1_8
#define UNCURSED_PP_DECLARE_BUFFER_CH1_10(e) e * UNCURSED_PP_DECLARE_BUFFER_CH1_9
#define UNCURSED_PP_DECLARE_BUFFER_CH1_11(e) e * UNCURSED_PP_DECLARE_BUFFER_CH1_10
#define UNCURSED_PP_DECLARE_BUFFER_CH1_12(e) e * UNCURSED_PP_DECLARE_BUFFER_CH1_11
#define UNCURSED_PP_DECLARE_BUFFER_CH1_13(e) e * UNCURSED_PP_DECLARE_BUFFER_CH1_12
#define UNCURSED_PP_DECLARE_BUFFER_CH1_14(e) e * UNCURSED_PP_DECLARE_BUFFER_CH1_13
#define UNCURSED_PP_DECLARE_BUFFER_CH1_15(e) e * UNCURSED_PP_DECLARE_BUFFER_CH1_14
#define UNCURSED_PP_DECLARE_BUFFER_CH1_16(e) e * UNCURSED_PP_DECLARE_BUFFER_CH1_15
#define UNCURSED_PP_DECLARE_BUFFER_ELSE1(name, dims) static char name[UNCURSED_PP_DECLARE_BUFFER_PICK1(BOOST_PP_SEQ_SIZE(dims))(dims)];
#define UNCURSED_PP_DECLARE_BUFFER_SMALL1(seq) BOOST_PP_CAT(UNCURSED_PP_DECLARE_BUFFER_CH1_, BOOST_PP_SEQ_SIZE(seq)) seq
#define UNCURSED_PP_DECLARE_BUFFER_PICK1(n) BOOST_PP_IIF(BOOST_PP_CAT(UNCURSED_PP_LE16_, n), UNCURSED_PP_DECLARE_BUFFER_SMALL1, UNCURSED_PP_DECLARE_BUFFER_BIG1)
#define UNCURSED_PP_DECLARE_BUFFER_BIG1(seq) BOOST_PP_SEQ_FOR_EACH_I(UNCURSED_PP_DECLARE_BUFFER_EACH1, ~, seq)
#define DECLARE_BUFFER(name, dims) BOOST_PP_IIF(BOOST_PP_EQUAL(BOOST_PP_SEQ_SIZE(dims), 1), UNCURSED_PP_DECLARE_BUFFER_THEN1, UNCURSED_PP_DECLARE_BUFFER_ELSE1)(name, dims)

/* uncursed-pp source:
 * @macro PICK_SEARCH(xs: seq<token>)
 * @if len(xs) <= 3
 *   linear_scan
 * @else
 *   binary_search
 * @end
 * @endmacro
 */
#define UNCURSED_PP_PICK_SEARCH_THEN1() linear_scan
#define UNCURSED_PP_PICK_SEARCH_ELSE1() binary_search
#define PICK_SEARCH(xs) BOOST_PP_IIF(BOOST_PP_BOOL(BOOST_PP_DEC(BOOST_PP_DEC(BOOST_PP_DEC(BOOST_PP_SEQ_SIZE(xs))))), UNCURSED_PP_PICK_SEARCH_ELSE1, UNCURSED_PP_PICK_SEARCH_THEN1)()
