/* Generated by uncursed-pp from 06-is-paren.uncursed — do not edit. */
#pragma once

#include <boost/preprocessor/control/iif.hpp>
#include <boost/preprocessor/punctuation/is_begin_parens.hpp>

/* uncursed-pp source:
 * macro INIT_CALL(fn, arg)
 * @if is_paren(arg)
 *   {{fn}}{{arg}};
 * @else
 *   {{fn}}(({{arg}}));
 * @end
 * end
 */
#define UNCURSED_PP_INIT_CALL_THEN1(fn, arg) fn arg;
#define UNCURSED_PP_INIT_CALL_ELSE1(fn, arg) fn((arg));
#define INIT_CALL(fn, arg) BOOST_PP_IIF(BOOST_PP_IS_BEGIN_PARENS(arg), UNCURSED_PP_INIT_CALL_THEN1, UNCURSED_PP_INIT_CALL_ELSE1)(fn, arg)
