/* Generated by uncursed-pp from 07-concat.uncursed — do not edit. */
#pragma once

#include <boost/preprocessor/cat.hpp>
#include "uncursed_pp_runtime.h"

/* uncursed-pp source:
 * macro DEFINE_ACCESSORS(sname, f: tuple<ftype, fname>)
 * static {{f.ftype}} {{concat(get_, f.fname)}}(const struct {{sname}} *o) { return o->{{f.fname}}; }
 * static void {{concat(set_, f.fname)}}(struct {{sname}} *o, {{f.ftype}} v) { o->{{f.fname}} = v; }
 * end
 */
#define UNCURSED_PP_DEFINE_ACCESSORS_BODY1(sname, ftype, fname) \
    static ftype BOOST_PP_CAT(get_, fname)(const struct sname *o) { return o->fname; } \
    static void BOOST_PP_CAT(set_, fname)(struct sname *o, ftype v) { o->fname = v; }
#define UNCURSED_PP_DEFINE_ACCESSORS_BODY1_D(...) UNCURSED_PP_DEFINE_ACCESSORS_BODY1(__VA_ARGS__)
#define DEFINE_ACCESSORS(sname, f) UNCURSED_PP_DEFINE_ACCESSORS_BODY1_D(sname, UNCURSED_PP_KW_SPREAD f)
