/* Generated by uncursed-pp from 08-stringize.uncursed — do not edit. */
#pragma once

#include <boost/preprocessor/cat.hpp>
#include <boost/preprocessor/control/iif.hpp>
#include <boost/preprocessor/seq/for_each.hpp>
#include <boost/preprocessor/seq/size.hpp>
#include <boost/preprocessor/stringize.hpp>
#include "uncursed_pp_runtime.h"

/* # ── stringize(): C strings from computed tokens ──────────────────────
 * #
 * # The C `#` operator only stringizes DIRECT macro parameters. For
 * # anything computed — a loop variable, a tuple element, a concat()
 * # result — use {{stringize(x)}}, which compiles to BOOST_PP_STRINGIZE
 * # and works on the token's final value.
 * #
 * # Scenario: an error-name table indexed by the enum value itself.
 */

/* uncursed-pp source:
 * @macro DEFINE_ERROR_NAMES($codes: seq<token>)
 * static const char *error_name[] = {
 * @for $c in $codes
 *   [{{$c}}] = {{stringize($c)}},
 * @end
 * };
 * @endmacro
 */
#define UNCURSED_PP_DEFINE_ERROR_NAMES_EACH1(r, d, e) [e] = BOOST_PP_STRINGIZE(e),
#define UNCURSED_PP_DEFINE_ERROR_NAMES_CH1_1(e) [e] = BOOST_PP_STRINGIZE(e),
#define UNCURSED_PP_DEFINE_ERROR_NAMES_CH1_2(e) [e] = BOOST_PP_STRINGIZE(e), UNCURSED_PP_DEFINE_ERROR_NAMES_CH1_1
#define UNCURSED_PP_DEFINE_ERROR_NAMES_CH1_3(e) [e] = BOOST_PP_STRINGIZE(e), UNCURSED_PP_DEFINE_ERROR_NAMES_CH1_2
#define UNCURSED_PP_DEFINE_ERROR_NAMES_CH1_4(e) [e] = BOOST_PP_STRINGIZE(e), UNCURSED_PP_DEFINE_ERROR_NAMES_CH1_3
#define UNCURSED_PP_DEFINE_ERROR_NAMES_CH1_5(e) [e] = BOOST_PP_STRINGIZE(e), UNCURSED_PP_DEFINE_ERROR_NAMES_CH1_4
#define UNCURSED_PP_DEFINE_ERROR_NAMES_CH1_6(e) [e] = BOOST_PP_STRINGIZE(e), UNCURSED_PP_DEFINE_ERROR_NAMES_CH1_5
#define UNCURSED_PP_DEFINE_ERROR_NAMES_CH1_7(e) [e] = BOOST_PP_STRINGIZE(e), UNCURSED_PP_DEFINE_ERROR_NAMES_CH1_6
#define UNCURSED_PP_DEFINE_ERROR_NAMES_CH1_8(e) [e] = BOOST_PP_STRINGIZE(e), UNCURSED_PP_DEFINE_ERROR_NAMES_CH1_7
#define UNCURSED_PP_DEFINE_ERROR_NAMES_CH1_9(e) [e] = BOOST_PP_STRINGIZE(e), UNCURSED_PP_DEFINE_ERROR_NAMES_CH1_8
#define UNCURSED_PP_DEFINE_ERROR_NAMES_CH1_10(e) [e] = BOOST_PP_STRINGIZE(e), UNCURSED_PP_DEFINE_ERROR_NAMES_CH1_9
#define UNCURSED_PP_DEFINE_ERROR_NAMES_CH1_11(e) [e] = BOOST_PP_STRINGIZE(e), UNCURSED_PP_DEFINE_ERROR_NAMES_CH1_10
#define UNCURSED_PP_DEFINE_ERROR_NAMES_CH1_12(e) [e] = BOOST_PP_STRINGIZE(e), UNCURSED_PP_DEFINE_ERROR_NAMES_CH1_11
#define UNCURSED_PP_DEFINE_ERROR_NAMES_CH1_13(e) [e] = BOOST_PP_STRINGIZE(e), UNCURSED_PP_DEFINE_ERROR_NAMES_CH1_12
#define UNCURSED_PP_DEFINE_ERROR_NAMES_CH1_14(e) [e] = BOOST_PP_STRINGIZE(e), UNCURSED_PP_DEFINE_ERROR_NAMES_CH1_13
#define UNCURSED_PP_DEFINE_ERROR_NAMES_CH1_15(e) [e] = BOOST_PP_STRINGIZE(e), UNCURSED_PP_DEFINE_ERROR_NAMES_CH1_14
#define UNCURSED_PP_DEFINE_ERROR_NAMES_CH1_16(e) [e] = BOOST_PP_STRINGIZE(e), UNCURSED_PP_DEFINE_ERROR_NAMES_CH1_15
#define UNCURSED_PP_DEFINE_ERROR_NAMES_SMALL1(seq) BOOST_PP_CAT(UNCURSED_PP_DEFINE_ERROR_NAMES_CH1_, BOOST_PP_SEQ_SIZE(seq)) seq
#define UNCURSED_PP_DEFINE_ERROR_NAMES_PICK1(n) BOOST_PP_IIF(BOOST_PP_CAT(UNCURSED_PP_LE16_, n), UNCURSED_PP_DEFINE_ERROR_NAMES_SMALL1, UNCURSED_PP_DEFINE_ERROR_NAMES_BIG1)
#define UNCURSED_PP_DEFINE_ERROR_NAMES_BIG1(seq) BOOST_PP_SEQ_FOR_EACH(UNCURSED_PP_DEFINE_ERROR_NAMES_EACH1, ~, seq)
#define DEFINE_ERROR_NAMES(codes) \
    static const char *error_name[] = { \
    UNCURSED_PP_DEFINE_ERROR_NAMES_PICK1(BOOST_PP_SEQ_SIZE(codes))(codes) \
    };

/* #?  DEFINE_ERROR_NAMES((E_OK)(E_IO)(E_NOMEM))
 * #=>     static const char *error_name[] = {
 * #=>         [E_OK] = "E_OK",
 * #=>         [E_IO] = "E_IO",
 * #=>         [E_NOMEM] = "E_NOMEM",
 * #=>     };
 */
