/* Generated by uncursed-pp from 09-remove-parens.uncursed — do not edit. */
#pragma once

#include <boost/preprocessor/punctuation/remove_parens.hpp>
#include "uncursed_pp_runtime.h"

/* uncursed-pp source:
 * @macro DECLARE_MEMBER(m: tuple<mtype, mname>)
 * {{remove_parens(m.mtype)}} {{m.mname}};
 * @endmacro
 */
#define UNCURSED_PP_DECLARE_MEMBER_BODY1(mtype, mname) BOOST_PP_REMOVE_PARENS(mtype) mname;
#define UNCURSED_PP_DECLARE_MEMBER_BODY1_D(...) UNCURSED_PP_DECLARE_MEMBER_BODY1(__VA_ARGS__)
#define DECLARE_MEMBER(m) UNCURSED_PP_DECLARE_MEMBER_BODY1_D(UNCURSED_PP_KW_SPREAD m)
