/* Generated by uncursed-pp from 10-let.uncursed — do not edit. */
#pragma once

#include <boost/preprocessor/cat.hpp>
#include <boost/preprocessor/seq/enum.hpp>
#include <boost/preprocessor/seq/size.hpp>

/* uncursed-pp source:
 * @macro COUNTED_ARRAY(name, elems: seq<token>)
 * @let n := len(elems)
 * static const int {{name}}[{{n}}] = { @join elems as e with ", ": {{e}}@end };
 * enum { {{concat(name, _len)}} = {{n}} };
 * @endmacro
 */
#define COUNTED_ARRAY(name, elems) \
    static const int name[BOOST_PP_SEQ_SIZE(elems)] = { BOOST_PP_SEQ_ENUM(elems) }; \
    enum { BOOST_PP_CAT(name, _len) = BOOST_PP_SEQ_SIZE(elems) };
