/* Generated by uncursed-pp from 11-tail-defaults.uncursed — do not edit. */
#pragma once

/* # ── Tail defaults: optional trailing arguments ───────────────────────
 * #
 * # `param = value` gives a trailing parameter a default. Omitted
 * # arguments are filled in AT C COMPILE TIME by arity dispatch — the
 * # generated macro counts its arguments and routes to the right filler.
 * # Defaults must trail required parameters; a default value must not
 * # contain commas or parens; at least one required parameter is needed
 * # (C cannot overload on zero arguments).
 * #
 * # Scenario: a retry wrapper where attempts and failure handler are
 * # usually the defaults.
 */

/* uncursed-pp source:
 * @macro RETRY($call, $attempts = 3, $on_fail = abort)
 * for (int i_ = 0; i_ < {{$attempts}}; i_++) { if ({{$call}}() == 0) break; if (i_ == {{$attempts}} - 1) {{$on_fail}}(); }
 * @endmacro
 */
#define UNCURSED_PP_RETRY_1(call) UNCURSED_PP_RETRY_3(call, 3, abort)
#define UNCURSED_PP_RETRY_2(call, attempts) UNCURSED_PP_RETRY_3(call, attempts, abort)
#define UNCURSED_PP_RETRY_3(call, attempts, on_fail) for (int i_ = 0; i_ < attempts; i_++) { if (call() == 0) break; if (i_ == attempts - 1) on_fail(); }
#define UNCURSED_PP_RETRY_SIZE(...) UNCURSED_PP_RETRY_SIZE_I(__VA_ARGS__, 3, 2, 1,)
#define UNCURSED_PP_RETRY_SIZE_I(e0, e1, e2, size, ...) size
#define UNCURSED_PP_RETRY_DISPATCH(n) UNCURSED_PP_RETRY_DISPATCH_I(n)
#define UNCURSED_PP_RETRY_DISPATCH_I(n) UNCURSED_PP_RETRY_ ## n
#define RETRY(...) UNCURSED_PP_RETRY_DISPATCH(UNCURSED_PP_RETRY_SIZE(__VA_ARGS__))(__VA_ARGS__)

/* #?  RETRY(connect)
 * #=>     for (int i_ = 0; i_ < 3; i_++) { if (connect() == 0) break; if (i_ == 3 - 1) abort(); }
 */

/* #?  RETRY(connect, 5)
 * #=>     for (int i_ = 0; i_ < 5; i_++) { if (connect() == 0) break; if (i_ == 5 - 1) abort(); }
 */

/* #?  RETRY(connect, 5, panic)
 * #=>     for (int i_ = 0; i_ < 5; i_++) { if (connect() == 0) break; if (i_ == 5 - 1) panic(); }
 */

/* # A default may be EMPTY — here `quals` disappears when omitted. */

/* uncursed-pp source:
 * @macro EXPORT_FN($ret, $fname, $quals = )
 * {{$quals}} {{$ret}} {{$fname}}(void);
 * @endmacro
 */
#define UNCURSED_PP_EXPORT_FN_2(ret, fname) UNCURSED_PP_EXPORT_FN_3(ret, fname, )
#define UNCURSED_PP_EXPORT_FN_3(ret, fname, quals) quals ret fname(void);
#define UNCURSED_PP_EXPORT_FN_SIZE(...) UNCURSED_PP_EXPORT_FN_SIZE_I(__VA_ARGS__, 3, 2, 1,)
#define UNCURSED_PP_EXPORT_FN_SIZE_I(e0, e1, e2, size, ...) size
#define UNCURSED_PP_EXPORT_FN_DISPATCH(n) UNCURSED_PP_EXPORT_FN_DISPATCH_I(n)
#define UNCURSED_PP_EXPORT_FN_DISPATCH_I(n) UNCURSED_PP_EXPORT_FN_ ## n
#define EXPORT_FN(...) UNCURSED_PP_EXPORT_FN_DISPATCH(UNCURSED_PP_EXPORT_FN_SIZE(__VA_ARGS__))(__VA_ARGS__)

/* #?  EXPORT_FN(int, get_version)
 * #=>     int get_version(void);
 */

/* #?  EXPORT_FN(int, get_version, static)
 * #=>     static int get_version(void);
 */
