/* Generated by uncursed-pp from 12-named-args.uncursed — do not edit. */
#pragma once

#include <boost/preprocessor/cat.hpp>

/* # ── Named arguments: any order, any subset ───────────────────────────
 * #
 * # `named KEY = default` declares a keyword parameter. Call sites write
 * # KEY(value) after the required arguments — in any order, any subset.
 * # Rules that matter at the call site:
 * #   - a repeated keyword: the LAST occurrence wins;
 * #   - a misspelled keyword is a C compile error, never a silent default;
 * #   - values containing commas must be parenthesized: TITLE((a, b));
 * #   - KEY() passes an empty value (zero tokens);
 * #   - keyword names must not be #define'd macros at the call site.
 * #
 * # Scenario: opening a window without remembering a 4-argument order.
 */

/* uncursed-pp source:
 * @macro OPEN_WINDOW($title, named $W = 640, named $H = 480, named $MONITOR = 0)
 * open_window({{$title}}, {{$W}}, {{$H}}, {{$MONITOR}});
 * @endmacro
 */
#define UNCURSED_PP_OPEN_WINDOW_SET_W(v) 0, v
#define UNCURSED_PP_OPEN_WINDOW_SET_H(v) 1, v
#define UNCURSED_PP_OPEN_WINDOW_SET_MONITOR(v) 2, v
#define UNCURSED_PP_OPEN_WINDOW_STEP1(e, ...) UNCURSED_PP_OPEN_WINDOW_STEP_D(BOOST_PP_CAT(UNCURSED_PP_OPEN_WINDOW_SET_, e), __VA_ARGS__)
#define UNCURSED_PP_OPEN_WINDOW_STEP_D(...) UNCURSED_PP_OPEN_WINDOW_STEP_I(__VA_ARGS__)
#define UNCURSED_PP_OPEN_WINDOW_STEP_I(i, v, ...) UNCURSED_PP_OPEN_WINDOW_PUT_ ## i(v, __VA_ARGS__)
#define UNCURSED_PP_OPEN_WINDOW_PUT_0(v, p0, p1, p2) v, p1, p2
#define UNCURSED_PP_OPEN_WINDOW_PUT_1(v, p0, p1, p2) p0, v, p2
#define UNCURSED_PP_OPEN_WINDOW_PUT_2(v, p0, p1, p2) p0, p1, v
#define UNCURSED_PP_OPEN_WINDOW_BODY(title, W, H, MONITOR) open_window(title, W, H, MONITOR);
#define UNCURSED_PP_OPEN_WINDOW_BODY_D(...) UNCURSED_PP_OPEN_WINDOW_BODY(__VA_ARGS__)
#define UNCURSED_PP_OPEN_WINDOW_1(title) UNCURSED_PP_OPEN_WINDOW_BODY(title, 640, 480, 0)
#define UNCURSED_PP_OPEN_WINDOW_2(title, e1) UNCURSED_PP_OPEN_WINDOW_BODY_D(title, UNCURSED_PP_OPEN_WINDOW_STEP1(e1, 640, 480, 0))
#define UNCURSED_PP_OPEN_WINDOW_3(title, e1, e2) UNCURSED_PP_OPEN_WINDOW_BODY_D(title, UNCURSED_PP_OPEN_WINDOW_STEP1(e2, UNCURSED_PP_OPEN_WINDOW_STEP1(e1, 640, 480, 0)))
#define UNCURSED_PP_OPEN_WINDOW_4(title, e1, e2, e3) UNCURSED_PP_OPEN_WINDOW_BODY_D(title, UNCURSED_PP_OPEN_WINDOW_STEP1(e3, UNCURSED_PP_OPEN_WINDOW_STEP1(e2, UNCURSED_PP_OPEN_WINDOW_STEP1(e1, 640, 480, 0))))
#define UNCURSED_PP_OPEN_WINDOW_SIZE(...) UNCURSED_PP_OPEN_WINDOW_SIZE_I(__VA_ARGS__, 4, 3, 2, 1,)
#define UNCURSED_PP_OPEN_WINDOW_SIZE_I(e0, e1, e2, e3, size, ...) size
#define UNCURSED_PP_OPEN_WINDOW_DISPATCH(n) UNCURSED_PP_OPEN_WINDOW_DISPATCH_I(n)
#define UNCURSED_PP_OPEN_WINDOW_DISPATCH_I(n) UNCURSED_PP_OPEN_WINDOW_ ## n
#define OPEN_WINDOW(...) UNCURSED_PP_OPEN_WINDOW_DISPATCH(UNCURSED_PP_OPEN_WINDOW_SIZE(__VA_ARGS__))(__VA_ARGS__)

/* # All defaults:
 * #?  OPEN_WINDOW("editor")
 * #=>     open_window("editor", 640, 480, 0);
 */

/* # Any subset, any order:
 * #?  OPEN_WINDOW("editor", H(1080), W(1920))
 * #=>     open_window("editor", 1920, 1080, 0);
 */

/* # Repeated keyword — last one wins:
 * #?  OPEN_WINDOW("editor", MONITOR(1), MONITOR(2))
 * #=>     open_window("editor", 640, 480, 2);
 */

/* # ── Empty defaults and empty values ──────────────────────────────────
 * #
 * # A default may be empty: the parameter substitutes as zero tokens
 * # unless the caller says otherwise. Bare `named $ATTRS` (no `=`) is
 * # shorthand for `named $ATTRS = `. Great for optional qualifiers,
 * # attributes, or trailing initializer entries.
 */

/* uncursed-pp source:
 * @macro DECLARE($name, named $ATTRS)
 * {{$ATTRS}} int {{$name}};
 * @endmacro
 */
#define UNCURSED_PP_DECLARE_SET_ATTRS(v) 0, v
#define UNCURSED_PP_DECLARE_STEP1(e, ...) UNCURSED_PP_DECLARE_STEP_D(BOOST_PP_CAT(UNCURSED_PP_DECLARE_SET_, e), __VA_ARGS__)
#define UNCURSED_PP_DECLARE_STEP_D(...) UNCURSED_PP_DECLARE_STEP_I(__VA_ARGS__)
#define UNCURSED_PP_DECLARE_STEP_I(i, v, ...) UNCURSED_PP_DECLARE_PUT_ ## i(v, __VA_ARGS__)
#define UNCURSED_PP_DECLARE_PUT_0(v, p0) v
#define UNCURSED_PP_DECLARE_BODY(name, ATTRS) ATTRS int name;
#define UNCURSED_PP_DECLARE_BODY_D(...) UNCURSED_PP_DECLARE_BODY(__VA_ARGS__)
#define UNCURSED_PP_DECLARE_1(name) UNCURSED_PP_DECLARE_BODY(name, )
#define UNCURSED_PP_DECLARE_2(name, e1) UNCURSED_PP_DECLARE_BODY_D(name, UNCURSED_PP_DECLARE_STEP1(e1, ))
#define UNCURSED_PP_DECLARE_SIZE(...) UNCURSED_PP_DECLARE_SIZE_I(__VA_ARGS__, 2, 1,)
#define UNCURSED_PP_DECLARE_SIZE_I(e0, e1, size, ...) size
#define UNCURSED_PP_DECLARE_DISPATCH(n) UNCURSED_PP_DECLARE_DISPATCH_I(n)
#define UNCURSED_PP_DECLARE_DISPATCH_I(n) UNCURSED_PP_DECLARE_ ## n
#define DECLARE(...) UNCURSED_PP_DECLARE_DISPATCH(UNCURSED_PP_DECLARE_SIZE(__VA_ARGS__))(__VA_ARGS__)

/* # Omitted keyword — the empty default contributes nothing:
 * #?  DECLARE(counter)
 * #=>     int counter;
 */

/* #?  DECLARE(counter, ATTRS(volatile))
 * #=>     volatile int counter;
 */

/* # Explicit empty value — same result as omitting the keyword:
 * #?  DECLARE(counter, ATTRS())
 * #=>     int counter;
 */

/* # ── Required keywords ────────────────────────────────────────────────
 * #
 * # `required named $HOST` has no default: the keyword must appear at
 * # the call site or the program does not compile. Forgetting it is a
 * # hard preprocessor error; if a repeated keyword hides the mistake
 * # from the argument count, a poison identifier naming the keyword
 * # lands in the output and the C compiler rejects it instead.
 * # (An explicit empty value, HOST(), still counts as provided.)
 */

/* uncursed-pp source:
 * @macro CONNECT($sock, required named $HOST, named $PORT = 80)
 * dial({{$sock}}, {{$HOST}}, {{$PORT}});
 * @endmacro
 */
#define UNCURSED_PP_CONNECT_SET_HOST(v) 0, v
#define UNCURSED_PP_CONNECT_SET_PORT(v) 1, v
#define UNCURSED_PP_CONNECT_STEP1(e, ...) UNCURSED_PP_CONNECT_STEP_D(BOOST_PP_CAT(UNCURSED_PP_CONNECT_SET_, e), __VA_ARGS__)
#define UNCURSED_PP_CONNECT_STEP_D(...) UNCURSED_PP_CONNECT_STEP_I(__VA_ARGS__)
#define UNCURSED_PP_CONNECT_STEP_I(i, v, ...) UNCURSED_PP_CONNECT_PUT_ ## i(v, __VA_ARGS__)
#define UNCURSED_PP_CONNECT_PUT_0(v, p0, p1) v, p1
#define UNCURSED_PP_CONNECT_PUT_1(v, p0, p1) p0, v
#define UNCURSED_PP_CONNECT_BODY(sock, HOST, PORT) dial(sock, HOST, PORT);
#define UNCURSED_PP_CONNECT_BODY_D(...) UNCURSED_PP_CONNECT_BODY(__VA_ARGS__)
#define UNCURSED_PP_CONNECT_ERROR_MISSING_REQUIRED_KEYWORD(kw, missing)
#define UNCURSED_PP_CONNECT_1(...) UNCURSED_PP_CONNECT_ERROR_MISSING_REQUIRED_KEYWORD(~)
#define UNCURSED_PP_CONNECT_2(sock, e1) UNCURSED_PP_CONNECT_BODY_D(sock, UNCURSED_PP_CONNECT_STEP1(e1, UNCURSED_PP_CONNECT_MISSING_REQUIRED_KEYWORD_HOST, 80))
#define UNCURSED_PP_CONNECT_3(sock, e1, e2) UNCURSED_PP_CONNECT_BODY_D(sock, UNCURSED_PP_CONNECT_STEP1(e2, UNCURSED_PP_CONNECT_STEP1(e1, UNCURSED_PP_CONNECT_MISSING_REQUIRED_KEYWORD_HOST, 80)))
#define UNCURSED_PP_CONNECT_SIZE(...) UNCURSED_PP_CONNECT_SIZE_I(__VA_ARGS__, 3, 2, 1,)
#define UNCURSED_PP_CONNECT_SIZE_I(e0, e1, e2, size, ...) size
#define UNCURSED_PP_CONNECT_DISPATCH(n) UNCURSED_PP_CONNECT_DISPATCH_I(n)
#define UNCURSED_PP_CONNECT_DISPATCH_I(n) UNCURSED_PP_CONNECT_ ## n
#define CONNECT(...) UNCURSED_PP_CONNECT_DISPATCH(UNCURSED_PP_CONNECT_SIZE(__VA_ARGS__))(__VA_ARGS__)

/* #?  CONNECT(s, HOST("example.org"))
 * #=>     dial(s, "example.org", 80);
 */

/* #?  CONNECT(s, PORT(443), HOST(h))
 * #=>     dial(s, h, 443);
 */

/* # Too few arguments to possibly contain HOST — hard preprocessor error:
 * #?! CONNECT(s)
 */

/* # The right argument count but the wrong keyword sneaks past the arity
 * # check. The expansion "succeeds" — with the poison identifier in it,
 * # so the C compiler rejects the output while naming the missing keyword:
 * #?  CONNECT(s, PORT(443))
 * #=>     dial(s, UNCURSED_PP_CONNECT_MISSING_REQUIRED_KEYWORD_HOST, 443);
 */
