/* Generated by uncursed-pp from 12-named-args.uncursed — do not edit. */
#pragma once

#include <boost/preprocessor/cat.hpp>

/* # ── Named arguments: any order, any subset ───────────────────────────
 * #
 * # `named KEY = default` declares a keyword parameter. Call sites write
 * # KEY(value) after the required arguments — in any order, any subset.
 * # Rules that matter at the call site:
 * #   - a repeated keyword: the LAST occurrence wins;
 * #   - a misspelled keyword is a C compile error, never a silent default;
 * #   - values containing commas must be parenthesized: TITLE((a, b));
 * #   - keyword names must not be #define'd macros at the call site.
 * #
 * # Scenario: opening a window without remembering a 4-argument order.
 */

/* uncursed-pp source:
 * @macro OPEN_WINDOW($title, named $W = 640, named $H = 480, named $MONITOR = 0)
 * open_window({{$title}}, {{$W}}, {{$H}}, {{$MONITOR}});
 * @endmacro
 */
#define UNCURSED_PP_OPEN_WINDOW_SET_W(v) 0, v
#define UNCURSED_PP_OPEN_WINDOW_SET_H(v) 1, v
#define UNCURSED_PP_OPEN_WINDOW_SET_MONITOR(v) 2, v
#define UNCURSED_PP_OPEN_WINDOW_STEP1(e, ...) UNCURSED_PP_OPEN_WINDOW_STEP_D(BOOST_PP_CAT(UNCURSED_PP_OPEN_WINDOW_SET_, e), __VA_ARGS__)
#define UNCURSED_PP_OPEN_WINDOW_STEP_D(...) UNCURSED_PP_OPEN_WINDOW_STEP_I(__VA_ARGS__)
#define UNCURSED_PP_OPEN_WINDOW_STEP_I(i, v, ...) UNCURSED_PP_OPEN_WINDOW_PUT_ ## i(v, __VA_ARGS__)
#define UNCURSED_PP_OPEN_WINDOW_PUT_0(v, p0, p1, p2) v, p1, p2
#define UNCURSED_PP_OPEN_WINDOW_PUT_1(v, p0, p1, p2) p0, v, p2
#define UNCURSED_PP_OPEN_WINDOW_PUT_2(v, p0, p1, p2) p0, p1, v
#define UNCURSED_PP_OPEN_WINDOW_BODY(title, W, H, MONITOR) open_window(title, W, H, MONITOR);
#define UNCURSED_PP_OPEN_WINDOW_BODY_D(...) UNCURSED_PP_OPEN_WINDOW_BODY(__VA_ARGS__)
#define UNCURSED_PP_OPEN_WINDOW_1(title) UNCURSED_PP_OPEN_WINDOW_BODY(title, 640, 480, 0)
#define UNCURSED_PP_OPEN_WINDOW_2(title, e1) UNCURSED_PP_OPEN_WINDOW_BODY_D(title, UNCURSED_PP_OPEN_WINDOW_STEP1(e1, 640, 480, 0))
#define UNCURSED_PP_OPEN_WINDOW_3(title, e1, e2) UNCURSED_PP_OPEN_WINDOW_BODY_D(title, UNCURSED_PP_OPEN_WINDOW_STEP1(e2, UNCURSED_PP_OPEN_WINDOW_STEP1(e1, 640, 480, 0)))
#define UNCURSED_PP_OPEN_WINDOW_4(title, e1, e2, e3) UNCURSED_PP_OPEN_WINDOW_BODY_D(title, UNCURSED_PP_OPEN_WINDOW_STEP1(e3, UNCURSED_PP_OPEN_WINDOW_STEP1(e2, UNCURSED_PP_OPEN_WINDOW_STEP1(e1, 640, 480, 0))))
#define UNCURSED_PP_OPEN_WINDOW_SIZE(...) UNCURSED_PP_OPEN_WINDOW_SIZE_I(__VA_ARGS__, 4, 3, 2, 1,)
#define UNCURSED_PP_OPEN_WINDOW_SIZE_I(e0, e1, e2, e3, size, ...) size
#define UNCURSED_PP_OPEN_WINDOW_DISPATCH(n) UNCURSED_PP_OPEN_WINDOW_DISPATCH_I(n)
#define UNCURSED_PP_OPEN_WINDOW_DISPATCH_I(n) UNCURSED_PP_OPEN_WINDOW_ ## n
#define OPEN_WINDOW(...) UNCURSED_PP_OPEN_WINDOW_DISPATCH(UNCURSED_PP_OPEN_WINDOW_SIZE(__VA_ARGS__))(__VA_ARGS__)

/* # All defaults:
 * #?  OPEN_WINDOW("editor")
 * #=>     open_window("editor", 640, 480, 0);
 */

/* # Any subset, any order:
 * #?  OPEN_WINDOW("editor", H(1080), W(1920))
 * #=>     open_window("editor", 1920, 1080, 0);
 */

/* # Repeated keyword — last one wins:
 * #?  OPEN_WINDOW("editor", MONITOR(1), MONITOR(2))
 * #=>     open_window("editor", 640, 480, 2);
 */
