/* Generated by uncursed-pp from 13-named-variadic.uncursed — do not edit. */
#pragma once

#include <boost/preprocessor/cat.hpp>
#include "uncursed_pp_runtime.h"

/* # ── named variadic: keywords that take bare commas ───────────────────
 * #
 * # A plain `named` keyword takes ONE token-sequence — KEY(a, b) is a
 * # compile error naming the keyword's setter. Declaring the parameter
 * # `named variadic` opts in to bare commas: the whole argument list
 * # passes through verbatim.
 * #
 * # Scenario: a color gradient where stops are naturally a bare list.
 */

/* uncursed-pp source:
 * @macro DEFINE_GRADIENT($name, named variadic $STOPS = black)
 * static const int {{$name}}[] = { {{$STOPS}} };
 * @endmacro
 */
#define UNCURSED_PP_DEFINE_GRADIENT_SET_STOPS(...) 0, (__VA_ARGS__)
#define UNCURSED_PP_DEFINE_GRADIENT_STEP1(e, ...) UNCURSED_PP_DEFINE_GRADIENT_STEP_D(BOOST_PP_CAT(UNCURSED_PP_DEFINE_GRADIENT_SET_, e), __VA_ARGS__)
#define UNCURSED_PP_DEFINE_GRADIENT_STEP_D(...) UNCURSED_PP_DEFINE_GRADIENT_STEP_I(__VA_ARGS__)
#define UNCURSED_PP_DEFINE_GRADIENT_STEP_I(i, v, ...) UNCURSED_PP_DEFINE_GRADIENT_PUT_ ## i(v, __VA_ARGS__)
#define UNCURSED_PP_DEFINE_GRADIENT_PUT_0(v, p0) v
#define UNCURSED_PP_DEFINE_GRADIENT_BODY(name, STOPS) static const int name[] = { UNCURSED_PP_KW_SPREAD STOPS };
#define UNCURSED_PP_DEFINE_GRADIENT_BODY_D(...) UNCURSED_PP_DEFINE_GRADIENT_BODY(__VA_ARGS__)
#define UNCURSED_PP_DEFINE_GRADIENT_1(name) UNCURSED_PP_DEFINE_GRADIENT_BODY(name, (black))
#define UNCURSED_PP_DEFINE_GRADIENT_2(name, e1) UNCURSED_PP_DEFINE_GRADIENT_BODY_D(name, UNCURSED_PP_DEFINE_GRADIENT_STEP1(e1, (black)))
#define UNCURSED_PP_DEFINE_GRADIENT_SIZE(...) UNCURSED_PP_DEFINE_GRADIENT_SIZE_I(__VA_ARGS__, 2, 1,)
#define UNCURSED_PP_DEFINE_GRADIENT_SIZE_I(e0, e1, size, ...) size
#define UNCURSED_PP_DEFINE_GRADIENT_DISPATCH(n) UNCURSED_PP_DEFINE_GRADIENT_DISPATCH_I(n)
#define UNCURSED_PP_DEFINE_GRADIENT_DISPATCH_I(n) UNCURSED_PP_DEFINE_GRADIENT_ ## n
#define DEFINE_GRADIENT(...) UNCURSED_PP_DEFINE_GRADIENT_DISPATCH(UNCURSED_PP_DEFINE_GRADIENT_SIZE(__VA_ARGS__))(__VA_ARGS__)

/* # Default:
 * #?  DEFINE_GRADIENT(fade)
 * #=>     static const int fade[] = { black };
 */

/* # Bare commas pass through verbatim:
 * #?  DEFINE_GRADIENT(fade, STOPS(red, green, blue))
 * #=>     static const int fade[] = { red, green, blue };
 */
