/* Generated by uncursed-pp from 14-variadic.uncursed — do not edit. */
#pragma once

#include <boost/preprocessor/cat.hpp>
#include <boost/preprocessor/control/iif.hpp>
#include <boost/preprocessor/seq/for_each.hpp>
#include <boost/preprocessor/seq/size.hpp>
#include <boost/preprocessor/stringize.hpp>
#include <boost/preprocessor/tuple/elem.hpp>
#include <boost/preprocessor/variadic/to_seq.hpp>
#include "uncursed_pp_runtime.h"

/* # ── variadic: comma-separated call sites ─────────────────────────────
 * #
 * # `items: variadic` makes the macro take trailing `...` arguments; the
 * # body sees them as a seq, so @for and @join work unchanged. A variadic
 * # parameter must be last, must receive at least one argument, and
 * # excludes tail defaults / named parameters in the same macro.
 * #
 * # Scenario: releasing a batch of resources.
 */

/* uncursed-pp source:
 * @macro FREE_ALL(ptrs: variadic)
 * @for p in ptrs
 *   free({{p}});
 * @end
 * @endmacro
 */
#define UNCURSED_PP_FREE_ALL_EACH1(r, d, e) free(e);
#define UNCURSED_PP_FREE_ALL_CH1_1(e) free(e);
#define UNCURSED_PP_FREE_ALL_CH1_2(e) free(e); UNCURSED_PP_FREE_ALL_CH1_1
#define UNCURSED_PP_FREE_ALL_CH1_3(e) free(e); UNCURSED_PP_FREE_ALL_CH1_2
#define UNCURSED_PP_FREE_ALL_CH1_4(e) free(e); UNCURSED_PP_FREE_ALL_CH1_3
#define UNCURSED_PP_FREE_ALL_CH1_5(e) free(e); UNCURSED_PP_FREE_ALL_CH1_4
#define UNCURSED_PP_FREE_ALL_CH1_6(e) free(e); UNCURSED_PP_FREE_ALL_CH1_5
#define UNCURSED_PP_FREE_ALL_CH1_7(e) free(e); UNCURSED_PP_FREE_ALL_CH1_6
#define UNCURSED_PP_FREE_ALL_CH1_8(e) free(e); UNCURSED_PP_FREE_ALL_CH1_7
#define UNCURSED_PP_FREE_ALL_CH1_9(e) free(e); UNCURSED_PP_FREE_ALL_CH1_8
#define UNCURSED_PP_FREE_ALL_CH1_10(e) free(e); UNCURSED_PP_FREE_ALL_CH1_9
#define UNCURSED_PP_FREE_ALL_CH1_11(e) free(e); UNCURSED_PP_FREE_ALL_CH1_10
#define UNCURSED_PP_FREE_ALL_CH1_12(e) free(e); UNCURSED_PP_FREE_ALL_CH1_11
#define UNCURSED_PP_FREE_ALL_CH1_13(e) free(e); UNCURSED_PP_FREE_ALL_CH1_12
#define UNCURSED_PP_FREE_ALL_CH1_14(e) free(e); UNCURSED_PP_FREE_ALL_CH1_13
#define UNCURSED_PP_FREE_ALL_CH1_15(e) free(e); UNCURSED_PP_FREE_ALL_CH1_14
#define UNCURSED_PP_FREE_ALL_CH1_16(e) free(e); UNCURSED_PP_FREE_ALL_CH1_15
#define UNCURSED_PP_FREE_ALL_SMALL1(seq) BOOST_PP_CAT(UNCURSED_PP_FREE_ALL_CH1_, BOOST_PP_SEQ_SIZE(seq)) seq
#define UNCURSED_PP_FREE_ALL_PICK1(n) BOOST_PP_IIF(BOOST_PP_CAT(UNCURSED_PP_LE16_, n), UNCURSED_PP_FREE_ALL_SMALL1, UNCURSED_PP_FREE_ALL_BIG1)
#define UNCURSED_PP_FREE_ALL_BIG1(seq) BOOST_PP_SEQ_FOR_EACH(UNCURSED_PP_FREE_ALL_EACH1, ~, seq)
#define FREE_ALL(...) UNCURSED_PP_FREE_ALL_PICK1(BOOST_PP_SEQ_SIZE(BOOST_PP_VARIADIC_TO_SEQ(__VA_ARGS__)))(BOOST_PP_VARIADIC_TO_SEQ(__VA_ARGS__))

/* #?  FREE_ALL(line_buf, name_buf, path_buf)
 * #=>     free(line_buf);
 * #=>     free(name_buf);
 * #=>     free(path_buf);
 */

/* # `variadic<tuple<...>>` gives SINGLE-paren tuple call sites — compare
 * # the double parens a seq<tuple<...>> parameter would need.
 */

/* uncursed-pp source:
 * @macro SET_DEFAULTS(pairs: variadic<tuple<key, value>>)
 * @for (key, value) in pairs
 *   config_set({{stringize(key)}}, {{value}});
 * @end
 * @endmacro
 */
#define UNCURSED_PP_SET_DEFAULTS_AP1(key, value) config_set(BOOST_PP_STRINGIZE(key), value);
#define UNCURSED_PP_SET_DEFAULTS_EACH1(r, d, e) UNCURSED_PP_SET_DEFAULTS_AP1 e
#define UNCURSED_PP_SET_DEFAULTS_CH1_1(e) UNCURSED_PP_SET_DEFAULTS_AP1 e
#define UNCURSED_PP_SET_DEFAULTS_CH1_2(e) UNCURSED_PP_SET_DEFAULTS_AP1 e UNCURSED_PP_SET_DEFAULTS_CH1_1
#define UNCURSED_PP_SET_DEFAULTS_CH1_3(e) UNCURSED_PP_SET_DEFAULTS_AP1 e UNCURSED_PP_SET_DEFAULTS_CH1_2
#define UNCURSED_PP_SET_DEFAULTS_CH1_4(e) UNCURSED_PP_SET_DEFAULTS_AP1 e UNCURSED_PP_SET_DEFAULTS_CH1_3
#define UNCURSED_PP_SET_DEFAULTS_CH1_5(e) UNCURSED_PP_SET_DEFAULTS_AP1 e UNCURSED_PP_SET_DEFAULTS_CH1_4
#define UNCURSED_PP_SET_DEFAULTS_CH1_6(e) UNCURSED_PP_SET_DEFAULTS_AP1 e UNCURSED_PP_SET_DEFAULTS_CH1_5
#define UNCURSED_PP_SET_DEFAULTS_CH1_7(e) UNCURSED_PP_SET_DEFAULTS_AP1 e UNCURSED_PP_SET_DEFAULTS_CH1_6
#define UNCURSED_PP_SET_DEFAULTS_CH1_8(e) UNCURSED_PP_SET_DEFAULTS_AP1 e UNCURSED_PP_SET_DEFAULTS_CH1_7
#define UNCURSED_PP_SET_DEFAULTS_CH1_9(e) UNCURSED_PP_SET_DEFAULTS_AP1 e UNCURSED_PP_SET_DEFAULTS_CH1_8
#define UNCURSED_PP_SET_DEFAULTS_CH1_10(e) UNCURSED_PP_SET_DEFAULTS_AP1 e UNCURSED_PP_SET_DEFAULTS_CH1_9
#define UNCURSED_PP_SET_DEFAULTS_CH1_11(e) UNCURSED_PP_SET_DEFAULTS_AP1 e UNCURSED_PP_SET_DEFAULTS_CH1_10
#define UNCURSED_PP_SET_DEFAULTS_CH1_12(e) UNCURSED_PP_SET_DEFAULTS_AP1 e UNCURSED_PP_SET_DEFAULTS_CH1_11
#define UNCURSED_PP_SET_DEFAULTS_CH1_13(e) UNCURSED_PP_SET_DEFAULTS_AP1 e UNCURSED_PP_SET_DEFAULTS_CH1_12
#define UNCURSED_PP_SET_DEFAULTS_CH1_14(e) UNCURSED_PP_SET_DEFAULTS_AP1 e UNCURSED_PP_SET_DEFAULTS_CH1_13
#define UNCURSED_PP_SET_DEFAULTS_CH1_15(e) UNCURSED_PP_SET_DEFAULTS_AP1 e UNCURSED_PP_SET_DEFAULTS_CH1_14
#define UNCURSED_PP_SET_DEFAULTS_CH1_16(e) UNCURSED_PP_SET_DEFAULTS_AP1 e UNCURSED_PP_SET_DEFAULTS_CH1_15
#define UNCURSED_PP_SET_DEFAULTS_SMALL1(seq) BOOST_PP_CAT(UNCURSED_PP_SET_DEFAULTS_CH1_, BOOST_PP_SEQ_SIZE(seq)) seq
#define UNCURSED_PP_SET_DEFAULTS_PICK1(n) BOOST_PP_IIF(BOOST_PP_CAT(UNCURSED_PP_LE16_, n), UNCURSED_PP_SET_DEFAULTS_SMALL1, UNCURSED_PP_SET_DEFAULTS_BIG1)
#define UNCURSED_PP_SET_DEFAULTS_BIG1(seq) BOOST_PP_SEQ_FOR_EACH(UNCURSED_PP_SET_DEFAULTS_EACH1, ~, seq)
#define SET_DEFAULTS(...) UNCURSED_PP_SET_DEFAULTS_PICK1(BOOST_PP_SEQ_SIZE(BOOST_PP_VARIADIC_TO_SEQ(__VA_ARGS__)))(BOOST_PP_VARIADIC_TO_SEQ(__VA_ARGS__))

/* #?  SET_DEFAULTS((timeout, 30), (retries, 3))
 * #=>     config_set("timeout", 30);
 * #=>     config_set("retries", 3);
 */
