/* Generated by uncursed-pp from 16-helper-collapse.uncursed — do not edit. */
#pragma once

#include <boost/preprocessor/cat.hpp>
#include <boost/preprocessor/control/iif.hpp>
#include <boost/preprocessor/seq/for_each.hpp>
#include <boost/preprocessor/seq/size.hpp>
#include "uncursed_pp_runtime.h"

/* # ── Codegen: helper collapse ─────────────────────────────────────────
 * #
 * # This example is about the GENERATED code — open the committed
 * # 16-helper-collapse.h next to this file. The two macros below have
 * # identical loop bodies, so the emitter's collapse pass merges their
 * # helpers into the SAME shared, stem-namespaced identifiers: a plain
 * # per-element callback UNCURSED_PP_16_HELPER_COLLAPSE_H1 (for large
 * # seqs, via BOOST_PP_SEQ_FOR_EACH) and a size-dispatched chain family
 * # UNCURSED_PP_16_HELPER_COLLAPSE_HC2_1 .. HC2_16 (for small seqs, via
 * # token pasting). Both TRACE_CALLS and AUDIT_CALLS route through the
 * # very same H1/HC2_* definitions — nothing is duplicated per macro
 * # (the file stem namespaces them so two generated headers can't
 * # collide inside one translation unit).
 * #
 * # History note: chain families are a regression trap for collapse —
 * # each chain entry is picked by size via token pasting, so the
 * # collapse pass must move a whole chain family as one unit, never
 * # split across the two macros. These specs (deliberately SMALL seqs,
 * # so they hit the chain-family path) pin that behavior through the
 * # real preprocessor.
 */

/* uncursed-pp source:
 * @macro TRACE_CALLS(fns: seq<token>)
 * @for f in fns
 *   trace_enter({{f}});
 * @end
 * @endmacro
 */
#define UNCURSED_PP_16_HELPER_COLLAPSE_H1(r, d, e) trace_enter(e);
#define UNCURSED_PP_16_HELPER_COLLAPSE_HC2_1(e) trace_enter(e);
#define UNCURSED_PP_16_HELPER_COLLAPSE_HC2_2(e) trace_enter(e); UNCURSED_PP_16_HELPER_COLLAPSE_HC2_1
#define UNCURSED_PP_16_HELPER_COLLAPSE_HC2_3(e) trace_enter(e); UNCURSED_PP_16_HELPER_COLLAPSE_HC2_2
#define UNCURSED_PP_16_HELPER_COLLAPSE_HC2_4(e) trace_enter(e); UNCURSED_PP_16_HELPER_COLLAPSE_HC2_3
#define UNCURSED_PP_16_HELPER_COLLAPSE_HC2_5(e) trace_enter(e); UNCURSED_PP_16_HELPER_COLLAPSE_HC2_4
#define UNCURSED_PP_16_HELPER_COLLAPSE_HC2_6(e) trace_enter(e); UNCURSED_PP_16_HELPER_COLLAPSE_HC2_5
#define UNCURSED_PP_16_HELPER_COLLAPSE_HC2_7(e) trace_enter(e); UNCURSED_PP_16_HELPER_COLLAPSE_HC2_6
#define UNCURSED_PP_16_HELPER_COLLAPSE_HC2_8(e) trace_enter(e); UNCURSED_PP_16_HELPER_COLLAPSE_HC2_7
#define UNCURSED_PP_16_HELPER_COLLAPSE_HC2_9(e) trace_enter(e); UNCURSED_PP_16_HELPER_COLLAPSE_HC2_8
#define UNCURSED_PP_16_HELPER_COLLAPSE_HC2_10(e) trace_enter(e); UNCURSED_PP_16_HELPER_COLLAPSE_HC2_9
#define UNCURSED_PP_16_HELPER_COLLAPSE_HC2_11(e) trace_enter(e); UNCURSED_PP_16_HELPER_COLLAPSE_HC2_10
#define UNCURSED_PP_16_HELPER_COLLAPSE_HC2_12(e) trace_enter(e); UNCURSED_PP_16_HELPER_COLLAPSE_HC2_11
#define UNCURSED_PP_16_HELPER_COLLAPSE_HC2_13(e) trace_enter(e); UNCURSED_PP_16_HELPER_COLLAPSE_HC2_12
#define UNCURSED_PP_16_HELPER_COLLAPSE_HC2_14(e) trace_enter(e); UNCURSED_PP_16_HELPER_COLLAPSE_HC2_13
#define UNCURSED_PP_16_HELPER_COLLAPSE_HC2_15(e) trace_enter(e); UNCURSED_PP_16_HELPER_COLLAPSE_HC2_14
#define UNCURSED_PP_16_HELPER_COLLAPSE_HC2_16(e) trace_enter(e); UNCURSED_PP_16_HELPER_COLLAPSE_HC2_15
#define UNCURSED_PP_TRACE_CALLS_SMALL1(seq) BOOST_PP_CAT(UNCURSED_PP_16_HELPER_COLLAPSE_HC2_, BOOST_PP_SEQ_SIZE(seq)) seq
#define UNCURSED_PP_TRACE_CALLS_PICK1(n) BOOST_PP_IIF(BOOST_PP_CAT(UNCURSED_PP_LE16_, n), UNCURSED_PP_TRACE_CALLS_SMALL1, UNCURSED_PP_TRACE_CALLS_BIG1)
#define UNCURSED_PP_TRACE_CALLS_BIG1(seq) BOOST_PP_SEQ_FOR_EACH(UNCURSED_PP_16_HELPER_COLLAPSE_H1, ~, seq)
#define TRACE_CALLS(fns) UNCURSED_PP_TRACE_CALLS_PICK1(BOOST_PP_SEQ_SIZE(fns))(fns)

/* uncursed-pp source:
 * @macro AUDIT_CALLS(fns: seq<token>)
 * @for f in fns
 *   trace_enter({{f}});
 * @end
 * @endmacro
 */
#define UNCURSED_PP_AUDIT_CALLS_SMALL1(seq) BOOST_PP_CAT(UNCURSED_PP_16_HELPER_COLLAPSE_HC2_, BOOST_PP_SEQ_SIZE(seq)) seq
#define UNCURSED_PP_AUDIT_CALLS_PICK1(n) BOOST_PP_IIF(BOOST_PP_CAT(UNCURSED_PP_LE16_, n), UNCURSED_PP_AUDIT_CALLS_SMALL1, UNCURSED_PP_AUDIT_CALLS_BIG1)
#define UNCURSED_PP_AUDIT_CALLS_BIG1(seq) BOOST_PP_SEQ_FOR_EACH(UNCURSED_PP_16_HELPER_COLLAPSE_H1, ~, seq)
#define AUDIT_CALLS(fns) UNCURSED_PP_AUDIT_CALLS_PICK1(BOOST_PP_SEQ_SIZE(fns))(fns)

/* # Both macros expand through the SAME shared helpers:
 * #?  TRACE_CALLS((open_file)(read_file))
 * #=>     trace_enter(open_file);
 * #=>     trace_enter(read_file);
 */

/* #?  AUDIT_CALLS((close_file))
 * #=>     trace_enter(close_file);
 */
