/* Generated by uncursed-pp from 17-adjacency.uncursed — do not edit. */
#pragma once

#include <boost/preprocessor/cat.hpp>

/* uncursed-pp source:
 * @macro SHOW_PASTE_RULE(prefix, name)
 * int {{prefix}}{{name}} = 0;
 * int {{concat(prefix, name)}} = 1;
 * @endmacro
 */
#define SHOW_PASTE_RULE(prefix, name) \
    int prefix name = 0; \
    int BOOST_PP_CAT(prefix, name) = 1;
