/* Generated by uncursed-pp from 18-unbounded-tuple.uncursed — do not edit. */
#pragma once

#include <boost/preprocessor/cat.hpp>
#include <boost/preprocessor/control/iif.hpp>
#include <boost/preprocessor/facilities/is_empty_variadic.hpp>
#include <boost/preprocessor/seq/enum.hpp>
#include <boost/preprocessor/tuple/size.hpp>
#include <boost/preprocessor/tuple/to_seq.hpp>

/* uncursed-pp source:
 * macro DEFINE_LUT(name, vals: tuple)
 * static const int {{name}}[] = { @join vals as v with ", ": {{v}}@end };
 * enum { {{concat(name, _len)}} = {{len(vals)}} };
 * end
 */
#define UNCURSED_PP_DEFINE_LUT_LOOP1(vals) BOOST_PP_SEQ_ENUM(BOOST_PP_TUPLE_TO_SEQ(vals))
#define UNCURSED_PP_DEFINE_LUT_NIL1(vals)
#define UNCURSED_PP_18_UNBOUNDED_TUPLE_H1(x) BOOST_PP_IS_EMPTY x
#define DEFINE_LUT(name, vals) \
    static const int name[] = { BOOST_PP_IIF(UNCURSED_PP_18_UNBOUNDED_TUPLE_H1(vals), UNCURSED_PP_DEFINE_LUT_NIL1, UNCURSED_PP_DEFINE_LUT_LOOP1)(vals) }; \
    enum { BOOST_PP_CAT(name, _len) = BOOST_PP_IIF(UNCURSED_PP_18_UNBOUNDED_TUPLE_H1(vals), 0, BOOST_PP_TUPLE_SIZE(vals)) };

/* uncursed-pp source:
 * macro CALL_CTX(fn, extras: tuple)
 * @if is_empty(extras)
 *   {{fn}}(ctx);
 * @else
 *   {{fn}}(ctx, @join extras as a with ", ": {{a}}@end);
 * @end
 * end
 */
#define UNCURSED_PP_CALL_CTX_THEN1(fn, extras) fn(ctx);
#define UNCURSED_PP_CALL_CTX_LOOP1(extras) BOOST_PP_SEQ_ENUM(BOOST_PP_TUPLE_TO_SEQ(extras))
#define UNCURSED_PP_CALL_CTX_NIL1(extras)
#define UNCURSED_PP_CALL_CTX_ELSE1(fn, extras) fn(ctx, BOOST_PP_IIF(UNCURSED_PP_18_UNBOUNDED_TUPLE_H1(extras), UNCURSED_PP_CALL_CTX_NIL1, UNCURSED_PP_CALL_CTX_LOOP1)(extras));
#define CALL_CTX(fn, extras) BOOST_PP_IIF(UNCURSED_PP_18_UNBOUNDED_TUPLE_H1(extras), UNCURSED_PP_CALL_CTX_THEN1, UNCURSED_PP_CALL_CTX_ELSE1)(fn, extras)
