/* Generated by uncursed-pp from 18-unbounded-tuple.uncursed — do not edit. */
#pragma once

#include <boost/preprocessor/cat.hpp>
#include <boost/preprocessor/control/iif.hpp>
#include <boost/preprocessor/facilities/is_empty_variadic.hpp>
#include <boost/preprocessor/seq/enum.hpp>
#include <boost/preprocessor/seq/for_each.hpp>
#include <boost/preprocessor/seq/size.hpp>
#include <boost/preprocessor/tuple/elem.hpp>
#include <boost/preprocessor/tuple/size.hpp>
#include <boost/preprocessor/tuple/to_seq.hpp>
#include "uncursed_pp_runtime.h"

/* # ── Unbounded tuples: a variable number of elements, one paren pair ──
 * #
 * # `row: tuple` accepts (a, b, c) — commas between elements, ONE pair of
 * # parens. Compare the seq call site (a)(b)(c): seqs shine for long
 * # element-wise data, unbounded tuples for short comma lists that read
 * # like ordinary C argument lists. Bare `tuple` is shorthand for
 * # `tuple<token...>`; the element type goes before the ellipsis:
 * #
 * #     row: tuple                     F((a, b, c))
 * #     row: tuple<token...>           same, explicit
 * #     ps:  tuple<tuple<k, v>...>     F(((x, 1), (y, 2)))  — named pairs
 * #
 * # (`tuple<token>` — no ellipsis — is something else entirely: a fixed
 * # 1-tuple whose element is NAMED "token".)
 * #
 * # The empty tuple works: `()` means ZERO elements. Loops run zero
 * # times and len() reports 0, even though to the raw preprocessor ()
 * # looks like one empty element — the generated code carries an
 * # emptiness gate (see the committed .h next to this file).
 * #
 * # Call-site rules: elements cap at 64 (vs 256 for seqs); an element
 * # containing commas must be wrapped in parens like everywhere else;
 * # and a value that is itself the NAME of a function-like macro can
 * # confuse the emptiness probe — same family as the "keywords must not
 * # be #define'd" rule.
 * #
 * # Scenario: a lookup table whose length is derived, not repeated.
 * # (`tuple<token...>` written out — the ellipsis marks unboundedness.)
 */

/* uncursed-pp source:
 * @macro DEFINE_LUT($name, $vals: tuple)
 * static const int {{$name}}[] = { @join $vals as $v with ", ": {{$v}}@end };
 * enum { {{concat($name, _len)}} = {{len($vals)}} };
 * @endmacro
 */
#define UNCURSED_PP_DEFINE_LUT_LOOP1(vals) BOOST_PP_SEQ_ENUM(BOOST_PP_TUPLE_TO_SEQ(vals))
#define UNCURSED_PP_DEFINE_LUT_NIL1(vals)
#define UNCURSED_PP_18_UNBOUNDED_TUPLE_H1(x) BOOST_PP_IS_EMPTY x
#define DEFINE_LUT(name, vals) \
    static const int name[] = { BOOST_PP_IIF(UNCURSED_PP_18_UNBOUNDED_TUPLE_H1(vals), UNCURSED_PP_DEFINE_LUT_NIL1, UNCURSED_PP_DEFINE_LUT_LOOP1)(vals) }; \
    enum { BOOST_PP_CAT(name, _len) = BOOST_PP_IIF(UNCURSED_PP_18_UNBOUNDED_TUPLE_H1(vals), 0, BOOST_PP_TUPLE_SIZE(vals)) };

/* #?  DEFINE_LUT(gamma, (0, 12, 34))
 * #=>     static const int gamma[] = { 0, 12, 34 };
 * #=>     enum { gamma_len = 3 };
 */

/* # () is a real, useful input: zero elements, length 0.
 * #?  DEFINE_LUT(placeholder, ())
 * #=>     static const int placeholder[] = { };
 * #=>     enum { placeholder_len = 0 };
 */

/* # ── typed elements: tuple<tuple<k, v>...> ────────────────────────────
 * #
 * # The element type goes before the ellipsis. Named-tuple elements
 * # unpack in loops and give single-paren call sites — compare the
 * # double parens a seq<tuple<k, v>> would need: ((dark,1))((huge,2)).
 */

/* uncursed-pp source:
 * @macro DEFINE_MODES($ms: tuple<tuple<$mode, $bit>...>)
 * @for ($mode, $bit) in $ms
 *   {{$mode}} = 1 << {{$bit}},
 * @end
 * @endmacro
 */
#define UNCURSED_PP_DEFINE_MODES_AP1(mode, bit) mode = 1 << bit,
#define UNCURSED_PP_DEFINE_MODES_EACH1(r, d, e) UNCURSED_PP_DEFINE_MODES_AP1 e
#define UNCURSED_PP_DEFINE_MODES_CH1_1(e) UNCURSED_PP_DEFINE_MODES_AP1 e
#define UNCURSED_PP_DEFINE_MODES_CH1_2(e) UNCURSED_PP_DEFINE_MODES_AP1 e UNCURSED_PP_DEFINE_MODES_CH1_1
#define UNCURSED_PP_DEFINE_MODES_CH1_3(e) UNCURSED_PP_DEFINE_MODES_AP1 e UNCURSED_PP_DEFINE_MODES_CH1_2
#define UNCURSED_PP_DEFINE_MODES_CH1_4(e) UNCURSED_PP_DEFINE_MODES_AP1 e UNCURSED_PP_DEFINE_MODES_CH1_3
#define UNCURSED_PP_DEFINE_MODES_CH1_5(e) UNCURSED_PP_DEFINE_MODES_AP1 e UNCURSED_PP_DEFINE_MODES_CH1_4
#define UNCURSED_PP_DEFINE_MODES_CH1_6(e) UNCURSED_PP_DEFINE_MODES_AP1 e UNCURSED_PP_DEFINE_MODES_CH1_5
#define UNCURSED_PP_DEFINE_MODES_CH1_7(e) UNCURSED_PP_DEFINE_MODES_AP1 e UNCURSED_PP_DEFINE_MODES_CH1_6
#define UNCURSED_PP_DEFINE_MODES_CH1_8(e) UNCURSED_PP_DEFINE_MODES_AP1 e UNCURSED_PP_DEFINE_MODES_CH1_7
#define UNCURSED_PP_DEFINE_MODES_CH1_9(e) UNCURSED_PP_DEFINE_MODES_AP1 e UNCURSED_PP_DEFINE_MODES_CH1_8
#define UNCURSED_PP_DEFINE_MODES_CH1_10(e) UNCURSED_PP_DEFINE_MODES_AP1 e UNCURSED_PP_DEFINE_MODES_CH1_9
#define UNCURSED_PP_DEFINE_MODES_CH1_11(e) UNCURSED_PP_DEFINE_MODES_AP1 e UNCURSED_PP_DEFINE_MODES_CH1_10
#define UNCURSED_PP_DEFINE_MODES_CH1_12(e) UNCURSED_PP_DEFINE_MODES_AP1 e UNCURSED_PP_DEFINE_MODES_CH1_11
#define UNCURSED_PP_DEFINE_MODES_CH1_13(e) UNCURSED_PP_DEFINE_MODES_AP1 e UNCURSED_PP_DEFINE_MODES_CH1_12
#define UNCURSED_PP_DEFINE_MODES_CH1_14(e) UNCURSED_PP_DEFINE_MODES_AP1 e UNCURSED_PP_DEFINE_MODES_CH1_13
#define UNCURSED_PP_DEFINE_MODES_CH1_15(e) UNCURSED_PP_DEFINE_MODES_AP1 e UNCURSED_PP_DEFINE_MODES_CH1_14
#define UNCURSED_PP_DEFINE_MODES_CH1_16(e) UNCURSED_PP_DEFINE_MODES_AP1 e UNCURSED_PP_DEFINE_MODES_CH1_15
#define UNCURSED_PP_DEFINE_MODES_LOOP1(ms) UNCURSED_PP_DEFINE_MODES_PICK1(BOOST_PP_SEQ_SIZE(BOOST_PP_TUPLE_TO_SEQ(ms)))(BOOST_PP_TUPLE_TO_SEQ(ms))
#define UNCURSED_PP_DEFINE_MODES_NIL1(ms)
#define UNCURSED_PP_DEFINE_MODES_SMALL1(seq) BOOST_PP_CAT(UNCURSED_PP_DEFINE_MODES_CH1_, BOOST_PP_SEQ_SIZE(seq)) seq
#define UNCURSED_PP_DEFINE_MODES_PICK1(n) BOOST_PP_IIF(BOOST_PP_CAT(UNCURSED_PP_LE16_, n), UNCURSED_PP_DEFINE_MODES_SMALL1, UNCURSED_PP_DEFINE_MODES_BIG1)
#define UNCURSED_PP_DEFINE_MODES_BIG1(seq) BOOST_PP_SEQ_FOR_EACH(UNCURSED_PP_DEFINE_MODES_EACH1, ~, seq)
#define DEFINE_MODES(ms) BOOST_PP_IIF(UNCURSED_PP_18_UNBOUNDED_TUPLE_H1(ms), UNCURSED_PP_DEFINE_MODES_NIL1, UNCURSED_PP_DEFINE_MODES_LOOP1)(ms)

/* #?  DEFINE_MODES(((DARK, 0), (HUGE, 1)))
 * #=>     DARK = 1 << 0,
 * #=>     HUGE = 1 << 1,
 */

/* # ── is_empty(): branch on it directly ────────────────────────────────
 * #
 * # The optional-trailing-arguments pattern: () means "no extras", so
 * # the comma after ctx must disappear with them. Bare `tuple` is the
 * # `tuple<token...>` shorthand.
 */

/* uncursed-pp source:
 * @macro CALL_CTX($fn, $extras: tuple)
 * @if is_empty($extras)
 *   {{$fn}}(ctx);
 * @else
 *   {{$fn}}(ctx, @join $extras as $a with ", ": {{$a}}@end);
 * @end
 * @endmacro
 */
#define UNCURSED_PP_CALL_CTX_THEN1(fn, extras) fn(ctx);
#define UNCURSED_PP_CALL_CTX_LOOP1(extras) BOOST_PP_SEQ_ENUM(BOOST_PP_TUPLE_TO_SEQ(extras))
#define UNCURSED_PP_CALL_CTX_NIL1(extras)
#define UNCURSED_PP_CALL_CTX_ELSE1(fn, extras) fn(ctx, BOOST_PP_IIF(UNCURSED_PP_18_UNBOUNDED_TUPLE_H1(extras), UNCURSED_PP_CALL_CTX_NIL1, UNCURSED_PP_CALL_CTX_LOOP1)(extras));
#define CALL_CTX(fn, extras) BOOST_PP_IIF(UNCURSED_PP_18_UNBOUNDED_TUPLE_H1(extras), UNCURSED_PP_CALL_CTX_THEN1, UNCURSED_PP_CALL_CTX_ELSE1)(fn, extras)

/* #?  CALL_CTX(reset, ())
 * #=>     reset(ctx);
 */

/* #?  CALL_CTX(configure, (VERBOSE, 2))
 * #=>     configure(ctx, VERBOSE, 2);
 */
