/* Generated by uncursed-pp from 20-arg-prefix.uncursed — do not edit. */
#pragma once

#include <boost/preprocessor/cat.hpp>
#include <boost/preprocessor/control/iif.hpp>
#include <boost/preprocessor/seq/for_each.hpp>
#include <boost/preprocessor/seq/size.hpp>
#include "uncursed_pp_runtime.h"

/* # ── @pragma arg_prefix: bullet-proof body text ───────────────────────
 * #
 * # Template variables compile to C macro parameters, and C macro
 * # parameters substitute EVERYWHERE in the macro body - including raw
 * # C text you wrote next to an interpolation. The generated helpers
 * # also have their own parameter names (r, d, e, n, i, ...). So body
 * # text that happens to mention one of those names gets captured at
 * # expansion time:
 * #
 * #     @for $x in $xs
 * #     int e = {{$x}};      <- `e` is ALSO the loop element's slot name:
 * #     @end                    without protection this expands to
 * #                              `int alpha = alpha;` - not `int e = alpha;`
 * #
 * # `@pragma arg_prefix u_` renames EVERY generated parameter - your
 * # variables ($x becomes parameter u_x) and the harness slots alike -
 * # so plain body text can never collide with one. The cost is noisier
 * # generated code (read the committed .h next to this file); the win is
 * # that no identifier in your C text is off-limits anymore.
 */

/* uncursed-pp source:
 * @macro TRACE_VARS($vars: seq<token>)
 * @for $v in $vars
 * int e = snapshot({{$v}});
 * log(&d, &e);
 * @end
 * @endmacro
 */
#define UNCURSED_PP_TRACE_VARS_EACH1(u_r, u_d, u_e) int e = snapshot(u_e); log(&d, &e);
#define UNCURSED_PP_TRACE_VARS_CH1_1(u_e) int e = snapshot(u_e); log(&d, &e);
#define UNCURSED_PP_TRACE_VARS_CH1_2(u_e) int e = snapshot(u_e); log(&d, &e); UNCURSED_PP_TRACE_VARS_CH1_1
#define UNCURSED_PP_TRACE_VARS_CH1_3(u_e) int e = snapshot(u_e); log(&d, &e); UNCURSED_PP_TRACE_VARS_CH1_2
#define UNCURSED_PP_TRACE_VARS_CH1_4(u_e) int e = snapshot(u_e); log(&d, &e); UNCURSED_PP_TRACE_VARS_CH1_3
#define UNCURSED_PP_TRACE_VARS_CH1_5(u_e) int e = snapshot(u_e); log(&d, &e); UNCURSED_PP_TRACE_VARS_CH1_4
#define UNCURSED_PP_TRACE_VARS_CH1_6(u_e) int e = snapshot(u_e); log(&d, &e); UNCURSED_PP_TRACE_VARS_CH1_5
#define UNCURSED_PP_TRACE_VARS_CH1_7(u_e) int e = snapshot(u_e); log(&d, &e); UNCURSED_PP_TRACE_VARS_CH1_6
#define UNCURSED_PP_TRACE_VARS_CH1_8(u_e) int e = snapshot(u_e); log(&d, &e); UNCURSED_PP_TRACE_VARS_CH1_7
#define UNCURSED_PP_TRACE_VARS_CH1_9(u_e) int e = snapshot(u_e); log(&d, &e); UNCURSED_PP_TRACE_VARS_CH1_8
#define UNCURSED_PP_TRACE_VARS_CH1_10(u_e) int e = snapshot(u_e); log(&d, &e); UNCURSED_PP_TRACE_VARS_CH1_9
#define UNCURSED_PP_TRACE_VARS_CH1_11(u_e) int e = snapshot(u_e); log(&d, &e); UNCURSED_PP_TRACE_VARS_CH1_10
#define UNCURSED_PP_TRACE_VARS_CH1_12(u_e) int e = snapshot(u_e); log(&d, &e); UNCURSED_PP_TRACE_VARS_CH1_11
#define UNCURSED_PP_TRACE_VARS_CH1_13(u_e) int e = snapshot(u_e); log(&d, &e); UNCURSED_PP_TRACE_VARS_CH1_12
#define UNCURSED_PP_TRACE_VARS_CH1_14(u_e) int e = snapshot(u_e); log(&d, &e); UNCURSED_PP_TRACE_VARS_CH1_13
#define UNCURSED_PP_TRACE_VARS_CH1_15(u_e) int e = snapshot(u_e); log(&d, &e); UNCURSED_PP_TRACE_VARS_CH1_14
#define UNCURSED_PP_TRACE_VARS_CH1_16(u_e) int e = snapshot(u_e); log(&d, &e); UNCURSED_PP_TRACE_VARS_CH1_15
#define UNCURSED_PP_TRACE_VARS_SMALL1(u_seq) BOOST_PP_CAT(UNCURSED_PP_TRACE_VARS_CH1_, BOOST_PP_SEQ_SIZE(u_seq)) u_seq
#define UNCURSED_PP_TRACE_VARS_PICK1(u_n) BOOST_PP_IIF(BOOST_PP_CAT(UNCURSED_PP_LE16_, u_n), UNCURSED_PP_TRACE_VARS_SMALL1, UNCURSED_PP_TRACE_VARS_BIG1)
#define UNCURSED_PP_TRACE_VARS_BIG1(u_seq) BOOST_PP_SEQ_FOR_EACH(UNCURSED_PP_TRACE_VARS_EACH1, ~, u_seq)
#define TRACE_VARS(u_vars) UNCURSED_PP_TRACE_VARS_PICK1(BOOST_PP_SEQ_SIZE(u_vars))(u_vars)

/* # `e` and `d` in the body survive - they'd both be captured without
 * # the pragma (e by the element slot, d by the data slot)
 * #?  TRACE_VARS((rate))
 * #=>     int e = snapshot(rate);
 * #=>     log(&d, &e);
 */

/* #?  TRACE_VARS((rate)(depth))
 * #=>     int e = snapshot(rate);
 * #=>     log(&d, &e);
 * #=>     int e = snapshot(depth);
 * #=>     log(&d, &e);
 */
