/* Generated by uncursed-pp from 21-conversions.uncursed — do not edit. */
#pragma once

#include <boost/preprocessor/cat.hpp>
#include <boost/preprocessor/control/iif.hpp>
#include <boost/preprocessor/facilities/is_empty_variadic.hpp>
#include <boost/preprocessor/seq/for_each.hpp>
#include <boost/preprocessor/seq/size.hpp>
#include <boost/preprocessor/tuple/size.hpp>
#include <boost/preprocessor/tuple/to_seq.hpp>
#include "uncursed_pp_runtime.h"

/* # ── Converting between shapes: seq ⇄ tuple ⇄ comma list ──────────────
 * #
 * # The three variable-count shapes and how to move between them:
 * #
 * #   AUTOMATIC   variadic → seq      the body already sees a variadic
 * #                                   parameter as a seq, and passing it
 * #                                   on ({{$items}}) hands the converted
 * #                                   seq to any seq-typed macro
 * #   to_seq($t)  tuple → seq         (a, b, c)  →  (a)(b)(c); identity
 * #                                   on seqs; a hybrid converts its TAIL
 * #   to_tuple($s) seq → tuple        (a)(b)(c)  →  (a, b, c); identity
 * #                                   on tuples
 * #   remove_parens($t)  tuple → bare commas   (a, b, c)  →  a, b, c
 * #   @join $xs with ", "  seq → bare commas   the identity comma join
 * #
 * # Rules: seqs cannot be empty, so to_seq(()) is a call-site error like
 * # any other empty seq; to_tuple's result obeys tuple semantics (len(),
 * # [i], is_empty(), iteration — all tail-scoped for hybrids).
 * #
 * # Scenario: one comma-list call site fans out to seq-shaped helpers.
 */

/* uncursed-pp source:
 * @macro DECLARE_ALL($types: seq<token>)
 * @for $t in $types
 * {{$t}} {{concat(make_, $t)}}(void);
 * @end
 * @endmacro
 */
#define UNCURSED_PP_DECLARE_ALL_EACH1(r, d, e) e BOOST_PP_CAT(make_, e)(void);
#define UNCURSED_PP_DECLARE_ALL_CH1_1(e) e BOOST_PP_CAT(make_, e)(void);
#define UNCURSED_PP_DECLARE_ALL_CH1_2(e) e BOOST_PP_CAT(make_, e)(void); UNCURSED_PP_DECLARE_ALL_CH1_1
#define UNCURSED_PP_DECLARE_ALL_CH1_3(e) e BOOST_PP_CAT(make_, e)(void); UNCURSED_PP_DECLARE_ALL_CH1_2
#define UNCURSED_PP_DECLARE_ALL_CH1_4(e) e BOOST_PP_CAT(make_, e)(void); UNCURSED_PP_DECLARE_ALL_CH1_3
#define UNCURSED_PP_DECLARE_ALL_CH1_5(e) e BOOST_PP_CAT(make_, e)(void); UNCURSED_PP_DECLARE_ALL_CH1_4
#define UNCURSED_PP_DECLARE_ALL_CH1_6(e) e BOOST_PP_CAT(make_, e)(void); UNCURSED_PP_DECLARE_ALL_CH1_5
#define UNCURSED_PP_DECLARE_ALL_CH1_7(e) e BOOST_PP_CAT(make_, e)(void); UNCURSED_PP_DECLARE_ALL_CH1_6
#define UNCURSED_PP_DECLARE_ALL_CH1_8(e) e BOOST_PP_CAT(make_, e)(void); UNCURSED_PP_DECLARE_ALL_CH1_7
#define UNCURSED_PP_DECLARE_ALL_CH1_9(e) e BOOST_PP_CAT(make_, e)(void); UNCURSED_PP_DECLARE_ALL_CH1_8
#define UNCURSED_PP_DECLARE_ALL_CH1_10(e) e BOOST_PP_CAT(make_, e)(void); UNCURSED_PP_DECLARE_ALL_CH1_9
#define UNCURSED_PP_DECLARE_ALL_CH1_11(e) e BOOST_PP_CAT(make_, e)(void); UNCURSED_PP_DECLARE_ALL_CH1_10
#define UNCURSED_PP_DECLARE_ALL_CH1_12(e) e BOOST_PP_CAT(make_, e)(void); UNCURSED_PP_DECLARE_ALL_CH1_11
#define UNCURSED_PP_DECLARE_ALL_CH1_13(e) e BOOST_PP_CAT(make_, e)(void); UNCURSED_PP_DECLARE_ALL_CH1_12
#define UNCURSED_PP_DECLARE_ALL_CH1_14(e) e BOOST_PP_CAT(make_, e)(void); UNCURSED_PP_DECLARE_ALL_CH1_13
#define UNCURSED_PP_DECLARE_ALL_CH1_15(e) e BOOST_PP_CAT(make_, e)(void); UNCURSED_PP_DECLARE_ALL_CH1_14
#define UNCURSED_PP_DECLARE_ALL_CH1_16(e) e BOOST_PP_CAT(make_, e)(void); UNCURSED_PP_DECLARE_ALL_CH1_15
#define UNCURSED_PP_DECLARE_ALL_SMALL1(seq) BOOST_PP_CAT(UNCURSED_PP_DECLARE_ALL_CH1_, BOOST_PP_SEQ_SIZE(seq)) seq
#define UNCURSED_PP_DECLARE_ALL_PICK1(n) BOOST_PP_IIF(BOOST_PP_CAT(UNCURSED_PP_LE16_, n), UNCURSED_PP_DECLARE_ALL_SMALL1, UNCURSED_PP_DECLARE_ALL_BIG1)
#define UNCURSED_PP_DECLARE_ALL_BIG1(seq) BOOST_PP_SEQ_FOR_EACH(UNCURSED_PP_DECLARE_ALL_EACH1, ~, seq)
#define DECLARE_ALL(types) UNCURSED_PP_DECLARE_ALL_PICK1(BOOST_PP_SEQ_SIZE(types))(types)

/* uncursed-pp source:
 * @macro EXPORTS($row: tuple)
 * /* {{len($row)}} exports * /
 * DECLARE_ALL({{to_seq($row)}})
 * @endmacro
 */
#define UNCURSED_PP_EXPORTS_ISNIL(x) BOOST_PP_IS_EMPTY x
#define EXPORTS(row) \
    /* BOOST_PP_IIF(UNCURSED_PP_EXPORTS_ISNIL(row), 0, BOOST_PP_TUPLE_SIZE(row)) exports */ \
    DECLARE_ALL(BOOST_PP_TUPLE_TO_SEQ(row))

/* #?  EXPORTS((widget, gadget))
 * #=>     widget make_widget(void);
 * #=>     gadget make_gadget(void);
 */
