/* Generated by uncursed-pp from 23-meta-templating.uncursed — do not edit. */
#pragma once

/* uncursed-pp source:
 * # ── Meta-templating: Jinja2 at generation time ───────────────────────
 * #
 * # Every .uncursed source passes through Jinja2 before the DSL parser,
 * # using alternative delimiters so nothing clashes with uncursed-pp's
 * # own syntax:
 * #
 * #   statements   <<% ... %>>     (set / for / if / macro / include ...)
 * #   expressions  <<{ ... }>>
 * #   comments     <<# ... #>>
 * #
 * # This is a THIRD clock: Jinja2 runs at generation time (Python),
 * # the emitted Boost.PP machinery runs at C preprocessing time, and the
 * # expansion is plain C. Use Jinja2 when the set of MACROS themselves is
 * # data-driven; use @for/@join when each macro's expansion is data-driven.
 * # A source with no meta markers skips Jinja2 entirely.
 * #
 * # Scenario: one accessor macro per field, from a single Python list.
 * @macro GET_ID($obj)
 * ((uint32_t)(({{$obj}})->id))
 * @endmacro
 */
#define GET_ID(obj) ((uint32_t)((obj)->id))

/* uncursed-pp source:
 * @macro GET_NAME($obj)
 * ((const char *)(({{$obj}})->name))
 * @endmacro
 */
#define GET_NAME(obj) ((const char *)((obj)->name))

/* #?  GET_ID(o)
 * #=>     ((uint32_t)((o)->id))
 */

/* #?  GET_NAME(o)
 * #=>     ((const char *)((o)->name))
 */
