/* Generated by uncursed-pp from 24-optional-fields.uncursed — do not edit. */
#pragma once

#include <boost/preprocessor/cat.hpp>
#include <boost/preprocessor/control/iif.hpp>
#include <boost/preprocessor/seq/for_each.hpp>
#include <boost/preprocessor/seq/size.hpp>
#include <boost/preprocessor/tuple/elem.hpp>
#include <boost/preprocessor/tuple/size.hpp>
#include "uncursed_pp_runtime.h"

/* # ── Optional trailing tuple fields ───────────────────────────────────
 * #
 * # After a tuple's required fields, trailing fields can be optional in
 * # two ways:
 * #
 * #   $field = value   omitted at the call site -> the default fills in
 * #   $field?          omitted at the call site -> truly ABSENT
 * #
 * # For a `?` field, `has($t.$field)` is 1/0 at C compile time, and
 * # accessing an absent field expands to zero tokens. The call site
 * # passes any prefix: (a), (a, b), (a, b, c) - the width is dispatched
 * # when the C compiler expands the macro, like everything else here.
 * #
 * # Scenario: a register description where the reset value is optional
 * # and the access qualifier defaults.
 */

/* uncursed-pp source:
 * @macro REG($r: tuple<$name, $addr, $qual = volatile, $reset?>)
 * enum { {{concat($r.$name, _ADDR)}} = {{$r.$addr}} };
 * @if has($r.$reset)
 * static {{$r.$qual}} int {{concat($r.$name, _reset)}} = {{$r.$reset}};
 * @end
 * @endmacro
 */
#define UNCURSED_PP_REG_THEN1(r) static BOOST_PP_TUPLE_ELEM(2, r) int BOOST_PP_CAT(BOOST_PP_TUPLE_ELEM(0, r), _reset) = BOOST_PP_TUPLE_ELEM(3, r);
#define UNCURSED_PP_REG_ELSE1(r)
#define UNCURSED_PP_REG_NF1(t) UNCURSED_PP_REG_NF1_D(BOOST_PP_TUPLE_SIZE(t), t)
#define UNCURSED_PP_REG_NF1_D(...) UNCURSED_PP_REG_NF1_I(__VA_ARGS__)
#define UNCURSED_PP_REG_NF1_I(n, t) UNCURSED_PP_REG_NF1_ ## n t
#define UNCURSED_PP_REG_ERROR_TOO_FEW_TUPLE_FIELDS(need, got)
#define UNCURSED_PP_REG_NF1_1(...) UNCURSED_PP_REG_ERROR_TOO_FEW_TUPLE_FIELDS(~)
#define UNCURSED_PP_REG_NF1_2(f0, f1) (f0, f1, volatile, , 2)
#define UNCURSED_PP_REG_NF1_3(f0, f1, f2) (f0, f1, f2, , 3)
#define UNCURSED_PP_REG_NF1_4(f0, f1, f2, f3) (f0, f1, f2, f3, 4)
#define UNCURSED_PP_REG_HP1_2 0
#define UNCURSED_PP_REG_HP1_3 0
#define UNCURSED_PP_REG_HP1_4 1
#define REG(r) \
    enum { BOOST_PP_CAT(BOOST_PP_TUPLE_ELEM(0, UNCURSED_PP_REG_NF1(r)), _ADDR) = BOOST_PP_TUPLE_ELEM(1, UNCURSED_PP_REG_NF1(r)) }; \
    BOOST_PP_IIF(BOOST_PP_CAT(UNCURSED_PP_REG_HP1_, BOOST_PP_TUPLE_ELEM(4, UNCURSED_PP_REG_NF1(r))), UNCURSED_PP_REG_THEN1, UNCURSED_PP_REG_ELSE1)(UNCURSED_PP_REG_NF1(r))

/* # All four fields:
 * #?  REG((CTRL, 0x40, volatile, 0x1))
 * #=>     enum { CTRL_ADDR = 0x40 }; static volatile int CTRL_reset = 0x1;
 */

/* # Reset omitted - the @if branch vanishes entirely:
 * #?  REG((STAT, 0x44))
 * #=>     enum { STAT_ADDR = 0x44 };
 */

/* uncursed-pp source:
 * # It composes: optional-field tuples as seq elements, loop-unpacked.
 * @macro FIELDS($fs: seq<tuple<$name, $type = int>>)
 * @for ($name, $type) in $fs
 * {{$type}} {{$name}};
 * @end
 * @endmacro
 */
#define UNCURSED_PP_FIELDS_AP1(name, type) type name;
#define UNCURSED_PP_FIELDS_AP1_N(t) UNCURSED_PP_FIELDS_AP1 t
#define UNCURSED_PP_FIELDS_EACH1(r, d, e) UNCURSED_PP_FIELDS_AP1_N(UNCURSED_PP_FIELDS_NF1(e))
#define UNCURSED_PP_FIELDS_CH1_1(e) UNCURSED_PP_FIELDS_AP1_N(UNCURSED_PP_FIELDS_NF1(e))
#define UNCURSED_PP_FIELDS_CH1_2(e) UNCURSED_PP_FIELDS_AP1_N(UNCURSED_PP_FIELDS_NF1(e)) UNCURSED_PP_FIELDS_CH1_1
#define UNCURSED_PP_FIELDS_CH1_3(e) UNCURSED_PP_FIELDS_AP1_N(UNCURSED_PP_FIELDS_NF1(e)) UNCURSED_PP_FIELDS_CH1_2
#define UNCURSED_PP_FIELDS_CH1_4(e) UNCURSED_PP_FIELDS_AP1_N(UNCURSED_PP_FIELDS_NF1(e)) UNCURSED_PP_FIELDS_CH1_3
#define UNCURSED_PP_FIELDS_CH1_5(e) UNCURSED_PP_FIELDS_AP1_N(UNCURSED_PP_FIELDS_NF1(e)) UNCURSED_PP_FIELDS_CH1_4
#define UNCURSED_PP_FIELDS_CH1_6(e) UNCURSED_PP_FIELDS_AP1_N(UNCURSED_PP_FIELDS_NF1(e)) UNCURSED_PP_FIELDS_CH1_5
#define UNCURSED_PP_FIELDS_CH1_7(e) UNCURSED_PP_FIELDS_AP1_N(UNCURSED_PP_FIELDS_NF1(e)) UNCURSED_PP_FIELDS_CH1_6
#define UNCURSED_PP_FIELDS_CH1_8(e) UNCURSED_PP_FIELDS_AP1_N(UNCURSED_PP_FIELDS_NF1(e)) UNCURSED_PP_FIELDS_CH1_7
#define UNCURSED_PP_FIELDS_CH1_9(e) UNCURSED_PP_FIELDS_AP1_N(UNCURSED_PP_FIELDS_NF1(e)) UNCURSED_PP_FIELDS_CH1_8
#define UNCURSED_PP_FIELDS_CH1_10(e) UNCURSED_PP_FIELDS_AP1_N(UNCURSED_PP_FIELDS_NF1(e)) UNCURSED_PP_FIELDS_CH1_9
#define UNCURSED_PP_FIELDS_CH1_11(e) UNCURSED_PP_FIELDS_AP1_N(UNCURSED_PP_FIELDS_NF1(e)) UNCURSED_PP_FIELDS_CH1_10
#define UNCURSED_PP_FIELDS_CH1_12(e) UNCURSED_PP_FIELDS_AP1_N(UNCURSED_PP_FIELDS_NF1(e)) UNCURSED_PP_FIELDS_CH1_11
#define UNCURSED_PP_FIELDS_CH1_13(e) UNCURSED_PP_FIELDS_AP1_N(UNCURSED_PP_FIELDS_NF1(e)) UNCURSED_PP_FIELDS_CH1_12
#define UNCURSED_PP_FIELDS_CH1_14(e) UNCURSED_PP_FIELDS_AP1_N(UNCURSED_PP_FIELDS_NF1(e)) UNCURSED_PP_FIELDS_CH1_13
#define UNCURSED_PP_FIELDS_CH1_15(e) UNCURSED_PP_FIELDS_AP1_N(UNCURSED_PP_FIELDS_NF1(e)) UNCURSED_PP_FIELDS_CH1_14
#define UNCURSED_PP_FIELDS_CH1_16(e) UNCURSED_PP_FIELDS_AP1_N(UNCURSED_PP_FIELDS_NF1(e)) UNCURSED_PP_FIELDS_CH1_15
#define UNCURSED_PP_FIELDS_NF1(t) UNCURSED_PP_FIELDS_NF1_D(BOOST_PP_TUPLE_SIZE(t), t)
#define UNCURSED_PP_FIELDS_NF1_D(...) UNCURSED_PP_FIELDS_NF1_I(__VA_ARGS__)
#define UNCURSED_PP_FIELDS_NF1_I(n, t) UNCURSED_PP_FIELDS_NF1_ ## n t
#define UNCURSED_PP_FIELDS_NF1_1(f0) (f0, int)
#define UNCURSED_PP_FIELDS_NF1_2(f0, f1) (f0, f1)
#define UNCURSED_PP_FIELDS_SMALL1(seq) BOOST_PP_CAT(UNCURSED_PP_FIELDS_CH1_, BOOST_PP_SEQ_SIZE(seq)) seq
#define UNCURSED_PP_FIELDS_PICK1(n) BOOST_PP_IIF(BOOST_PP_CAT(UNCURSED_PP_LE16_, n), UNCURSED_PP_FIELDS_SMALL1, UNCURSED_PP_FIELDS_BIG1)
#define UNCURSED_PP_FIELDS_BIG1(seq) BOOST_PP_SEQ_FOR_EACH(UNCURSED_PP_FIELDS_EACH1, ~, seq)
#define FIELDS(fs) UNCURSED_PP_FIELDS_PICK1(BOOST_PP_SEQ_SIZE(fs))(fs)

/* #?  FIELDS(((n))((f, float)))
 * #=>     int n; float f;
 */
