/* Common runtime macros, shared by all cursedpp-generated headers.
   Generated by cursedpp — do not edit. */
#pragma once

#include <boost/preprocessor/tuple/replace.hpp>

#define CURSEDPP_KW_PUT(state, ...) CURSEDPP_KW_PUT_I(state, __VA_ARGS__)
#define CURSEDPP_KW_PUT_I(state, i, v) BOOST_PP_TUPLE_REPLACE(state, i, v)
