/* Generated by cursedpp from declare_fields.cursed — do not edit. */
#pragma once

#include <boost/preprocessor.hpp>

#define CURSEDPP_DECLARE_FIELDS_EACH1(r, d, e) BOOST_PP_TUPLE_ELEM(2, 0, e) BOOST_PP_TUPLE_ELEM(2, 1, e);
#define DECLARE_FIELDS(fields) BOOST_PP_SEQ_FOR_EACH(CURSEDPP_DECLARE_FIELDS_EACH1, ~, fields)
