/* Generated by cursedpp from pair.cursed — do not edit. */
#pragma once

#include <boost/preprocessor.hpp>

#define PAIR(p) S{ BOOST_PP_REMOVE_PARENS(BOOST_PP_TUPLE_ELEM(2, 0, p)) | BOOST_PP_TUPLE_ELEM(2, 1, p) }
