/* Generated by cursedpp from proto.cursed — do not edit. */
#pragma once

#include <boost/preprocessor.hpp>

#define CURSEDPP_PROTO_EACH1(r, d, i, e) BOOST_PP_COMMA_IF(i) BOOST_PP_TUPLE_ELEM(2, 0, e) BOOST_PP_TUPLE_ELEM(2, 1, e)
#define PROTO(name, args) void name(BOOST_PP_SEQ_FOR_EACH_I(CURSEDPP_PROTO_EACH1, ~, args));
