/* Generated by cursedpp from proto.cursed — do not edit. */
#pragma once

#include <boost/preprocessor/punctuation/comma_if.hpp>
#include <boost/preprocessor/seq/for_each_i.hpp>
#include <boost/preprocessor/tuple/elem.hpp>

#define CURSEDPP_PROTO_EACH1(r, d, i, e) BOOST_PP_COMMA_IF(i) BOOST_PP_TUPLE_ELEM(0, e) BOOST_PP_TUPLE_ELEM(1, e)
#define PROTO(name, args) void name(BOOST_PP_SEQ_FOR_EACH_I(CURSEDPP_PROTO_EACH1, ~, args));
