/* Generated by cursedpp from reflect.cursed — do not edit. */
#pragma once

#include <boost/preprocessor/cat.hpp>
#include <boost/preprocessor/seq/for_each.hpp>
#include <boost/preprocessor/seq/size.hpp>
#include <boost/preprocessor/stringize.hpp>
#include <boost/preprocessor/tuple/elem.hpp>
#include <boost/preprocessor/variadic/to_seq.hpp>

#define CURSEDPP_DEFINE_STRUCT_EACH1(r, d, e) BOOST_PP_TUPLE_ELEM(0, e) BOOST_PP_TUPLE_ELEM(1, e);
#define DEFINE_STRUCT(sname, fields) \
    typedef struct { \
    BOOST_PP_SEQ_FOR_EACH(CURSEDPP_DEFINE_STRUCT_EACH1, ~, fields) \
    } sname;

#define CURSEDPP_DEFINE_FIELD_TABLE_EACH1(r, d, e) { BOOST_PP_STRINGIZE(BOOST_PP_TUPLE_ELEM(1, e)), BOOST_PP_STRINGIZE(BOOST_PP_TUPLE_ELEM(0, e)), offsetof(d, BOOST_PP_TUPLE_ELEM(1, e)) },
#define DEFINE_FIELD_TABLE(sname, fields) \
    static const cursed_field BOOST_PP_CAT(sname, _fields)[] = { \
    BOOST_PP_SEQ_FOR_EACH(CURSEDPP_DEFINE_FIELD_TABLE_EACH1, sname, fields) \
    }; \
    enum { BOOST_PP_CAT(sname, _field_count) = BOOST_PP_SEQ_SIZE(fields) };

#define CURSEDPP_DEFINE_PRINTER_EACH1(r, d, e) printf(" " BOOST_PP_STRINGIZE(BOOST_PP_TUPLE_ELEM(1, e)) " = " BOOST_PP_TUPLE_ELEM(2, e) "\n", v->BOOST_PP_TUPLE_ELEM(1, e));
#define DEFINE_PRINTER(sname, fields) \
    static void BOOST_PP_CAT(print_, sname)(const sname *v) { \
    BOOST_PP_SEQ_FOR_EACH(CURSEDPP_DEFINE_PRINTER_EACH1, ~, fields) \
    }

#define REFLECT(sname, ...) \
    DEFINE_STRUCT(sname, BOOST_PP_VARIADIC_TO_SEQ(__VA_ARGS__)) \
    DEFINE_FIELD_TABLE(sname, BOOST_PP_VARIADIC_TO_SEQ(__VA_ARGS__)) \
    DEFINE_PRINTER(sname, BOOST_PP_VARIADIC_TO_SEQ(__VA_ARGS__))
