/* Generated by cursedpp from widget.cursed — do not edit. */
#pragma once

#include <boost/preprocessor/cat.hpp>
#include <boost/preprocessor/facilities/overload.hpp>
#include <boost/preprocessor/seq/fold_left.hpp>
#include <boost/preprocessor/tuple/elem.hpp>
#include <boost/preprocessor/variadic/to_seq.hpp>
#include "cursedpp_runtime.h"

#define CURSEDPP_MAKE_WIDGET_SET_WIDTH(v) 0, v
#define CURSEDPP_MAKE_WIDGET_SET_HEIGHT(v) 1, v
#define CURSEDPP_MAKE_WIDGET_SET_FLAGS(v) 2, v
#define CURSEDPP_MAKE_WIDGET_STEP(s, state, e) CURSEDPP_KW_PUT(state, BOOST_PP_CAT(CURSEDPP_MAKE_WIDGET_SET_, e))
#define CURSEDPP_MAKE_WIDGET_BODY(name, WIDTH, HEIGHT, FLAGS) struct widget name = { WIDTH, HEIGHT, FLAGS };
#define CURSEDPP_MAKE_WIDGET_UNPACK(name, state) CURSEDPP_MAKE_WIDGET_BODY(name, BOOST_PP_TUPLE_ELEM(0, state), BOOST_PP_TUPLE_ELEM(1, state), BOOST_PP_TUPLE_ELEM(2, state))
#define CURSEDPP_MAKE_WIDGET_KW(name, ...) CURSEDPP_MAKE_WIDGET_UNPACK(name, BOOST_PP_SEQ_FOLD_LEFT(CURSEDPP_MAKE_WIDGET_STEP, (100, 50, ), BOOST_PP_VARIADIC_TO_SEQ(__VA_ARGS__)))
#define CURSEDPP_MAKE_WIDGET_1(name) CURSEDPP_MAKE_WIDGET_BODY(name, 100, 50, )
#define CURSEDPP_MAKE_WIDGET_2 CURSEDPP_MAKE_WIDGET_KW
#define CURSEDPP_MAKE_WIDGET_3 CURSEDPP_MAKE_WIDGET_KW
#define CURSEDPP_MAKE_WIDGET_4 CURSEDPP_MAKE_WIDGET_KW
#define MAKE_WIDGET(...) BOOST_PP_OVERLOAD(CURSEDPP_MAKE_WIDGET_, __VA_ARGS__)(__VA_ARGS__)
