/* Generated by uncursed-pp from access.uncursed — do not edit. */
#pragma once

#include <boost/preprocessor/seq/elem.hpp>
#include <boost/preprocessor/tuple/elem.hpp>

/* uncursed-pp source:
 * # Element access: seq indexing and chained seq[i].field access.
 * @macro HEADTAIL(xs: seq<token>)
 * {{xs[0]}} ... {{xs[1]}}
 * @endmacro
 */
#define HEADTAIL(xs) BOOST_PP_SEQ_ELEM(0, xs) ... BOOST_PP_SEQ_ELEM(1, xs)

/* uncursed-pp source:
 * @macro SECOND_NAME(xs: seq<tuple<t, n>>)
 * {{xs[1].n}}
 * @endmacro
 */
#define SECOND_NAME(xs) BOOST_PP_TUPLE_ELEM(1, BOOST_PP_SEQ_ELEM(1, xs))

/* # ── invocation specs (verified through cc -E by the spec harness) ──
 * #?  HEADTAIL((a)(b))
 * #=>     a ... b
 */

/* #?  SECOND_NAME(((int, x))((float, y)))
 * #=>     y
 */
