/* Generated by uncursed-pp from access.uncursed — do not edit. */
#pragma once

#include <boost/preprocessor/facilities/is_empty_variadic.hpp>
#include <boost/preprocessor/seq/elem.hpp>
#include <boost/preprocessor/tuple/elem.hpp>

/* uncursed-pp source:
 * # Element access: seq indexing and chained seq[i].field access.
 * @macro HEADTAIL($xs: seq<token>)
 * {{$xs[0]}} ... {{$xs[1]}}
 * @endmacro
 */
#define HEADTAIL(xs) BOOST_PP_SEQ_ELEM(0, xs) ... BOOST_PP_SEQ_ELEM(1, xs)

/* uncursed-pp source:
 * @macro SECOND_NAME($xs: seq<tuple<$t, $n>>)
 * {{$xs[1].$n}}
 * @endmacro
 */
#define SECOND_NAME(xs) BOOST_PP_TUPLE_ELEM(1, BOOST_PP_SEQ_ELEM(1, xs))

/* # ── invocation specs (verified through cc -E by the spec harness) ──
 * #?  HEADTAIL((a)(b))
 * #=>     a ... b
 */

/* #?  SECOND_NAME(((int, x))((float, y)))
 * #=>     y
 */

/* uncursed-pp source:
 * # is_empty($p) is a WHOLE-value use: it must consult the tuple itself,
 * # never a stray identifier left behind by the spread pass
 * @macro PROBE($p: tuple<$x, $y>)
 * {{$p.$x}}/{{$p.$y}} empty={{is_empty($p)}}
 * @endmacro
 */
#define PROBE(p) BOOST_PP_TUPLE_ELEM(0, p)/BOOST_PP_TUPLE_ELEM(1, p) empty=BOOST_PP_IS_EMPTY(p)

/* #?  PROBE((3, 4))
 * #=>     3/4 empty=0
 */
