/* Generated by uncursed-pp from convert.uncursed — do not edit. */
#pragma once

#include <boost/preprocessor/cat.hpp>
#include <boost/preprocessor/control/iif.hpp>
#include <boost/preprocessor/facilities/is_empty_variadic.hpp>
#include <boost/preprocessor/punctuation/remove_parens.hpp>
#include <boost/preprocessor/seq/for_each.hpp>
#include <boost/preprocessor/seq/size.hpp>
#include <boost/preprocessor/seq/to_tuple.hpp>
#include <boost/preprocessor/tuple/elem.hpp>
#include <boost/preprocessor/tuple/size.hpp>
#include <boost/preprocessor/tuple/to_seq.hpp>
#include "uncursed_pp_runtime.h"

/* # Shape conversions: to_seq() / to_tuple() bridge the two variable-count
 * # shapes; identity on already-right-shaped values; hybrids convert their
 * # TAIL. Composition is the point: a tuple<T...> value can now feed any
 * # seq-typed macro.
 */

/* uncursed-pp source:
 * @macro TAKES_SEQ($xs: seq<token>)
 * @for $x in $xs
 * f({{$x}});
 * @end
 * @endmacro
 */
#define UNCURSED_PP_CONVERT_H1(r, d, e) d(e);
#define UNCURSED_PP_TAKES_SEQ_CH1_1(e) f(e);
#define UNCURSED_PP_TAKES_SEQ_CH1_2(e) f(e); UNCURSED_PP_TAKES_SEQ_CH1_1
#define UNCURSED_PP_TAKES_SEQ_CH1_3(e) f(e); UNCURSED_PP_TAKES_SEQ_CH1_2
#define UNCURSED_PP_TAKES_SEQ_CH1_4(e) f(e); UNCURSED_PP_TAKES_SEQ_CH1_3
#define UNCURSED_PP_TAKES_SEQ_CH1_5(e) f(e); UNCURSED_PP_TAKES_SEQ_CH1_4
#define UNCURSED_PP_TAKES_SEQ_CH1_6(e) f(e); UNCURSED_PP_TAKES_SEQ_CH1_5
#define UNCURSED_PP_TAKES_SEQ_CH1_7(e) f(e); UNCURSED_PP_TAKES_SEQ_CH1_6
#define UNCURSED_PP_TAKES_SEQ_CH1_8(e) f(e); UNCURSED_PP_TAKES_SEQ_CH1_7
#define UNCURSED_PP_TAKES_SEQ_CH1_9(e) f(e); UNCURSED_PP_TAKES_SEQ_CH1_8
#define UNCURSED_PP_TAKES_SEQ_CH1_10(e) f(e); UNCURSED_PP_TAKES_SEQ_CH1_9
#define UNCURSED_PP_TAKES_SEQ_CH1_11(e) f(e); UNCURSED_PP_TAKES_SEQ_CH1_10
#define UNCURSED_PP_TAKES_SEQ_CH1_12(e) f(e); UNCURSED_PP_TAKES_SEQ_CH1_11
#define UNCURSED_PP_TAKES_SEQ_CH1_13(e) f(e); UNCURSED_PP_TAKES_SEQ_CH1_12
#define UNCURSED_PP_TAKES_SEQ_CH1_14(e) f(e); UNCURSED_PP_TAKES_SEQ_CH1_13
#define UNCURSED_PP_TAKES_SEQ_CH1_15(e) f(e); UNCURSED_PP_TAKES_SEQ_CH1_14
#define UNCURSED_PP_TAKES_SEQ_CH1_16(e) f(e); UNCURSED_PP_TAKES_SEQ_CH1_15
#define UNCURSED_PP_TAKES_SEQ_SMALL1(seq) BOOST_PP_CAT(UNCURSED_PP_TAKES_SEQ_CH1_, BOOST_PP_SEQ_SIZE(seq)) seq
#define UNCURSED_PP_TAKES_SEQ_PICK1(n) BOOST_PP_IIF(BOOST_PP_CAT(UNCURSED_PP_LE16_, n), UNCURSED_PP_TAKES_SEQ_SMALL1, UNCURSED_PP_TAKES_SEQ_BIG1)
#define UNCURSED_PP_TAKES_SEQ_BIG1(seq) BOOST_PP_SEQ_FOR_EACH(UNCURSED_PP_CONVERT_H1, f, seq)
#define TAKES_SEQ(xs) UNCURSED_PP_TAKES_SEQ_PICK1(BOOST_PP_SEQ_SIZE(xs))(xs)

/* uncursed-pp source:
 * @macro FROM_TUPLE($row: tuple)
 * TAKES_SEQ({{to_seq($row)}})
 * @endmacro
 */
#define FROM_TUPLE(row) TAKES_SEQ(BOOST_PP_TUPLE_TO_SEQ(row))

/* #?  FROM_TUPLE((a, b, c))
 * #=>     f(a); f(b); f(c);
 */

/* uncursed-pp source:
 * # seq -> tuple, then tuple ops apply: len() and remove_parens()
 * @macro SEQ_STATS($xs: seq<token>)
 * @let $t := to_tuple($xs)
 * count {{len($t)}}: {{remove_parens($t)}}
 * @endmacro
 */
#define UNCURSED_PP_SEQ_STATS_ISNIL(x) BOOST_PP_IS_EMPTY x
#define SEQ_STATS(xs) count BOOST_PP_IIF(UNCURSED_PP_SEQ_STATS_ISNIL(BOOST_PP_SEQ_TO_TUPLE(xs)), 0, BOOST_PP_TUPLE_SIZE(BOOST_PP_SEQ_TO_TUPLE(xs))): BOOST_PP_REMOVE_PARENS(BOOST_PP_SEQ_TO_TUPLE(xs))

/* #?  SEQ_STATS((p)(q)(r))
 * #=>     count 3: p, q, r
 */

/* uncursed-pp source:
 * # hybrids convert their tail (consistent with len/iteration/[i])
 * @macro TAIL_SEQ($f: tuple<$owner, token...>)
 * {{$f.$owner}}[ TAKES_SEQ({{to_seq($f)}}) ]
 * @endmacro
 */
#define UNCURSED_PP_TAIL_SEQ_TL1(t) UNCURSED_PP_TAIL_SEQ_TL1_I t
#define UNCURSED_PP_TAIL_SEQ_TL1_I(f0, ...) (__VA_ARGS__)
#define TAIL_SEQ(f) BOOST_PP_TUPLE_ELEM(0, f)[ TAKES_SEQ(BOOST_PP_TUPLE_TO_SEQ(UNCURSED_PP_TAIL_SEQ_TL1(f))) ]

/* #?  TAIL_SEQ((root, x, y))
 * #=>     root[ f(x); f(y); ]
 */

/* uncursed-pp source:
 * # fixed named tuples convert too - the names are just access sugar
 * @macro SPLIT($p: tuple<$x, $y>)
 * @let $s := to_seq($p)
 * @for $e in $s
 * item({{$e}});
 * @end
 * first={{$p.$x}}
 * @endmacro
 */
#define UNCURSED_PP_SPLIT_CH1_1(e) item(e);
#define UNCURSED_PP_SPLIT_CH1_2(e) item(e); UNCURSED_PP_SPLIT_CH1_1
#define UNCURSED_PP_SPLIT_CH1_3(e) item(e); UNCURSED_PP_SPLIT_CH1_2
#define UNCURSED_PP_SPLIT_CH1_4(e) item(e); UNCURSED_PP_SPLIT_CH1_3
#define UNCURSED_PP_SPLIT_CH1_5(e) item(e); UNCURSED_PP_SPLIT_CH1_4
#define UNCURSED_PP_SPLIT_CH1_6(e) item(e); UNCURSED_PP_SPLIT_CH1_5
#define UNCURSED_PP_SPLIT_CH1_7(e) item(e); UNCURSED_PP_SPLIT_CH1_6
#define UNCURSED_PP_SPLIT_CH1_8(e) item(e); UNCURSED_PP_SPLIT_CH1_7
#define UNCURSED_PP_SPLIT_CH1_9(e) item(e); UNCURSED_PP_SPLIT_CH1_8
#define UNCURSED_PP_SPLIT_CH1_10(e) item(e); UNCURSED_PP_SPLIT_CH1_9
#define UNCURSED_PP_SPLIT_CH1_11(e) item(e); UNCURSED_PP_SPLIT_CH1_10
#define UNCURSED_PP_SPLIT_CH1_12(e) item(e); UNCURSED_PP_SPLIT_CH1_11
#define UNCURSED_PP_SPLIT_CH1_13(e) item(e); UNCURSED_PP_SPLIT_CH1_12
#define UNCURSED_PP_SPLIT_CH1_14(e) item(e); UNCURSED_PP_SPLIT_CH1_13
#define UNCURSED_PP_SPLIT_CH1_15(e) item(e); UNCURSED_PP_SPLIT_CH1_14
#define UNCURSED_PP_SPLIT_CH1_16(e) item(e); UNCURSED_PP_SPLIT_CH1_15
#define UNCURSED_PP_SPLIT_SMALL1(seq) BOOST_PP_CAT(UNCURSED_PP_SPLIT_CH1_, BOOST_PP_SEQ_SIZE(seq)) seq
#define UNCURSED_PP_SPLIT_PICK1(n) BOOST_PP_IIF(BOOST_PP_CAT(UNCURSED_PP_LE16_, n), UNCURSED_PP_SPLIT_SMALL1, UNCURSED_PP_SPLIT_BIG1)
#define UNCURSED_PP_SPLIT_BIG1(seq) BOOST_PP_SEQ_FOR_EACH(UNCURSED_PP_CONVERT_H1, item, seq)
#define SPLIT(p) \
    UNCURSED_PP_SPLIT_PICK1(BOOST_PP_SEQ_SIZE(BOOST_PP_TUPLE_TO_SEQ(p)))(BOOST_PP_TUPLE_TO_SEQ(p)) \
    first=BOOST_PP_TUPLE_ELEM(0, p)

/* #?  SPLIT((3, 4))
 * #=>     item(3); item(4); first=3
 */
