/* Generated by uncursed-pp from lets.uncursed — do not edit. */
#pragma once

#include <boost/preprocessor/cat.hpp>
#include <boost/preprocessor/control/iif.hpp>
#include <boost/preprocessor/punctuation/comma_if.hpp>
#include <boost/preprocessor/punctuation/is_begin_parens.hpp>
#include <boost/preprocessor/punctuation/remove_parens.hpp>
#include <boost/preprocessor/seq/for_each.hpp>
#include <boost/preprocessor/seq/for_each_i.hpp>
#include <boost/preprocessor/seq/size.hpp>
#include <boost/preprocessor/tuple/elem.hpp>
#include "uncursed_pp_runtime.h"

/* uncursed-pp source:
 * # @let may capture an inline @join or @if; the rendered helper is reused
 * # at every use site. @let inside a loop body binds per element.
 * @macro CALL2($fn, $args: seq<tuple<$type, $argname>>)
 * @let $joined := @join $args with ", ": {{$argname}}@end
 * {{$fn}}({{$joined}}, {{$joined}})
 * @endmacro
 */
#define UNCURSED_PP_CALL2_AP1(type, argname) argname
#define UNCURSED_PP_CALL2_EACH1(r, d, i, e) BOOST_PP_COMMA_IF(i) UNCURSED_PP_CALL2_AP1 e
#define UNCURSED_PP_CALL2_CH1_1(e) UNCURSED_PP_CALL2_AP1 e
#define UNCURSED_PP_CALL2_CH1_2(e) UNCURSED_PP_CALL2_AP1 e, UNCURSED_PP_CALL2_CH1_1
#define UNCURSED_PP_CALL2_CH1_3(e) UNCURSED_PP_CALL2_AP1 e, UNCURSED_PP_CALL2_CH1_2
#define UNCURSED_PP_CALL2_CH1_4(e) UNCURSED_PP_CALL2_AP1 e, UNCURSED_PP_CALL2_CH1_3
#define UNCURSED_PP_CALL2_CH1_5(e) UNCURSED_PP_CALL2_AP1 e, UNCURSED_PP_CALL2_CH1_4
#define UNCURSED_PP_CALL2_CH1_6(e) UNCURSED_PP_CALL2_AP1 e, UNCURSED_PP_CALL2_CH1_5
#define UNCURSED_PP_CALL2_CH1_7(e) UNCURSED_PP_CALL2_AP1 e, UNCURSED_PP_CALL2_CH1_6
#define UNCURSED_PP_CALL2_CH1_8(e) UNCURSED_PP_CALL2_AP1 e, UNCURSED_PP_CALL2_CH1_7
#define UNCURSED_PP_CALL2_CH1_9(e) UNCURSED_PP_CALL2_AP1 e, UNCURSED_PP_CALL2_CH1_8
#define UNCURSED_PP_CALL2_CH1_10(e) UNCURSED_PP_CALL2_AP1 e, UNCURSED_PP_CALL2_CH1_9
#define UNCURSED_PP_CALL2_CH1_11(e) UNCURSED_PP_CALL2_AP1 e, UNCURSED_PP_CALL2_CH1_10
#define UNCURSED_PP_CALL2_CH1_12(e) UNCURSED_PP_CALL2_AP1 e, UNCURSED_PP_CALL2_CH1_11
#define UNCURSED_PP_CALL2_CH1_13(e) UNCURSED_PP_CALL2_AP1 e, UNCURSED_PP_CALL2_CH1_12
#define UNCURSED_PP_CALL2_CH1_14(e) UNCURSED_PP_CALL2_AP1 e, UNCURSED_PP_CALL2_CH1_13
#define UNCURSED_PP_CALL2_CH1_15(e) UNCURSED_PP_CALL2_AP1 e, UNCURSED_PP_CALL2_CH1_14
#define UNCURSED_PP_CALL2_CH1_16(e) UNCURSED_PP_CALL2_AP1 e, UNCURSED_PP_CALL2_CH1_15
#define UNCURSED_PP_CALL2_SMALL1(seq) BOOST_PP_CAT(UNCURSED_PP_CALL2_CH1_, BOOST_PP_SEQ_SIZE(seq)) seq
#define UNCURSED_PP_CALL2_PICK1(n) BOOST_PP_IIF(BOOST_PP_CAT(UNCURSED_PP_LE16_, n), UNCURSED_PP_CALL2_SMALL1, UNCURSED_PP_CALL2_BIG1)
#define UNCURSED_PP_CALL2_BIG1(seq) BOOST_PP_SEQ_FOR_EACH_I(UNCURSED_PP_CALL2_EACH1, ~, seq)
#define CALL2(fn, args) fn(UNCURSED_PP_CALL2_PICK1(BOOST_PP_SEQ_SIZE(args))(args), UNCURSED_PP_CALL2_PICK1(BOOST_PP_SEQ_SIZE(args))(args))

/* uncursed-pp source:
 * @macro PICK($x)
 * @let $norm := @if is_paren($x) {{remove_parens($x)}} @else {{$x}} @end
 * g({{$norm}})
 * @endmacro
 */
#define UNCURSED_PP_PICK_THEN1(x) BOOST_PP_REMOVE_PARENS(x)
#define UNCURSED_PP_PICK_ELSE1(x) x
#define PICK(x) g(BOOST_PP_IIF(BOOST_PP_IS_BEGIN_PARENS(x), UNCURSED_PP_PICK_THEN1, UNCURSED_PP_PICK_ELSE1)(x))

/* uncursed-pp source:
 * @macro PAIRS($xs: seq<token>)
 * @for $x in $xs
 * @let $id := concat($x, _id)
 * int {{$id}} = sizeof({{$id}});
 * @end
 * @endmacro
 */
#define UNCURSED_PP_PAIRS_EACH1(r, d, e) int BOOST_PP_CAT(e, _id) = sizeof(BOOST_PP_CAT(e, _id));
#define UNCURSED_PP_PAIRS_CH1_1(e) int BOOST_PP_CAT(e, _id) = sizeof(BOOST_PP_CAT(e, _id));
#define UNCURSED_PP_PAIRS_CH1_2(e) int BOOST_PP_CAT(e, _id) = sizeof(BOOST_PP_CAT(e, _id)); UNCURSED_PP_PAIRS_CH1_1
#define UNCURSED_PP_PAIRS_CH1_3(e) int BOOST_PP_CAT(e, _id) = sizeof(BOOST_PP_CAT(e, _id)); UNCURSED_PP_PAIRS_CH1_2
#define UNCURSED_PP_PAIRS_CH1_4(e) int BOOST_PP_CAT(e, _id) = sizeof(BOOST_PP_CAT(e, _id)); UNCURSED_PP_PAIRS_CH1_3
#define UNCURSED_PP_PAIRS_CH1_5(e) int BOOST_PP_CAT(e, _id) = sizeof(BOOST_PP_CAT(e, _id)); UNCURSED_PP_PAIRS_CH1_4
#define UNCURSED_PP_PAIRS_CH1_6(e) int BOOST_PP_CAT(e, _id) = sizeof(BOOST_PP_CAT(e, _id)); UNCURSED_PP_PAIRS_CH1_5
#define UNCURSED_PP_PAIRS_CH1_7(e) int BOOST_PP_CAT(e, _id) = sizeof(BOOST_PP_CAT(e, _id)); UNCURSED_PP_PAIRS_CH1_6
#define UNCURSED_PP_PAIRS_CH1_8(e) int BOOST_PP_CAT(e, _id) = sizeof(BOOST_PP_CAT(e, _id)); UNCURSED_PP_PAIRS_CH1_7
#define UNCURSED_PP_PAIRS_CH1_9(e) int BOOST_PP_CAT(e, _id) = sizeof(BOOST_PP_CAT(e, _id)); UNCURSED_PP_PAIRS_CH1_8
#define UNCURSED_PP_PAIRS_CH1_10(e) int BOOST_PP_CAT(e, _id) = sizeof(BOOST_PP_CAT(e, _id)); UNCURSED_PP_PAIRS_CH1_9
#define UNCURSED_PP_PAIRS_CH1_11(e) int BOOST_PP_CAT(e, _id) = sizeof(BOOST_PP_CAT(e, _id)); UNCURSED_PP_PAIRS_CH1_10
#define UNCURSED_PP_PAIRS_CH1_12(e) int BOOST_PP_CAT(e, _id) = sizeof(BOOST_PP_CAT(e, _id)); UNCURSED_PP_PAIRS_CH1_11
#define UNCURSED_PP_PAIRS_CH1_13(e) int BOOST_PP_CAT(e, _id) = sizeof(BOOST_PP_CAT(e, _id)); UNCURSED_PP_PAIRS_CH1_12
#define UNCURSED_PP_PAIRS_CH1_14(e) int BOOST_PP_CAT(e, _id) = sizeof(BOOST_PP_CAT(e, _id)); UNCURSED_PP_PAIRS_CH1_13
#define UNCURSED_PP_PAIRS_CH1_15(e) int BOOST_PP_CAT(e, _id) = sizeof(BOOST_PP_CAT(e, _id)); UNCURSED_PP_PAIRS_CH1_14
#define UNCURSED_PP_PAIRS_CH1_16(e) int BOOST_PP_CAT(e, _id) = sizeof(BOOST_PP_CAT(e, _id)); UNCURSED_PP_PAIRS_CH1_15
#define UNCURSED_PP_PAIRS_SMALL1(seq) BOOST_PP_CAT(UNCURSED_PP_PAIRS_CH1_, BOOST_PP_SEQ_SIZE(seq)) seq
#define UNCURSED_PP_PAIRS_PICK1(n) BOOST_PP_IIF(BOOST_PP_CAT(UNCURSED_PP_LE16_, n), UNCURSED_PP_PAIRS_SMALL1, UNCURSED_PP_PAIRS_BIG1)
#define UNCURSED_PP_PAIRS_BIG1(seq) BOOST_PP_SEQ_FOR_EACH(UNCURSED_PP_PAIRS_EACH1, ~, seq)
#define PAIRS(xs) UNCURSED_PP_PAIRS_PICK1(BOOST_PP_SEQ_SIZE(xs))(xs)

/* # ── invocation specs (verified through cc -E by the spec harness) ──
 * #?  CALL2(f, ((int, a))((int, b)))
 * #=>     f(a, b, a, b)
 */

/* #?  PICK((a, b))
 * #=>     g(a, b)
 */

/* #?  PICK(q)
 * #=>     g(q)
 */

/* #?  PAIRS((a)(b))
 * #=>     int a_id = sizeof(a_id); int b_id = sizeof(b_id);
 */
