/* Generated by cursedpp from mixed.cursed — do not edit. */
#pragma once

#include <boost/preprocessor/cat.hpp>
#include <boost/preprocessor/punctuation/remove_parens.hpp>
#include <boost/preprocessor/seq/elem.hpp>
#include <boost/preprocessor/seq/for_each.hpp>
#include <boost/preprocessor/seq/size.hpp>
#include <boost/preprocessor/stringize.hpp>
#include <boost/preprocessor/tuple/elem.hpp>

#define FUSE(p) BOOST_PP_CAT(BOOST_PP_TUPLE_ELEM(0, p), BOOST_PP_TUPLE_ELEM(1, p))

#define STR0(xs) BOOST_PP_STRINGIZE(BOOST_PP_SEQ_ELEM(0, xs)) / BOOST_PP_STRINGIZE(BOOST_PP_SEQ_SIZE(xs))

#define CURSEDPP_CLEAN_EACH1(r, d, e) BOOST_PP_REMOVE_PARENS(BOOST_PP_TUPLE_ELEM(0, e)) BOOST_PP_TUPLE_ELEM(1, e);
#define CLEAN(fields) BOOST_PP_SEQ_FOR_EACH(CURSEDPP_CLEAN_EACH1, ~, fields)
