/* Generated by uncursed-pp from paste.uncursed — do not edit. */
#pragma once

#include <boost/preprocessor/cat.hpp>
#include <boost/preprocessor/stringize.hpp>

/* uncursed-pp source:
 * # Explicit pasting and stringizing of computed tokens; @let chains.
 * @macro NAME_OF(x)
 * {{stringize(concat(pre_, x))}}
 * @endmacro
 */
#define NAME_OF(x) BOOST_PP_STRINGIZE(BOOST_PP_CAT(pre_, x))

/* uncursed-pp source:
 * @macro TRIPLE(a)
 * {{concat(pre_, a, _post)}}
 * @endmacro
 */
#define TRIPLE(a) BOOST_PP_CAT(pre_, BOOST_PP_CAT(a, _post))

/* uncursed-pp source:
 * @macro CHAIN(base)
 * @let a := concat(base, _mid)
 * @let b := concat(a, _end)
 * {{b}}
 * @endmacro
 */
#define CHAIN(base) BOOST_PP_CAT(BOOST_PP_CAT(base, _mid), _end)

/* # ── invocation specs (verified through cc -E by the spec harness) ──
 * #?  NAME_OF(foo)
 * #=>     "pre_foo"
 */

/* #?  TRIPLE(x)
 * #=>     pre_x_post
 */

/* #?  CHAIN(v)
 * #=>     v_mid_end
 */
