/* Generated by cursedpp from paste.cursed — do not edit. */
#pragma once

#include <boost/preprocessor/cat.hpp>
#include <boost/preprocessor/stringize.hpp>

#define NAME_OF(x) BOOST_PP_STRINGIZE(BOOST_PP_CAT(pre_, x))

#define TRIPLE(a) BOOST_PP_CAT(pre_, BOOST_PP_CAT(a, _post))

#define CHAIN(base) BOOST_PP_CAT(BOOST_PP_CAT(base, _mid), _end)
