/* Generated by cursedpp from paste.cursed — do not edit. */
#pragma once

#include <boost/preprocessor/cat.hpp>
#include <boost/preprocessor/stringize.hpp>

/* cursedpp source:
 * # Explicit pasting and stringizing of computed tokens; @let chains.
 * macro NAME_OF(x)
 * {{stringize(concat(pre_, x))}}
 * end
 */
#define NAME_OF(x) BOOST_PP_STRINGIZE(BOOST_PP_CAT(pre_, x))

/* cursedpp source:
 * macro TRIPLE(a)
 * {{concat(pre_, a, _post)}}
 * end
 */
#define TRIPLE(a) BOOST_PP_CAT(pre_, BOOST_PP_CAT(a, _post))

/* cursedpp source:
 * macro CHAIN(base)
 * @let a := concat(base, _mid)
 * @let b := concat(a, _end)
 * {{b}}
 * end
 */
#define CHAIN(base) BOOST_PP_CAT(BOOST_PP_CAT(base, _mid), _end)
