/* Generated by uncursed-pp from arg_prefix.uncursed — do not edit. */
#pragma once

#include <boost/preprocessor/cat.hpp>
#include <boost/preprocessor/control/iif.hpp>
#include <boost/preprocessor/seq/for_each.hpp>
#include <boost/preprocessor/seq/size.hpp>
#include "uncursed_pp_runtime.h"

/* # @pragma arg_prefix: every generated parameter name (user variables AND
 * # harness slots like r/d/e) is emitted with this prefix, so raw body text
 * # mentioning one of those names can never be captured at expansion time.
 */

/* uncursed-pp source:
 * # the classic capture case: body text says `e`, the loop helper's element
 * # slot is ALSO named e - unprefixed, `int e = ...` would expand wrong
 * @macro DECLARE_COUNTERS($names: seq<token>)
 * @for $x in $names
 * int e = counter({{$x}});
 * @end
 * @endmacro
 */
#define UNCURSED_PP_DECLARE_COUNTERS_EACH1(u_r, u_d, u_e) int e = counter(u_e);
#define UNCURSED_PP_DECLARE_COUNTERS_CH1_1(u_e) int e = counter(u_e);
#define UNCURSED_PP_DECLARE_COUNTERS_CH1_2(u_e) int e = counter(u_e); UNCURSED_PP_DECLARE_COUNTERS_CH1_1
#define UNCURSED_PP_DECLARE_COUNTERS_CH1_3(u_e) int e = counter(u_e); UNCURSED_PP_DECLARE_COUNTERS_CH1_2
#define UNCURSED_PP_DECLARE_COUNTERS_CH1_4(u_e) int e = counter(u_e); UNCURSED_PP_DECLARE_COUNTERS_CH1_3
#define UNCURSED_PP_DECLARE_COUNTERS_CH1_5(u_e) int e = counter(u_e); UNCURSED_PP_DECLARE_COUNTERS_CH1_4
#define UNCURSED_PP_DECLARE_COUNTERS_CH1_6(u_e) int e = counter(u_e); UNCURSED_PP_DECLARE_COUNTERS_CH1_5
#define UNCURSED_PP_DECLARE_COUNTERS_CH1_7(u_e) int e = counter(u_e); UNCURSED_PP_DECLARE_COUNTERS_CH1_6
#define UNCURSED_PP_DECLARE_COUNTERS_CH1_8(u_e) int e = counter(u_e); UNCURSED_PP_DECLARE_COUNTERS_CH1_7
#define UNCURSED_PP_DECLARE_COUNTERS_CH1_9(u_e) int e = counter(u_e); UNCURSED_PP_DECLARE_COUNTERS_CH1_8
#define UNCURSED_PP_DECLARE_COUNTERS_CH1_10(u_e) int e = counter(u_e); UNCURSED_PP_DECLARE_COUNTERS_CH1_9
#define UNCURSED_PP_DECLARE_COUNTERS_CH1_11(u_e) int e = counter(u_e); UNCURSED_PP_DECLARE_COUNTERS_CH1_10
#define UNCURSED_PP_DECLARE_COUNTERS_CH1_12(u_e) int e = counter(u_e); UNCURSED_PP_DECLARE_COUNTERS_CH1_11
#define UNCURSED_PP_DECLARE_COUNTERS_CH1_13(u_e) int e = counter(u_e); UNCURSED_PP_DECLARE_COUNTERS_CH1_12
#define UNCURSED_PP_DECLARE_COUNTERS_CH1_14(u_e) int e = counter(u_e); UNCURSED_PP_DECLARE_COUNTERS_CH1_13
#define UNCURSED_PP_DECLARE_COUNTERS_CH1_15(u_e) int e = counter(u_e); UNCURSED_PP_DECLARE_COUNTERS_CH1_14
#define UNCURSED_PP_DECLARE_COUNTERS_CH1_16(u_e) int e = counter(u_e); UNCURSED_PP_DECLARE_COUNTERS_CH1_15
#define UNCURSED_PP_DECLARE_COUNTERS_SMALL1(u_seq) BOOST_PP_CAT(UNCURSED_PP_DECLARE_COUNTERS_CH1_, BOOST_PP_SEQ_SIZE(u_seq)) u_seq
#define UNCURSED_PP_DECLARE_COUNTERS_PICK1(u_n) BOOST_PP_IIF(BOOST_PP_CAT(UNCURSED_PP_LE16_, u_n), UNCURSED_PP_DECLARE_COUNTERS_SMALL1, UNCURSED_PP_DECLARE_COUNTERS_BIG1)
#define UNCURSED_PP_DECLARE_COUNTERS_BIG1(u_seq) BOOST_PP_SEQ_FOR_EACH(UNCURSED_PP_DECLARE_COUNTERS_EACH1, ~, u_seq)
#define DECLARE_COUNTERS(u_names) UNCURSED_PP_DECLARE_COUNTERS_PICK1(BOOST_PP_SEQ_SIZE(u_names))(u_names)

/* #?  DECLARE_COUNTERS((alpha)(beta))
 * #=>     int e = counter(alpha);
 * #=>     int e = counter(beta);
 */

/* uncursed-pp source:
 * # a user variable name used as literal C text in ANOTHER macro: the
 * # generated parameter is u_d, so the d in `d.ready` survives
 * @macro POLL($flag)
 * while (!d.ready) { wait({{$flag}}); }
 * @endmacro
 */
#define POLL(u_flag) while (!d.ready) { wait(u_flag); }

/* #?  POLL(F_IRQ)
 * #=>     while (!d.ready) { wait(F_IRQ); }
 */

/* uncursed-pp source:
 * # collapse interaction: identical bodies still share one helper family
 * # with prefixed parameters (chain families move as units)
 * @macro EMIT_A($xs: seq<token>)
 * @for $x in $xs
 * emit({{$x}});
 * @end
 * @endmacro
 */
#define UNCURSED_PP_ARG_PREFIX_H1(u_r, u_d, u_e) emit(u_e);
#define UNCURSED_PP_ARG_PREFIX_HC2_1(u_e) emit(u_e);
#define UNCURSED_PP_ARG_PREFIX_HC2_2(u_e) emit(u_e); UNCURSED_PP_ARG_PREFIX_HC2_1
#define UNCURSED_PP_ARG_PREFIX_HC2_3(u_e) emit(u_e); UNCURSED_PP_ARG_PREFIX_HC2_2
#define UNCURSED_PP_ARG_PREFIX_HC2_4(u_e) emit(u_e); UNCURSED_PP_ARG_PREFIX_HC2_3
#define UNCURSED_PP_ARG_PREFIX_HC2_5(u_e) emit(u_e); UNCURSED_PP_ARG_PREFIX_HC2_4
#define UNCURSED_PP_ARG_PREFIX_HC2_6(u_e) emit(u_e); UNCURSED_PP_ARG_PREFIX_HC2_5
#define UNCURSED_PP_ARG_PREFIX_HC2_7(u_e) emit(u_e); UNCURSED_PP_ARG_PREFIX_HC2_6
#define UNCURSED_PP_ARG_PREFIX_HC2_8(u_e) emit(u_e); UNCURSED_PP_ARG_PREFIX_HC2_7
#define UNCURSED_PP_ARG_PREFIX_HC2_9(u_e) emit(u_e); UNCURSED_PP_ARG_PREFIX_HC2_8
#define UNCURSED_PP_ARG_PREFIX_HC2_10(u_e) emit(u_e); UNCURSED_PP_ARG_PREFIX_HC2_9
#define UNCURSED_PP_ARG_PREFIX_HC2_11(u_e) emit(u_e); UNCURSED_PP_ARG_PREFIX_HC2_10
#define UNCURSED_PP_ARG_PREFIX_HC2_12(u_e) emit(u_e); UNCURSED_PP_ARG_PREFIX_HC2_11
#define UNCURSED_PP_ARG_PREFIX_HC2_13(u_e) emit(u_e); UNCURSED_PP_ARG_PREFIX_HC2_12
#define UNCURSED_PP_ARG_PREFIX_HC2_14(u_e) emit(u_e); UNCURSED_PP_ARG_PREFIX_HC2_13
#define UNCURSED_PP_ARG_PREFIX_HC2_15(u_e) emit(u_e); UNCURSED_PP_ARG_PREFIX_HC2_14
#define UNCURSED_PP_ARG_PREFIX_HC2_16(u_e) emit(u_e); UNCURSED_PP_ARG_PREFIX_HC2_15
#define UNCURSED_PP_EMIT_A_SMALL1(u_seq) BOOST_PP_CAT(UNCURSED_PP_ARG_PREFIX_HC2_, BOOST_PP_SEQ_SIZE(u_seq)) u_seq
#define UNCURSED_PP_EMIT_A_PICK1(u_n) BOOST_PP_IIF(BOOST_PP_CAT(UNCURSED_PP_LE16_, u_n), UNCURSED_PP_EMIT_A_SMALL1, UNCURSED_PP_EMIT_A_BIG1)
#define UNCURSED_PP_EMIT_A_BIG1(u_seq) BOOST_PP_SEQ_FOR_EACH(UNCURSED_PP_ARG_PREFIX_H1, ~, u_seq)
#define EMIT_A(u_xs) UNCURSED_PP_EMIT_A_PICK1(BOOST_PP_SEQ_SIZE(u_xs))(u_xs)

/* uncursed-pp source:
 * @macro EMIT_B($ys: seq<token>)
 * @for $y in $ys
 * emit({{$y}});
 * @end
 * @endmacro
 */
#define UNCURSED_PP_EMIT_B_SMALL1(u_seq) BOOST_PP_CAT(UNCURSED_PP_ARG_PREFIX_HC2_, BOOST_PP_SEQ_SIZE(u_seq)) u_seq
#define UNCURSED_PP_EMIT_B_PICK1(u_n) BOOST_PP_IIF(BOOST_PP_CAT(UNCURSED_PP_LE16_, u_n), UNCURSED_PP_EMIT_B_SMALL1, UNCURSED_PP_EMIT_B_BIG1)
#define UNCURSED_PP_EMIT_B_BIG1(u_seq) BOOST_PP_SEQ_FOR_EACH(UNCURSED_PP_ARG_PREFIX_H1, ~, u_seq)
#define EMIT_B(u_ys) UNCURSED_PP_EMIT_B_PICK1(BOOST_PP_SEQ_SIZE(u_ys))(u_ys)

/* #?  EMIT_A((one)(two))
 * #=>     emit(one); emit(two);
 */

/* #?  EMIT_B((three))
 * #=>     emit(three);
 */

/* uncursed-pp source:
 * # spread tuple params: the public define's heads are prefixed exactly
 * # like the arguments it forwards (they used to disagree under arg_prefix,
 * # leaving the forward unbound)
 * @macro PT($p: tuple<$x, $y>)
 * pair({{$p.$x}}, {{$p.$y}});
 * @endmacro
 */
#define UNCURSED_PP_PT_BODY1(u_x, u_y) pair(u_x, u_y);
#define UNCURSED_PP_PT_BODY1_D(...) UNCURSED_PP_PT_BODY1(__VA_ARGS__)
#define PT(u_p) UNCURSED_PP_PT_BODY1_D(UNCURSED_PP_KW_SPREAD u_p)

/* #?  PT((3, 4))
 * #=>     pair(3, 4);
 */
