/* Generated by uncursed-pp from c_comments.uncursed — do not edit. */
#pragma once

#include <boost/preprocessor/cat.hpp>
#include <boost/preprocessor/control/iif.hpp>
#include <boost/preprocessor/seq/for_each.hpp>
#include <boost/preprocessor/seq/size.hpp>
#include "uncursed_pp_runtime.h"

/* # C /* * / comments in body text are preserved into the generated
 * # defines - documentation for whoever reads the .h - and the real
 * # preprocessor strips them at expansion time, so specs never see them.
 * # Comment BLOCKS escape a terminator: this * / stays harmless.
 */

/* uncursed-pp source:
 * @macro INIT($x)
 * setup({{$x}}); /* inline note * /
 * /* own-line note * /
 * teardown({{$x}});
 * @endmacro
 */
#define INIT(x) \
    setup(x); /* inline note */ \
    /* own-line note */ \
    teardown(x);

/* #?  INIT(dev)
 * #=>     setup(dev);
 * #=>     teardown(dev);
 */

/* uncursed-pp source:
 * # comments replicate into loop helpers (and chain members) untouched
 * @macro EACH_NOTED($xs: seq<token>)
 * @for $v in $xs
 * poke({{$v}}); /* per item * /
 * @end
 * @endmacro
 */
#define UNCURSED_PP_EACH_NOTED_EACH1(r, d, e) poke(e); /* per item */
#define UNCURSED_PP_EACH_NOTED_CH1_1(e) poke(e); /* per item */
#define UNCURSED_PP_EACH_NOTED_CH1_2(e) poke(e); /* per item */ UNCURSED_PP_EACH_NOTED_CH1_1
#define UNCURSED_PP_EACH_NOTED_CH1_3(e) poke(e); /* per item */ UNCURSED_PP_EACH_NOTED_CH1_2
#define UNCURSED_PP_EACH_NOTED_CH1_4(e) poke(e); /* per item */ UNCURSED_PP_EACH_NOTED_CH1_3
#define UNCURSED_PP_EACH_NOTED_CH1_5(e) poke(e); /* per item */ UNCURSED_PP_EACH_NOTED_CH1_4
#define UNCURSED_PP_EACH_NOTED_CH1_6(e) poke(e); /* per item */ UNCURSED_PP_EACH_NOTED_CH1_5
#define UNCURSED_PP_EACH_NOTED_CH1_7(e) poke(e); /* per item */ UNCURSED_PP_EACH_NOTED_CH1_6
#define UNCURSED_PP_EACH_NOTED_CH1_8(e) poke(e); /* per item */ UNCURSED_PP_EACH_NOTED_CH1_7
#define UNCURSED_PP_EACH_NOTED_CH1_9(e) poke(e); /* per item */ UNCURSED_PP_EACH_NOTED_CH1_8
#define UNCURSED_PP_EACH_NOTED_CH1_10(e) poke(e); /* per item */ UNCURSED_PP_EACH_NOTED_CH1_9
#define UNCURSED_PP_EACH_NOTED_CH1_11(e) poke(e); /* per item */ UNCURSED_PP_EACH_NOTED_CH1_10
#define UNCURSED_PP_EACH_NOTED_CH1_12(e) poke(e); /* per item */ UNCURSED_PP_EACH_NOTED_CH1_11
#define UNCURSED_PP_EACH_NOTED_CH1_13(e) poke(e); /* per item */ UNCURSED_PP_EACH_NOTED_CH1_12
#define UNCURSED_PP_EACH_NOTED_CH1_14(e) poke(e); /* per item */ UNCURSED_PP_EACH_NOTED_CH1_13
#define UNCURSED_PP_EACH_NOTED_CH1_15(e) poke(e); /* per item */ UNCURSED_PP_EACH_NOTED_CH1_14
#define UNCURSED_PP_EACH_NOTED_CH1_16(e) poke(e); /* per item */ UNCURSED_PP_EACH_NOTED_CH1_15
#define UNCURSED_PP_EACH_NOTED_SMALL1(seq) BOOST_PP_CAT(UNCURSED_PP_EACH_NOTED_CH1_, BOOST_PP_SEQ_SIZE(seq)) seq
#define UNCURSED_PP_EACH_NOTED_PICK1(n) BOOST_PP_IIF(BOOST_PP_CAT(UNCURSED_PP_LE16_, n), UNCURSED_PP_EACH_NOTED_SMALL1, UNCURSED_PP_EACH_NOTED_BIG1)
#define UNCURSED_PP_EACH_NOTED_BIG1(seq) BOOST_PP_SEQ_FOR_EACH(UNCURSED_PP_EACH_NOTED_EACH1, ~, seq)
#define EACH_NOTED(xs) UNCURSED_PP_EACH_NOTED_PICK1(BOOST_PP_SEQ_SIZE(xs))(xs)

/* #?  EACH_NOTED((a)(b))
 * #=>     poke(a); poke(b);
 */
