/* Generated by uncursed-pp from declare_fields.uncursed — do not edit. */
#pragma once

#include <boost/preprocessor/seq/for_each.hpp>
#include <boost/preprocessor/tuple/elem.hpp>

/* uncursed-pp source:
 * # Declare one struct field per (type, name) tuple.
 * macro DECLARE_FIELDS(fields: seq<tuple<type, name>>)
 * @for (type, name) in fields
 *   {{type}} {{name}};
 * @end
 * end
 */
#define UNCURSED_PP_DECLARE_FIELDS_AP1(type, name) type name;
#define UNCURSED_PP_DECLARE_FIELDS_EACH1(r, d, e) UNCURSED_PP_DECLARE_FIELDS_AP1 e
#define DECLARE_FIELDS(fields) BOOST_PP_SEQ_FOR_EACH(UNCURSED_PP_DECLARE_FIELDS_EACH1, ~, fields)
