/* Generated by cursedpp from getter.cursed — do not edit. */
#pragma once

#include <boost/preprocessor/cat.hpp>
#include <boost/preprocessor/tuple/elem.hpp>

#define GETTER(field) \
    BOOST_PP_TUPLE_ELEM(0, field) BOOST_PP_CAT(get_, BOOST_PP_TUPLE_ELEM(1, field))(const struct self *s) { \
    return s->BOOST_PP_TUPLE_ELEM(1, field); \
    }
