/* Generated by uncursed-pp from getter.uncursed — do not edit. */
#pragma once

#include <boost/preprocessor/cat.hpp>
#include "uncursed_pp_runtime.h"

/* uncursed-pp source:
 * # Getter function for one (type, name) field; concat() pastes the identifier.
 * @macro GETTER(field: tuple<type, name>)
 * @let getter := concat(get_, field.name)
 * {{field.type}} {{getter}}(const struct self *s) {
 *   return s->{{field.name}};
 * }
 * @endmacro
 */
#define UNCURSED_PP_GETTER_BODY1(type, name) \
    type BOOST_PP_CAT(get_, name)(const struct self *s) { \
    return s->name; \
    }
#define UNCURSED_PP_GETTER_BODY1_D(...) UNCURSED_PP_GETTER_BODY1(__VA_ARGS__)
#define GETTER(field) UNCURSED_PP_GETTER_BODY1_D(UNCURSED_PP_KW_SPREAD field)
