/* Generated by uncursed-pp from meta.uncursed — do not edit. */
#pragma once

/* uncursed-pp source:
 * # Jinja2 meta-templating: this source is expanded by Jinja2 (with
 * # alternative delimiters) BEFORE uncursed-pp parses it - the loop below
 * # writes one macro per register name at generation time.
 * @macro READ_CTRL($dev)
 * read_reg({{$dev}}, 0)
 * @endmacro
 */
#define READ_CTRL(dev) read_reg(dev, 0)

/* uncursed-pp source:
 * @macro READ_STAT($dev)
 * read_reg({{$dev}}, 1)
 * @endmacro
 */
#define READ_STAT(dev) read_reg(dev, 1)

/* # ── invocation specs (verified through cc -E by test_e2e_specs) ──
 * #?  READ_CTRL(d0)
 * #=>     read_reg(d0, 0)
 */

/* #?  READ_STAT(d1)
 * #=>     read_reg(d1, 1)
 */
