/* Generated by cursedpp from pair.cursed — do not edit. */
#pragma once

#include <boost/preprocessor/punctuation/remove_parens.hpp>
#include <boost/preprocessor/tuple/elem.hpp>

#define PAIR(p) S{ BOOST_PP_REMOVE_PARENS(BOOST_PP_TUPLE_ELEM(0, p)) | BOOST_PP_TUPLE_ELEM(1, p) }
