/* Generated by cursedpp from pair.cursed — do not edit. */
#pragma once

#include <boost/preprocessor/punctuation/remove_parens.hpp>
#include "cursedpp_runtime.h"

#define CURSEDPP_PAIR_BODY1(a, b) S{ BOOST_PP_REMOVE_PARENS(a) | b }
#define CURSEDPP_PAIR_BODY1_D(...) CURSEDPP_PAIR_BODY1(__VA_ARGS__)
#define PAIR(p) CURSEDPP_PAIR_BODY1_D(CURSEDPP_KW_SPREAD p)
